### ISSUE TITLE
Folder browsers with type-in area

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#1]
```
Some programs have a FolderBrowser that has an area that the user can type
the path in directly.  Is it a common control, or something custom?
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 11:56

**Comment by JoeBiellik** [comment]
The improved open folder dialog was introduced in Windows 7, unfortunately, it is not implemented in .NET natively.

It's relatively easy to upgrade dialogs, if supported, using a [library originally released by Microsoft](https://www.nuget.org/packages/Microsoft.WindowsAPICodePack-Shell/). I've used it before and I think it significantly improves the UX.

The library also includes other Windows 7+ shell improvements, I think it would be nice if we used the process indicator feature of the taskbar when scanning.

![Windows 7 Taskbar](https://i-msdn.sec.s-msft.com/en-us/library/system.windows.shell.taskbariteminfo.progressstate.cdacfba2-f256-4c82-bb62-bbf9b4a9d669(v=vs.110).jpeg)

**Comment by MarkSummerville** [comment]
I agree. Part of the v4 upgrade? or something we should look at now? Personally I think wait, but happy either way

**Comment by JoeBiellik** [comment]
I think we can do this in v3 considering its so minor to implement.

**Comment by MarkSummerville** [comment]
May fix this issue people are complaining about https://groups.google.com/forum/#!topic/tvrename/CSdRPIQcPbo

**Comment by JoeBiellik** [comment]
I can confirm the CommonOpenFileDialog works with UNC and mapped drives paths for me, however, I don't have any issue using these with the traditional dialog and textbox, other than it being tricky to browse.

**Comment by JoeBiellik** [comment]
Closing as the new dialog is implemented in the v3 branch.
