### ISSUE TITLE
Improve "keep files together" functionality

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#10]
```
* Exclusions for 'keep files together'
http://tvrename.com/bb/viewtopic.php?f=4&t=408
* Option for "all", "all but these" or "only these" extensions, perhaps.
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:06

**Comment by MarkSummerville** [comment]
Link is now: http://tvrename.com/bbold/4/t-408.html

I'll start work on it

**Comment by MarkSummerville** [comment]
UPdate - now http://old.tvrename.com/bbold/4/t-408.html
