### ISSUE TITLE
Handle duplicate episodes / upgrade to better quality episodes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#11]
```
* Find duplicate episodes: http://old.tvrename.com/bbold/4/t-388.html
* Automatically upgrade the quality of files in the media library

(This may be better done as two separate tasks)
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:08

**Comment by MarkSummerville** [comment]
Tracked as http://ideas.theideawall.com/TVRename/Forum/TopicDetails/56979057-2b75-4e0f-9e2f-4b77fe6f0df2?fb=0

Closing this one until we are ready
