### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#130]
```
What steps will reproduce the problem?
1. click scan button on scan tab
2.
3.

What is the expected output? What do you see instead?
should see list of missing episodes, get error message instead

What version of the product are you using? On what operating system?
2.2.4 on windows 7 64 bit

Please provide any additional information below.
have been using program just fine for over six months before this issue 
occurred.
attached is text file containing debug info from "details" box in error message.
```

Original issue reported on code.google.com by `jegarret...@gmail.com` on 18 Mar 2015 at 3:55

Attachments:
- [error text.txt](https://storage.googleapis.com/google-code-attachments/tvrename/issue-130/comment-0/error text.txt)

**Comment by MarkSummerville** [comment]
************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path)
   at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
   at System.IO.FileInfo..ctor(String fileName)
   at TVRename.ItemMissing.get_ScanListViewItem()
   at TVRename.UI.LVIForItem(Item item)

**Comment by MarkSummerville** [comment]
Put a fix in to stop this happening and speed it up
