### ISSUE TITLE
Disable episode overview text in My Shows and WhenToWatch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#14]
```
For episodes yet to be aired, perhaps "recent" ones as well.

Similar to hiding episode images in My Shows.

Avoids spoilers.

http://old.tvrename.com/bbold/4/t-398.html
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:12

**Comment by MarkSummerville** [comment]
Disable episode overview text in My Shows and WhenToWatch

**Comment by MarkSummerville** [comment]
* Hide Spoilers in My Shows
* Hide Spoilers in When to Watch

http://old.tvrename.com/bbold/4/t-398.html
