### ISSUE TITLE
Teracopy integration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#15]
```
http://tvrename.com/bb/viewtopic.php?f=4&t=396

When copying/moving missing items into media library.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:12

**Comment by MarkSummerville** [comment]
https://github.com/TV-Rename/tvrename/issues/15
https://github.com/TV-Rename/tvrename/issues/61
http://old.tvrename.com/bbold/4/t-396.html

Raised as http://ideas.theideawall.com/TVRename/Forum/TopicDetails/3ca8665a-2968-4b6c-9220-420fd3c942e4?fb=0, so closing here for now
