### ISSUE TITLE
Touch file with airdate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#16]
```
http://tvrename.com/bb/viewtopic.php?f=4&t=392

(and folder too?)
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:13

**Comment by MarkSummerville** [comment]
Link is now http://old.tvrename.com/bbold/4/t-392.html

**Comment by MarkSummerville** [comment]
Tested - looks good
