### ISSUE TITLE
Prompt what to do with unmatched files in search folders

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#17]
```
http://tvrename.com/bb/viewtopic.php?f=4&t=394

Prompt, or maybe show as to-do item, with right-click or double-click
showing the list of unmatched missing items.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:14

**Comment by MarkSummerville** [comment]
Tracked as http://ideas.theideawall.com/TVRename/Forum/TopicDetails/4acc1b1e-f1fe-4c94-9eae-7df050bd0fe8, so closing this one until we are ready to start work
