### ISSUE TITLE
2.3b3 moving files?

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#170]
Is it just me or is beta 3 automatically moving found files?

If so is it an option I can turn off?:(can't see anything obvious!)

**Comment by jamoamo** [comment]
I think I'm seeing the same thing. I have the "Copy Files, don't move" option checked but when the action is performed the file is moved instead of copied.

**Comment by Andy-ABTec** [comment]
I think that is probably a slightly different issue - this is a beta after all!
I'm not actually "asking" TV Rename to do anything with the file, it seems that it happens on its own. I'm not sure yet if it only happens after the download completes or if it tries and fails during the download - still investigating...

**Comment by MarkSummerville** [comment]
TV Rename can automatically listen for changes in a directory and then take action. See https://tv-rename.github.io/tvrename/settings#search-folders for config screen that deals with this function.

Separately jamoamo has correctly noted that the "Copy Files, don't move" function  always moves now. I have just patched an update

**Comment by Andy-ABTec** [comment]
Doh! missed the tick box - sorry!
