### ISSUE TITLE
2.3b2 cold install bad link on first page

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#172]
Having just performed a new cold install of 2.3b2 I'm seeing a "Can't reach this page" error on the information pane of "My Shows"

I Think either the web page address needs to be "**www**.tvrename.com" or the software needs tweaking to point to "tvrename.com"

Andy B.

**Comment by Andy-ABTec** [comment]
OK, I'm still seeing the same 404 error but the text has changes to be GitHub specific, it now reads: -

```
404
File not found
The site configured at this address does not contain the requested file. 

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file. 

Read the full documentation for more information about using GitHub Pages. 
```
From what I can tell crawling the site there is no index.html... 😟

**Comment by MarkSummerville** [comment]
Beta 3 should fix this

**Comment by MarkSummerville** [comment]
Added to 2.3 RC1 release
