### ISSUE TITLE
Preserve suffixes, e.g. "HDTV",

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#19]
Preserve suffixes, e.g. "HDTV", etc. 

http://old.tvrename.com/bbold/4/t-277.html

* Define specific suffixes to keep?
* Need to avoid "release group" suffixes.
* Need to keep language suffixes for subtitled shows.

There is currently some logic that attempts to preserve language tags when
doing the "keep files together" thing.

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:19

**Comment by MarkSummerville** [comment]
Tracked as http://ideas.theideawall.com/TVRename/Forum/TopicDetails/551827fa-6dde-4038-9d6a-b626d568eec4?fb=0, so closing this one
