### ISSUE TITLE
2.3.6 - Full Scan Problem?

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#191]
Not sure if it's just me, but when I run a Full Scan in 2.3.6 I'm seeing an unhandled exception...

![2017-12-22_092440](https://user-images.githubusercontent.com/5175695/34293371-77ce9a66-e6fc-11e7-9005-f2055fa5bf7a.png)

Just went back and double checked... Recent and Quick scans are fine, it appears to be just the Full Scan that has the problem.

**Comment by MarkSummerville** [comment]
What details does it give? Be good if we had some logging :-)

**Comment by MarkSummerville** [comment]
It's OK - fixed it!

**Comment by Andy-ABTec** [comment]
STAR!
