### ISSUE TITLE
2.3.6 - Log files not being created?

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#192]
Sorry, for me the log files aren't appearing, The content of C:\Users\Andy\AppData\Roaming\TVRename tree is exactly the same after I save and exit as it was before 8-(

**Comment by MarkSummerville** [comment]
do you have a nlog.config file in your tvrename install folder ? If not can you please try adding one from here? https://github.com/TV-Rename/tvrename/blob/master/TVRename%23/NLog.config

**Comment by MarkSummerville** [comment]
Looks like it's fixed in 2.3.8 .https://github.com/TV-Rename/tvrename/releases/tag/2.3.8
