### ISSUE TITLE
Bulk Add Shows: show tick beside folders with both tvdb code and season number

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#2]
```
Indicate with icon which items in the folder monitor have all the necessary
details.
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 11:56

**Comment by MarkSummerville** [comment]
looks like one to take when we refactor this code

**Comment by JoeBiellik** [comment]
I've added a check or cross to the "Folder Monitor" results tab listview to make it clear if the show has been ID'ed or not, is that was this issue refers to?
