### ISSUE TITLE
Legacy Branches

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#204]
It looks like there are a lot of [legacy branches](https://github.com/TV-Rename/tvrename/branches) that were imported into git.

Do any of these branches have any code worth merging? Can any be safely deleted? My concern is the more development we do to master the harder it's going to be to see what these branches changed.

**Comment by MarkSummerville** [comment]
I *think* I have previously gone through them and dug out anything useful (during the google code days). I'll start picking through and closing them formally now

**Comment by MarkSummerville** [comment]
For example the following commits are manual merges of some of these branches into master:
https://github.com/TV-Rename/tvrename/commit/e8b84f03fb2970a57fb498d2c8c8aef80dd3c3d2
https://github.com/TV-Rename/tvrename/commit/75eafa581ceb2ab9ee53cc308c2362cd3f9f90bf

**Comment by JoeBiellik** [comment]
Good work, I definitely think it's worth making sure we have everything in master before doing more major reformatting.

**Comment by MarkSummerville** [comment]
OK - we are down to 2 'spare' branches:
 * tvrename3 - An aborted attempt to change the Settings from the current XML to use RavenDB
 * cf - Mostly already added, but includes 3 changes I want to spend a bit more time on:
     * ShowSummary UI - this was never merged in and may be useful.
     * Change to TVDB that if >10% of episodes are dirty then the whole series is refreshed. This was removed in the move to json TVDB API, but we should consider this function
     * Imrpoved handling of cancelling a copy midway through

**Comment by MarkSummerville** [comment]
Looks like the cancel is delivered a different way in the new multithreaded code:
`            this.ActionProcessorThread.Start(queues);

            if ((cmp != null) && (cmp.ShowDialog() == DialogResult.Cancel))
                this.ActionProcessorThread.Abort();

            this.ActionProcessorThread.Join();`

**Comment by JoeBiellik** [comment]
If we want to keep the RavenDB efforts maybe we should rename the branch so its a little more obvious what it is.

I built the cf branch and gave the show summary a go. I found it very slow, it froze the UI and seemed to take at least 10x longer than a full scan. Personally, I don't think the UI adds a lot, but if it was maybe integrated into the scan results it could be helpful and save running a second slow process.

For the canceling, I think a bigger refactor is needed. There are a lot of times using the latest code that the UI locks up and I think the underlying async system needs to be rethought. I would personally like to see the project target .NET 4.5 and use the native async/await just for simplicity.

**Comment by MarkSummerville** [comment]
I think we keen the RavenDB efforts off to the side. I'd definitely like to rename the branch though. (not sure how to do that though! - I don't have command line GIT access yet,  looks like I'll need to!)

I'm just testing the "10% of episodes are dirty" change and will have a PR ready soon as I think that is worth including.

I agree that there is a bigger refactor needed. I'd like to include review of the IPC calls as part of that. Better ways have been developed over the last 10 years and too many commits (mainly mine!) have not helped and have code in the wrong threads etc. Therefore I suggest we leave this out

Re `ShowSummary` then I will work on getting it working in a performant fashion that will merge with the current codebase and then stick it on a branch in my fork in case we want to use it (even just for ideas in a subsequent rewrite/redesign). There are a few performance enhancements that have been put into the codebase that it does not leverage yet.

**Comment by JoeBiellik** [comment]
I've renamed the branch to ``ravendb`` and I agree on your other points so I'll close this now.
