### ISSUE TITLE
File header comment

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#210]
Some, but not all, of the source files have a comment header with the old Google Code link.

Does anyone feel these comments are necessary? If so I'll replace the link and add it to all files, otherwise, we can remove them.

**Comment by MarkSummerville** [comment]
I’d be inclined to replace them all with the new links, but I can’t really see the need for them. Anyone could google search and find the code in 10 seconds

**Comment by JoeBiellik** [comment]
My thoughts as well. If no one objects I'll remove them in a few days.
