### ISSUE TITLE
TV Rename vs TVRename

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#216]
Just for clarification is the project officially ``TV Rename`` or ``TVRename``? It seems like recent efforts in the code and docs are using the space, but the [Google groups](https://groups.google.com/forum/#!forum/tvrename) and [feature tracker](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0) etc are not. I think it should be unified just to avoid confusion and simplify searching.

Personally, I prefer it with the space.

**Comment by Andy-ABTec** [comment]
My vote would be for TV Rename as well, at least that's what I'm slowly heading towards in the web pages.
I'd guess that TVRename came about due to lack of space (" ") support on some systems (web and otherwise)

Andy B.

**Comment by MarkSummerville** [comment]
I agree so I have updated the groups and feature tracker to include the space where possible. Let me know of anywhere I've missed. Some things such as email addresses and some URLs need to stay as 'TVRename' though

**Comment by Andy-ABTec** [comment]
Which URL's have you changed? Docs may need tweaking to match...

**Comment by MarkSummerville** [comment]
I don't  think any URLs have changed

**Comment by Andy-ABTec** [comment]
@MarkSummerville, apologies got thrown by: -
 >email addresses and **_some URLs_** need to stay as 'TVRename'

**Comment by JoeBiellik** [comment]
Closing as I think we have updated everywhere.
