### ISSUE TITLE
Technical documention

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#219]
I'm looking through the documentation and I found a few small changes for the [technical page](http://www.tvrename.com/technical).

* ``But Hey, why would you want to do that?``, lowercase the ``hey``?
* ``And on Windows 7 and later: -`` should be ``Windows Vista``, on the page in 2 places.
* We no longer use ``DotNET Zip`` as a dependency.
* Resharper link should be ``https://www.jetbrains.com/resharper/`` (HTTPS), dotTrace needs HTTPS as well.
* SourceGrid link should be ``https://sourcegrid.codeplex.com/``.
* ANT link should be ``https://www.red-gate.com/products/dotnet-development/ants-performance-profiler/``.
* We now use [Json.NET](https://www.newtonsoft.com/json) dependency.
* We should probably list [NLog](http://nlog-project.org/) under the credits.

I didn't want to make the changes myself as I know @Andy-ABTec is probably working on it.

**Comment by Andy-ABTec** [comment]
Thank-you kindly 8-)
I'll go fix later...

**Comment by Andy-ABTec** [comment]
Tweaking done, please can you check it...
You can see the update at https://andy-abtec.github.io/tvrename/technical.html

I'm using this gh-pages repo/site as a test-bed before I raise pull requests to the main repo.

Happy to make you a collaborator if you wish, I'm trying to stop multiple copies of the pages appearing and being a nightmare to merge later.

_Any other proofing you care to do please feel free!_

BTW how did you get the ```documentation``` label on this, I couldn't find it anywhere (having said that I've only been using GitHub for a little over a week :confused:)

**Comment by JoeBiellik** [comment]
Looks good!

You can set labels in the sidebar, there is a cog icon, but I think you might need to have the correct GitHub permissions first, maybe @MarkSummerville could take a look.
