### ISSUE TITLE
Options>Preferences>General - questions...

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#223]
Please can someone confirm for the User Guide: -

1. "Download up to 'X' shows simultaneously from thetvdb" - bandwidth limitation? some other reason? should it be "thetvdb", "thetvdb.com", "The TVDB" or "TheTVDB"?

2. "Automatically select show and season in My Shows" -  does this only work from "When to watch" or from anywhere, a show and season can be gleaned?

3. "Look for airdate in filenames" - couldn't get my head round this, does this literally mean look in the filename - if so is the format an issue? or look at the date of the file?

4. Presume "Preferred language" picks up from the system but you can override it?

Thanks!

**Comment by JoeBiellik** [comment]
1. I'm not familiar with the lastest TVDB API code, but I can tell that it's officially named "TheTVDB".
2. This works when on "When to watch" and "Scan" tabs, when selecting an item on these tabs, the "My Shows" list is automatically updated to highlight the show and season.
3. I've not used this so I may be wrong, but it looks like[ the code is checking the filename for a number of date formats](https://github.com/TV-Rename/tvrename/blob/master/TVRename%23/TVRename/TVDoc.cs#L2608) and using that to find which episode it is from the air date.
4. This is the language that we ask for from TheTVDB, if unavailable it falls back to English data.

**Comment by Andy-ABTec** [comment]
Thanks @JoeBiellik, just as well I checked, the wording of 4. does not make that at all obvious.

I'll go fix what you've given me but leave this open for a while in case anyone else has anything to add.

I'm afraid there's probably going to be a few more of these as I work my way through the Application

**Comment by MarkSummerville** [comment]
Re 4 - there was talk of also allowing 'per show' language setting, but that is not implemented (yet). The user can select a preferred language to request data from TheTVDB. If that language is not available then TV Rename will request English as a backup (as @JoeBiellik explained above)

**Comment by Andy-ABTec** [comment]
Think this is pretty much sorted now, so closing...
