### ISSUE TITLE
Options>Preferences>Automatic Export

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#226]
Said I'd be back...

Can someone please tell me what triggers the "All Shows" TXT export?

I've figured out the other three but can't nail this one...

Ta!

**Comment by MarkSummerville** [comment]
Whenever a show is added, edited or deleted from the UI. (possible that it does not get used when doing a Folder Monitor -> Auto Id All though - I'll check)

**Comment by MarkSummerville** [comment]
Yes, there is a bug here. File was saved twice when deleting a show and not saved at all when adding multiple. Fixed in https://github.com/MarkSummerville/tvrename/commit/3a7b2864bd1ee744a7ad2344e4e8b4a3927471a1

**Comment by Andy-ABTec** [comment]
Thank you!
