### ISSUE TITLE
Settings>Options Media Center update? 

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#229]
Does the Settings>Options Media Player tab need updating?

![preferences-media-center-01](https://user-images.githubusercontent.com/5175695/34455426-136c9682-ed77-11e7-9148-e0eb2410f219.png)

I note that KODI (the only one I use) has radio buttons for Eden and Frodo. Since then we've had Gotham, Helix, Isengard, Jarvis and (currently) Krypton with Leia due for release soon.

Possibly XBMC/Kodi has settled down enough to make the buttons redundant? 

I know nothing of the others but perhaps someone who uses them could check?

Thanks!

**Comment by MarkSummerville** [comment]
Yeah - we should update something. The way that images were stored changes in XBMC between Eden and Frodo, so it should really say Eden-and-earlier and Frodo-and-later

In any case, I'd be happy removing Eden support due to its age (or at least redesigning it)

**Comment by MarkSummerville** [comment]
http://kodi.wiki/view/XBMC_v12_(Frodo)_FAQ#Local_images explains the differences (well the new format at least)

**Comment by JoeBiellik** [comment]
I agree that Eden is now too old to support and could be removed. If we are working on the metadata settings I'd like to see some more options included, #95 etc.

**Comment by Andy-ABTec** [comment]
I think I'd be inclined to pull Eden altogether, it was only out in the wild from March 2012 to January 2013

**Comment by MarkSummerville** [comment]
Can this be closed?

**Comment by Andy-ABTec** [comment]
Depends, the radio buttons are still there...
Having just re-read #243 if its down for V3 then probably "yes, close it" if its still down for V2.? then probably "no, dont close it" 

Is it possible to "fix" the button variable to "both" and hide the buttons on the form? If not, what do you want me to say about the form in the documentation?

**Comment by MarkSummerville** [comment]
There is a fix in place linked to this that is scheduled for v3. I don't see any point changing code prior to that.  In the doco I am happy to have anyuthing. If it were me I would just be a little vague about the Frodo/Eden option or not mention it at all so that the updates needed when v3 comes along are small

**Comment by Andy-ABTec** [comment]
OK, no problem.... closing!
