### ISSUE TITLE
Settings>Options µTorrent / NZB tab? 

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#232]
Perhaps http://tvrss.net/feed/eztv should be removed from this tab as it doesn't exist any more?

**Comment by JoeBiellik** [comment]
Yes, along with most of the built-in torrent sites.

**Comment by Andy-ABTec** [comment]
In the guide I played it as:
https://andy-abtec.github.io/tvrename/options#search-engines
I figured doing it this way meant we weren't DIRECTLY giving links to torrent sites, just providing enough information for people to work it out for themselves.
I doubt that the complexity of TV Rename would attract a "novice"...
Thoughts?

**Comment by JoeBiellik** [comment]
I see no point in keeping any dead links, I think only two of the default links currently work. Personally, I would remove all the torrent links and add Google and maybe a usenet site as examples.

**Comment by Andy-ABTec** [comment]
OK, Google I can do no problem, but I haven't used usenet since the days of Agent and FreeAgent on windows 95 can you supply a usenet example please?

BTW https://andy-abtec.github.io/tvrename/options is probably "alpha" at the moment, give me a couple of days and I should have a "release candidate" for initial proofing

**Comment by JoeBiellik** [comment]
@Andy-ABTec please see #235, that provides a search engine, torrent site, and usenet site.

**Comment by Andy-ABTec** [comment]
Got it - thanks

**Comment by MarkSummerville** [comment]
Can this be closed?

**Comment by Andy-ABTec** [comment]
Yes, Sorry been looking/thinking about other stuff!
