### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#233]
Does/did TV Rename have a changelog? I know @MarkSummerville has been adding notes to the last couple of GitHub releases but do we have a list of everything that has changed since the 2.2.4 release?

**Comment by JoeBiellik** [comment]
I've added a [changelog wiki page](https://github.com/TV-Rename/tvrename/wiki/changelog), it would be helpful if we tried to keep it up to date with changes as we merge them.

**Comment by MarkSummerville** [comment]
@JoeBiellik Happy to close

**Comment by JoeBiellik** [comment]
Yeah, I'll keep the wiki page updated with v3 changes so far.
