### ISSUE TITLE
Targeting .NET 4.5 for Async

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#237]
A lot of the more complex and questionable code is dealing with the UI threading due to blocking operations. I feel it would be very advantageous to use .NET 4.5's TPL with C# 5.0 async/await to easily make long-running operations asynchronous.

This would mean targeting .NET 4.5 over 4.0. The only major difference is that this would mean [dropping Windows XP support](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements#supported-client-operating-systems). Considering XP has been officially End of Life for 3 years now, I'm not sure this is such a bad thing.

Is anyone still using XP, does anyone have any objections?

**Comment by MarkSummerville** [comment]
Yeah. I think this is a good plan. Will put a call out on the Forums to see if anyone is still using xp

**Comment by mhurwood** [comment]
Seconding this, along with total separation of the UI from the "business logic" code. i.e. the two should go hand-in-hand.

**Comment by Andy-ABTec** [comment]
Just a thought - I note that the website has Google Analytics enabled (at least there's an Google Analytics code in config.yml), that should have details of the browsers in use among its stats...

Might give an hint to the operating systems in use. I know its targeting the website not the app but why read the pages if you don't have the software?

**Comment by Andy-ABTec** [comment]
Does anyone have access to TV Rename's Google Analytics, or do I try need to try and persuade Google to associate the ID with a new email address?

**Comment by MarkSummerville** [comment]
I have access.  It’s only been giving us data since the new site went out though. The previous website had GA too, busy I don’t have access to that data

**Comment by MarkSummerville** [comment]
0.44% use XP according to the stats. I have put a call out in the forum too though

**Comment by MarkSummerville** [comment]
I think we can close this. v3 includes targetting v4.5
