### ISSUE TITLE
Website options.html page - Release Candidate

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#239]
It's been a bit of a vertical learning curve battling against the template and the markdown but I think I've got something just about ready for inclusion in the main site. I originally started with the userguide but needed to refer to options and tools so often that I thought options was a better place to build first (tools next!).

Mark, this is the best I can do with the navigation for now (within the restrictions of the template) - please let me know what you think

https://andy-abtec.github.io/tvrename/options

I think
https://andy-abtec.github.io/tvrename and
https://andy-abtec.github.io/tvrename/technical 

are probably ready to go as well - at least until the App Data file structure is changed...

Please take a look/proof read etc

Before anyone else spots it, I'm aware of the issue with links apparently missing their id targets in the main body, The raw Jekyll template "Leap Day" does it as well (already raised a bug - https://github.com/pages-themes/leap-day/issues/7 though I dont hold much hope judging by stale bot actions there)

Happy reading - I'm going to go and put my head in a bucket for a while...

**Comment by Andy-ABTec** [comment]
I think https://andy-abtec.github.io/tvrename/technical is ready to go as well - at least until the App Data file structure is changed...

**Comment by MarkSummerville** [comment]
Looks great - we’ll done.  If you open a pull request I can merge it into the main site. Cheers

**Comment by Andy-ABTec** [comment]
I'm in the middle of fixing some minor bits and pieces at the moment (and working on tooks.md) 

Anything for anyone else?

**Comment by Andy-ABTec** [comment]
If not I'll push later this evening when I reach a suitable spot...

**Comment by MarkSummerville** [comment]
Just checking this can be closed?

**Comment by Andy-ABTec** [comment]
Certainly can...
