### ISSUE TITLE
Detect airdate in filename

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#24]
```
http://tvrename.com/bb/viewtopic.php?f=7&t=207

Improvement to FindSeasEp ?

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:25

**Comment by MarkSummerville** [comment]
FYI http://old.tvrename.com/bbold/7/t-207.html

Looks like we'd need to:
 * support another type of RegEx to match yyyymmDD
 * Allow user to choose to save files as S0xE0y or with airdate in the filename (if this is not already done)
* Check that the RegEx matches the format that we output the file with
