### ISSUE TITLE
Make 'season' special word configurable

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#241]
See https://groups.google.com/forum/#!topic/tvrename/WpuR5qVggiw

**Comment by Andy-ABTec** [comment]
If you're going to make "Season" configurable, put it in Options>Preferences>Files and Folders, it can keep "Specials" company (but I guess you already thought of that!)

**Comment by MarkSummerville** [comment]
More of a note to self: configure the default ,season’ word that is used to create directories, configure the list of words used in the auto search ( semi colon separated) and then use the union of both plus the set of custom words used for each series. Use this combined list to search for appropriate folders.
