### ISSUE TITLE
Refresh - how many ways?

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#248]
Apologies, I said I'd be back...

I was looking at paths for refreshing data - some of these are obvious, some not so much, please can someone confirm or deny (- or preferably correct!) this little lot?

I'm trying to "demistify" stuff for the User Guide

Options
* Offline Operation (block internet access?, Tools>Force... overrides?)
* Automatic Background Download (thetvdb.com - on a timer? triggered by other actions? both? 

Tools
* Force Refresh All (thetvdb.com? the Media Library? both? overrides Offline Operation?)
* Background Download Now (thetvdb.com?)

My Shows
* Refresh Button (thetvdb.com? everything)
* Right Click Force Refresh with a show highlighted (complete show from thetvdb.com?)
* Right Click Force Refresh with a season of a show highlighted (season of a show from thetvdb.com?|) 

Scan
* Full (The Media Library?)
* Recent (The Media Library?) Differences?
* Quick (The Media Library?)

Is the "Options" button really necessary, it's confusing, it opens up "Preferences" not "Options" and the real "Options" menu is only 60mm away?

When to watch
* Refresh (thetvdb.com? everything?)
* Right Click Force Refresh (thetvdb.com show or season?)

Apologies again...

**Comment by Andy-ABTec** [comment]
Just found this: -

There are 3 types of scan you can choose from :
* Full - A full scan of all shows
* Recent - Scan of all the shows that have aired in the last 7 days
* Quick - Scan just the shows that are in the last 7 days and have a missing episode on disk. Plus any shows that match a media file in the download folder.

So that's a bit less...

Is it fixed 7 days or is it taken from the number of days = recent in **Options>Preferences>General**?

**Comment by JoeBiellik** [comment]
I'll do my best to answer but I've not spent a lot of time looking at this part of the codebase, so take it with a grain of salt.

### Options
> Offline Operation

This toggles internet access to TheTVDB.com. When this is enabled all metadata is loaded from the local cache (TheTVDB.xml) and new updates are not downloaded.

> Automatic Background Download

This simply fires off a TVDB refresh 10 seconds after startup then every 60 minutes.

### My Shows
> Refresh

This is the basic refresh mentioned above, for each added show it contacts TheTVDB.com and downloads new metadata based on the last sync timestamp. Under the hood, there is a bit more going on, like completely redownloading a show if more than 10% of episodes have changed, but the end user doesn't need to know about this.

> Force Refresh

As above but will always completely redownload the metadata. AFAIK, no matter what you select (show, season, episode) the entire show is processed.

All the other places should follow the same convention when it comes to "refresh" and "full refresh".

Recent and quick scans do use the number of days from the options.

**Comment by Andy-ABTec** [comment]
Thanks for that it really helps, anyone got anything to add?

**Comment by MarkSummerville** [comment]
I think joe covered it all? A ‘force refresh all’ is not that bad - just
time consuming as it’ll go back to tvdb for all your data. Nothing about
your settings or preferences are lost.

There is also a refresh images that just reloads images for a series/show.
Useful because TV rename chooses posters/banners based on the most popular
for that language. Often, what is popular changes and you may wish to
refresh.

Anything else you need to know?

**Comment by MarkSummerville** [comment]
Nb we should probably make refresh period configurable and setup an auto scan period at the same time

**Comment by Andy-ABTec** [comment]
That's great thanks to you both...

Will probably push another website update late today.
