### ISSUE TITLE
Torrent Match broken?

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#249]
Can't get this to work as described...

Just to make sure I deleted a recent file from my media library, found its torrent and downloaded it again, then let TV Rename move it into the media library, and keept the torrent file.

"Browse..." for the torrent file works, I can see it.
"Browse..." to the folder with my file in it works, I can click "Open" and see the file.

Action: "Rename files", click "Go"
The Window below is populated with the BT "tree", but nothing else happens, looking in the source folder there is no change.
 
Action: "Copy To:" click "Browse"
Bottom text box "wakes up" and I can select a path but when accepted  it is put in the "Folder" box above overwriting the source path.

Put the source folder box back as it was and type a path in the bottom box, "Open" now works, but "Go" still does nothing!

What am I missing?

**Comment by MarkSummerville** [comment]
Sorry, am on holiday at the moment and can’t get to he bottom of this for a couple of weeks. It may well do nothing at all!

**Comment by MarkSummerville** [comment]
It’s something I’d have to investigate in the code as it’s not something I use. I know it does some hashing of the files to try and match them up with the downloads, so maybe something has changed there?

**Comment by JoeBiellik** [comment]
I've never used this feature either, but I'm working on the ``Finders`` so I'll have a look at this next.

**Comment by MarkSummerville** [comment]
#277 will hide these features until people are ready to update/use them
