### ISSUE TITLE
The Status bar?

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#250]
Silly question: what's the box on the right hand side of the status bar for? - In all my fiddling about I'm sure I haven't seen it do anything yet!

Also - possibilities for V 3?
I note that the status bar shows "Background Download:" as Idle or the info being downloaded, would be nice if it said "Disabled" as well, or even just flipping between "Busy", "Idle" and "Disabled".

This would make more space and allow "Offline Operation" status to be shown as well, though that would probably be better shown as "Online Operation" / "Offline Operation", maybe with a red/green coloured background...

**Comment by JoeBiellik** [comment]
It's a progress bar - from a quick glance it seems like its only used for uTorrent related activities.

I agree the status bar needs a rethink for v3; the way I use TV Rename there is never any valuable information shown.

**Comment by Andy-ABTec** [comment]
That explains it then... I can't get the uTorrent tools to work.

#249 refers but there may be other areas I haven't properly broken yet!&emsp; :sunglasses:

**Comment by MarkSummerville** [comment]
closable?

**Comment by Andy-ABTec** [comment]
Don't see why not, just seemed a waste of real estate that could be used for something else

**Comment by Andy-ABTec** [comment]
Don't see why not, just seemed a waste of real estate that could be used for something else
