### ISSUE TITLE
My Shows - Images tab

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#251]
If no images are available the tab incorrectly describes the path to Media Centre as:

**Options->Settings->Media Center** rather than **Options->Preferences->Media Center**

I would Imagine that **Settings** got renamed to **Preferences** at some point and the error messages got left behind - so there may be others I haven't found yet!

**Comment by JoeBiellik** [comment]
I had a look through, couldn't see anywhere else it was left as settings.

**Comment by Andy-ABTec** [comment]
Thanks
