### ISSUE TITLE
Wiki New Page -Thoughts for Future Versions

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#261]
Just created this page so I've got somewhere to scribble down ideas for future Versions so I don't forget
They're not issues just ideas - hence the Wiki rather than here!

Maybe we need to think about a private developer forum so stuff can be discussed rather than raising unnecessary issues?

Feel free to add to it, that was the whole point of creating it in the first place...

**Comment by MarkSummerville** [comment]
Good idea. Here you go: [forum](https://groups.google.com/forum/?nomobile=true#!forum/tv-rename-development)

As for the feature ideas then either raise on the idea wall or as issues  on github. To me they fit neatly on there.

**Comment by MarkSummerville** [comment]
Re releases then I would see the forum going away over time and just using the github releases page.   Having two places is a waste of time. I think we should take download links from the main exe and put them onto the website.

**Comment by Andy-ABTec** [comment]
Apologies - I wasn't aware of a GitHub releases page, let me know where it is and I'll link it to the website. (Up until now I've always found new releases in the releases forum 8-)
BTW the download link in the download forum seems broken - sorry!

**Comment by MarkSummerville** [comment]
https://github.com/TV-Rename/tvrename/releases. I see you found the new forum! :-)

**Comment by Andy-ABTec** [comment]
Thanks for that, I just need to figure out where to put it on the website now

**Comment by Andy-ABTec** [comment]
Download link done - just needs my pull request processing.

New wiki page now gone as well - please close this when you're ready...
