### ISSUE TITLE
Crash when changing preferred language

### ISSUE THREAD

**Issue by exe22** [TV-Rename/tvrename#266]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [x ] I checked the [documentation](http://www.tvrename.com/userguide) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [x ] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [x ] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))

# Expected Behaviour

I want to change the preferred language in the preferences menu to German.

# Current Behaviour

After changing the language to German and hitting the OK button the application crashes 
![screenshot_3](https://user-images.githubusercontent.com/35178756/34644264-4f42e596-f333-11e7-99ce-f7c592e8f1e0.jpg)

# Failure Information

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\Ben\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   bei System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   bei TVRename.TheTVDB.SaveCache()
   bei TVRename.Preferences.OKButton_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2600.0 built by: NET471REL1LAST.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
TVRename
    Assembly-Version: 2.3.0.0.
    Win32-Version: 2.3.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/TVRename/TVRename.exe.
----------------------------------------
NLog
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.4.5791.
    CodeBase: file:///C:/Program%20Files%20(x86)/TVRename/NLog.DLL.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2600.0 built by: NET471REL1LAST.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.ServiceModel
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
Microsoft.VisualBasic
    Assembly-Version: 10.0.0.0.
    Win32-Version: 14.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll.
----------------------------------------
System.Runtime.Remoting
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll.
----------------------------------------
AlphaFS
    Assembly-Version: 2.1.0.0.
    Win32-Version: 2.1.3.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/TVRename/AlphaFS.DLL.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
SourceGrid
    Assembly-Version: 4.40.4580.29115.
    Win32-Version: 4.40.4580.29115.
    CodeBase: file:///C:/Program%20Files%20(x86)/TVRename/SourceGrid.DLL.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 10.0.0.0.
    Win32-Version: 10.0.3.21018.
    CodeBase: file:///C:/Program%20Files%20(x86)/TVRename/Newtonsoft.Json.DLL.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Options -> Preferences
2. Change Preferred Language to German
3. Hit OK
4. The application crashes

## Context

![screenshot_4](https://user-images.githubusercontent.com/35178756/34644283-bcae44b8-f333-11e7-91e5-ea2b44cfa972.jpg)

## XML Files

not yet created

**Comment by MarkSummerville** [comment]
Hi, can you help with a few questions please?
* Is this a new or upgrade installation? 
* does the following location exist? C:\Users\Ben\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml
* if not, are you able to find the xml file somewhere else? 

Thanks, danke

**Comment by exe22** [comment]
Hi Mark,

this was a new installation, I never used tvrename before.
There is a path _C:\Users\Ben\AppData\Roaming\TVRename_ but inside is only a _log_ folder which contains the following TVRename.log

`
2018-01-06 22:43:26|INFO| TV Rename started with args: 
2018-01-06 22:43:27|INFO| Starting new instance
2018-01-06 22:43:27|INFO| Loading Cache from: C:\Users\Ben\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml
2018-01-06 22:43:27|INFO| Loading Settings from C:\Users\Ben\AppData\Roaming\TVRename\TVRename\2.1\TVRenameSettings.xml
2018-01-06 22:43:33|INFO| Status on screen updated: Connecting to TVDB
2018-01-06 22:43:33|INFO| Status on screen updated: 
2018-01-06 22:43:33|INFO| Status on screen updated: TheTVDB Languages
2018-01-06 22:43:34|INFO| Status on screen updated: 
2018-01-06 22:44:30|INFO| Saving Cache to: C:\Users\Ben\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml
2018-01-06 22:59:43|INFO| Application exiting
`
I tried to find the TheTVDB.xml but it seems like there is no such file anywhere.

Thank you!

**Comment by MarkSummerville** [comment]
Hi,

Can you try and create the appropriate directory please? We have recently
changed the installer/app, so I think we may have introduced a bug.

If you can create the directory then retry then you may have a solution.

Thanks

**Comment by JoeBiellik** [comment]
I can confirm this can be recreated by deleting the TVRename appdata directory; as the directory does not exist whichever XML file it tries to write first will cause the error.

@exe22 if you manually create ``C:\Users\Ben\AppData\Roaming\TVRename\TVRename\2.1\`` directories this should fix it.

@MarkSummerville I'm not sure what we changed to stop creating to initial directory tree, it wasnt the [old installer](https://github.com/TV-Rename/tvrename/blob/450e46cba97b60cece1033bdca64c2bb5817a31e/Installer/TVRename.nsi).

**Comment by JoeBiellik** [comment]
Found the issue:
```diff
- return GetFileInfo(System.Windows.Forms.Application.UserAppDataPath, LayoutFileName);
+ return GetFileInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "TVRename", "TVRename", "2.1"), LayoutFileName);
```

From [Application.UserAppDataPath](https://msdn.microsoft.com/en-us/library/system.windows.forms.application.userappdatapath(v=vs.110).aspx#Anchor_1):
> "If a path does not exist, one is created"

I'll make a patch to manually create the directory tree at startup.

**Comment by exe22** [comment]
This worked. Thank you very much!
