### ISSUE TITLE
TvRename is moving files when it should be copying them.

### ISSUE THREAD

**Issue by jamoamo** [TV-Rename/tvrename#267]
# Expected Behaviour

When configured to copy files, not move (Options->Preferences->Scan Options), missing episodes found in the search folder should be copied to the target directory and renamed, leaving the original file in the source folder.

# Current Behaviour

The file is being moved to the target directory and renamed. The file is removed from the source folder.

# Failure Information

I think the logic in file ActionCopyMoveRename file line 79 should be reversed as follows. 

`                if (FileHelper.Same(this.From, this.To))
                {
                    ...`

->>>>>

`                if (!FileHelper.Same(this.From, this.To))
                {
                    ...`

I'll create a pull request with this change shortly. Logging this issue for tracking purposes. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. configure TvRename tp copy files, not move them (Options->Preferences->Scan Options, check "Copy files, don't move"),
2. ensure there is a missing episode which exists in the search folder
3.  run scan, do actions
4. The file no longer exists in the search folder but exists in the target folder

**Comment by JoeBiellik** [comment]
Thanks very much for the reporting this, I can confirm I'm able to recreate it.
