### ISSUE TITLE
Make a playlist of recent episodes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#27]
```
http://tvrename.com/bb/viewtopic.php?p=799#p799
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:30

**Comment by MarkSummerville** [comment]
WHat format would the playlist be?

**Comment by JoeBiellik** [comment]
Rather than just adding playlist export I think it makes more sense to add full export functionality to each of the tabs. The user could then choose what format to export the data from each tab as; playlist, XML, RSS, calendar (#37) etc?

**Comment by Chlorel** [comment]
My Show Collection proposal can be a solution to that : Why not creating a Collection with *Current entering season's* ? So all Refresh, Scan and other stuff just done on this *part* from all stuff on disk's

**Comment by MarkSummerville** [comment]
I think this is the thread
http://old.tvrename.com/bbold/4/t-188.html
