### ISSUE TITLE
Unhandled exception. "Could not find a part of the path " For RSS file output of 'when to watch'

### ISSUE THREAD

**Issue by palentir** [TV-Rename/tvrename#273]
# Expected Behaviour
When you open the software, it doesn't crash.

# Current Behaviour
When I opened the software it crashed

# Failure Information
Unhandled exception. "Could not find a part of the path "c:/blahblah/file.rss"

## Steps to Reproduce
1. Set up an output to RSS file, to anywhere such as c:/test/file.rss. (Sorry my backslash doesnt work on this keyboard lol)
2. Close tvrename
3. Delete the folder c:/test
4. Open tvrename

## Context
Not required

## XML Files
Not required

Also, the error handling text needs to be changed. It says "if you want to report this problem, email tvrename@tvrename.com", but Steve doesn't need these reports emailed to him. The text should give a link to this github issues page where people can report bugs.

## Cause
I used to have tvrename old version, I used to have an old RSS file too which is like "when to watch list". But I deleted that rss folder ages ago as I had stopped using tvrename for a while, but when I installed new version of tvrename I got the error. I fixed it by creating the folder again and making a blank rss file. Then tvrename opened and I went into settings and removed the RSS output option. Then I deleted the rss folder again and the software would open normally. 

## Fix
If FSO file exists = false then dont bother using the rss file :-P

**Comment by JoeBiellik** [comment]
Thanks for the report, I can confirm I'm able to reproduce this, it crashes when trying to write to an non-existent directory. This applies to all exporters.

I think the best fix for this would be to just create the directory on demand? @MarkSummerville

**Comment by palentir** [comment]
No problem at all, I develop a little myself with VB, so I understand programming enough that I could share a couple different ways you could handle it.

* if file doesnt exist, silently uncheck the option. (silent approach)
* if file doesnt exist,  silently ignore the option for current session, in the hope that the file will be available next time tvrename is launched. (more practice)
* inform the user there was an error locating the file path. (annoying)
* ask the user to browse for the file. (annoying)
* next time the user opens options, perform another check for file exists and if it doesnt then dont let them close options until they've sorted out a valid file path. (would go nicely with the silent approach)

**Comment by MarkSummerville** [comment]
Yeah - I agree - just create the directory. We create the file when it doesn't exist, so creating the directory too is not too much of a problem. Need to make sure the error handling is improved in case there is no permission to create the directory or some other issue occurs; This should not bomb the whole app out.  Also we can use logging to explain what's going on. I am against any sort of user interaction being mandatory as we have to consider the hidden/unattended execution of TV Rename.

**Comment by palentir** [comment]
If you do it that way, you also need to include the code to create the parent folders then. What if the folder is 4 folders deep? "d:\folder\folder2\folder3\folder4\myfile.rss" and I delete the whole of d:\folder. Then you need to split the string based on "\", then loop each array element to create all the folders. If I deleted that folder, then I probably did it for a reason, maybe I moved it to another drive. So the software re-making the folder structure again is going to annoy me because of the confusion. It would save a lot of code just to turn off the feature and ignore the rss if the file doesnt exist. But you guys know what you're doing. Great to see this project active, such a good program <3
