### ISSUE TITLE
Export HTML document with Episode Details

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#28]
```
Do a "report" with various optional sections:
 - Files you have
 - Files you are missing
 - Episode guides
 - Links to thetvdb
 - file:// links to avi file
 - Episode thumbnails (downloaded to local, or direct link to thetvdb)

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:31

**Comment by MarkSummerville** [comment]
Tracked as:

http://ideas.theideawall.com/TVRename/Forum/TopicDetails/e345b5b9-4641-4521-9162-366ffc566486

Closing here

**Comment by MarkSummerville** [comment]
Closing this as the requirement is so old and not sure who the user would be
