### ISSUE TITLE
Javascript reading GitHub API

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#280]
Looking for a little assistance please!
As I've said before, I'm no coder...

I've cobbled some javascript together to read the API and get the path to the latest version of the .exe (don't ask how long it took!) for the download link on the web site. The hard bit works, I've got the download link in 'x' as the alert (x) proves but I can't get it into the document.write.

Ideas anyone?
```` 
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Test Page</title>
	</head>
	<body>
		<h1>Test Page</h1>
		<ul>
		<script> 
			var x = "unknown";
			fetch('https://api.github.com/repos/tv-rename/tvrename/releases/latest')
			.then( function( response ) {
				return response.text();
			}).then( function( body ) {
				x = JSON.parse( body ).assets[0].browser_download_url;
				alert ( x );
			})
			document.write( "<li><a title=\"Download the Latest Version from GitHub\" href=\""+ x +"\">Download</a></li>" );
		</script> 
		</ul>
	</body>
</html>

**Comment by JoeBiellik** [comment]
Using [``fetch()``](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is a bad idea as not all browsers support it, instead either use [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) or just use a library like jQuery.

You don't want to use ``document.write``, but instead, have a link already on the page which links to the releases overview page, so users with JS disabled still get a link. Then with JS you can just swap out the ``href`` once the API request is done.

**Comment by Andy-ABTec** [comment]
Thanks for the tips, I'll go play...

**Comment by Andy-ABTec** [comment]
Yep, worked like a charm (and your scripting made much more sense than the rubbish Google showed me). For now you can see the results at `https://andy-abtec.github.io/tvrename/`
It'll be in my next push to the main site.
Thanks again for the assist...

**Comment by JoeBiellik** [comment]
Looks good, but you are including 2 separate copies of jQuery on the page which can cause major issues. jQuery 1.7, which is very old, is included in ``head``, with the new one at the bottom of ``body``.

I've not tested it but it should be fine to remove the jQuery 1.7 line and move ``<script src="/tvrename/assets/js/main.js"></script>`` to under the new ``script`` at the bottom.

There are a few other JS issues (like ``//html5shiv.googlecode.com/svn/trunk/html5.js`` is dead) but I can make some revisions once you are done.

**Comment by Andy-ABTec** [comment]
I was just about to ask about this... didn't notice it was there, it's part of the Jekyll template Mark requested I use, I'll go and have another play...

**Comment by JoeBiellik** [comment]
Looks like the template is just very outdated then, jQuery 1.7 is from 2011 and Google Code shutdown around then too. I'm not very familiar with Jekyll but modifying the layout file to include newer libraries shouldn't break anything.

**Comment by Andy-ABTec** [comment]
Tried both locally. Replacing the jquery script in head with the new one and cutting it out totally  and moving as you suggested. Both result in the following:
![image](https://user-images.githubusercontent.com/5175695/34786445-1c01edfc-f62c-11e7-8f4c-bc5b195bdee1.png)
Definitely have no idea now... Can push it up to the test site and make you a collaborator if you have time to take a look...

**Comment by JoeBiellik** [comment]
The error is because main.js uses ``.load()`` which has been deprecated since 1.8 and removed in 3.0.

The fix is as easy as changing ``.load(...`` to ``.on('load', ...``. If you don't want to make JS changes you can swap the jQuery 3 include for 2:

```html
<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="/tvrename/assets/js/main.js"></script>
<script>...
```

**Comment by Andy-ABTec** [comment]
Think that fixed it thanks... I'll push it up to the test site shortly when I've tidied up.

Ended up having to change the jquery source back to 2.2.4 because the one "load" command in the whole shebang appears to be hosted by and pulled directly from github, I have no local copy to tweak.

Downgrading jquery was quite interesting as well, until I twigged that I needed to update the sha as well.

Still, got there eventually. Thanks again for the help!

Got to go out now, will update test in 3-4 hours

**Comment by Andy-ABTec** [comment]
Just pushed the updated version up to the test site...
It's much better now, the only error I'm seeing happens when the Home link is selected. I'm not at all sure but I think this is jquery again.
````
Exception
:
TypeError: Cannot read property 'top' of undefined at HTMLAnchorElement.<anonymous> (https://andy-abtec.github.io/tvrename/assets/js/main.js:23:52) at HTMLLIElement.dispatch (https://code.jquery.com/jquery-2.2.4.min.js:3:7537) at HTMLLIElement.r.handle (https://code.jquery.com/jquery-2.2.4.min.js:3:5620)
message
:
"Cannot read property 'top' of undefined"
stack
:
"TypeError: Cannot read property 'top' of undefined↵    at HTMLAnchorElement.<anonymous> (https://andy-abtec.github.io/tvrename/assets/js/main.js:23:52)↵    at HTMLLIElement.dispatch (https://code.jquery.com/jquery-2.2.4.min.js:3:7537)↵    at HTMLLIElement.r.handle (https://code.jquery.com/jquery-2.2.4.min.js:3:5620)"

**Comment by JoeBiellik** [comment]
The current site has a similar error.

``TypeError: Cannot read property 'top' of undefined``

In main.js there is code to smoothly animate the page scroll when you click on a sidebar link. The following gets the clicked link's vertical postion on the page:
```js
var position = $($(this).attr("href")).offset().top - 190;
```
``this`` being an ``<a>`` in ``nav ul li``, the href for the home link is ``index``.
The error is because ``index`` is not a valid element name, so it can't get the position.

This JS is terrible, are you against me writing a replacement or maybe switching theme?

**Comment by MarkSummerville** [comment]
At the time we could only select from about 8 themes and I chose the best one (looks wise IMHO). I noticed that you can now use any theme for your page though, so we have a larger set we could move to (one with better navigation and links would be good - Although I like the work @Andy-ABTec has done getting the theme useful for us (esp the menu bar)).

If we are able to make changes to the core templates with  PR to https://github.com/pages-themes/leap-day then that would be the best way of updating it centrally for all users to benefit from.

If anyone wants to recommend another theme then lets discuss the pro-cons here as well as the amount of work it would be to port it. I know @Andy-ABTec has worked very hard with the current theme and I wouldn't want throw it out just because of an outdated JQuery library.

**Comment by MarkSummerville** [comment]
Maybe fix these other issues while there. https://github.com/pages-themes/leap-day/issues/10

FWIW, I think they should be able to deal with these easily and it's quite harsh to just close down your concerns

**Comment by MarkSummerville** [comment]
Apologies 13 themes were supported: https://pages.github.com/themes/

However now many are: https://github.com/blog/2464-use-any-theme-with-github-pages 

Having said that I tried to use one of the non-13 ones and it didn't work so I switched back (albeit without much perseverance)

**Comment by MarkSummerville** [comment]
Sorry for the spam, but [minimal mistakes] (https://mmistakes.github.io/minimal-mistakes/collection-archive/) looks the most used. We could give it a try? @Andy-ABTec  thoughts?

**Comment by JoeBiellik** [comment]
To clarify, I'm more than happy to keep the current theme, I meant writing some replacement javascript. I'll open PRs upstream to replace the dead link and update jQuery, and see how they respond.

**Comment by Andy-ABTec** [comment]
I'm happy for anyone to do whatever is necessary, even change the theme if you wish. The hard work is done, worst case scenario now is "cut and paste".

From what reading I've done Jekyll seems to be aimed at blogging, and the GitHub themes appear to have little or no maintenance - witness Leap Day issues - https://github.com/pages-themes/leap-day/issues.

90% of the aggravation has been trying to work out how to do stuff, like apply specific style classes to blocks of text without access to divs and spans and without the markdown getting in the way. I spent hours fiddling with Chrome's "Inspect" tracing style inheritance and the like trying to get the "look". Prime example: the menu changes which were a nightmare, witness the css cludge that goes with them, would have been easier to start with a clean slate. 

As I've said, I'm no coder, before I took early retirement I was a Linux and Network Admin. I've got a fairly good working knowledge of html and css, and to a lesser extent javascript and php, (and designed hardware/wrote shed-loads of Fortran for the MoD years ago), but I'm happiest in a bash shell or a Cisco config or playing with hardware and Cat 6. So if @JoeBiellik is happy (and has the time) to fix the template then please go for it! (but if you do -please can you take a look at https://github.com/pages-themes/leap-day/issues/7, the fact that the template is broken and was just tagged "help wanted" does not seem an appropriate solution.)

_Apologies to any GitHub "staff", I have no wish to offend, but when I worked in Tech Support if it was broke you fixed it PDQ - I bet you would scream the place down if you lost your servers.)_

**Comment by Andy-ABTec** [comment]
I've updated my copy of default.html with Joe's html5shiv fix so it will be in my next pull, not that it makes a lot of difference, it's commented out? Do I need to uncomment it? Is there anything else I need to worry about?

**Comment by JoeBiellik** [comment]
The shiv is wrapped in a special comment that means it will only run in older versions of IE. This is intended. I have an open PR to update jQuery, we can see how that goes.

I think we can shut this when you are ready, I'll make relevant new issues for any updates.

**Comment by Andy-ABTec** [comment]
Right - I hadn't twigged that comments could be conditional... learn something new every day...

Thanks again for taking the time and helping!
