### ISSUE TITLE
Not sure if "Language" setting is being honoured properly when importing banners

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#285]
Hi guys, Just stumbled on this while rebuilding again...
The TV American Show "Leverage" is one of the older shows in my collection, when importing it I'm getting a Spanish Show Banner, have done a couple of forced refreshes and image updates with the same problem each time.

Checked on https://www.thetvdb.com/?tab=seriesbanners&id=82339. the banner I'm getting is the highest scoring one however it's correctly tagged Español. With my language set to English shouldn't I be getting the highest scoring english one, or is it a problem caused by the "ñ"?

**Comment by JoeBiellik** [comment]
AFAIK [we just check the score](https://github.com/TV-Rename/tvrename/blob/master/TVRename%23/TheTVDB/SeriesInfo.cs#L664-L675), not the language.

**Comment by Andy-ABTec** [comment]
Future enhancement then...  
Using Leverage - an English show -as an example there are twelve banners available, eleven are in English, one is in Spanish, they all have the correct language tags and of all twelve the Spanish one scores the highest.
I would guess from the date associated with the Spanish banner the show must have run in a spanish speaking country recently. 
As far as I can tell there is no way in TV Rename to choose the banner so wouldn't it make much more sense to download the highest scoring banner in the "Preferred Language" set in Options>Preferences>General otherwise what's the point of having the setting, I'm guessing the .nfo file already does this?

**Comment by MarkSummerville** [comment]
It already does all this. https://github.com/TV-Rename/tvrename/blob/master/TVRename%23/TheTVDB/SeriesInfo.cs#L620-L636 I suspect there is a little bug with banners not being removed or something similar

**Comment by MarkSummerville** [comment]
At source it is bad data from TheTVDB:

```
{
  \"data\": {
    \"id\": 82339,
    \"seriesName\": \"Leverage\",
    \"aliases\": [],
    \"banner\": \"text/82339-2.jpg\",
    \"seriesId\": \"75367\",
    \"status\": \"Ended\",
    \"firstAired\": \"2008-12-07\",
    \"network\": \"TNT (US)\",
    \"networkId\": \"\",
    \"runtime\": \"45\",
```
However we should be dealing with it and overriding with our own banner...

**Comment by MarkSummerville** [comment]
The code for the series banner assumes that TVDB has the correct banner and uses that as a priority. (in this case it is wrong - as shown above) .

For the season banner it looks at its collection of possible banners, finds the best in the correct language (if available), finds the best in any language and then is that fails uses the series banner.

Which one(s) are you seeing issues with? The series banner is down to TVDB data. How do the season ones look?

**Comment by Andy-ABTec** [comment]
The seasons all appear to be showing the show banner not the season banner, checking at thetvdb there is a banner for each season but they all appear to be tagged as german except season 5. I'll go and raise the the bad data issue with them. (wont be the first time!)
Out of interest what's the giveaway for bad data in the json? snippet above?

**Comment by MarkSummerville** [comment]
Fixed to use our banners first
