### ISSUE TITLE
V 2.3.1. crashing at the end of  the Media Library Check in a full scan

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#286]
Sorry chaps this one appears to be back again...

![image](https://user-images.githubusercontent.com/5175695/34914408-846f7022-f90a-11e7-9675-7faa37d2e14e.png)

Nothing in the log as you can see...

[TVRename.log](https://github.com/TV-Rename/tvrename/files/1629179/TVRename.log)

**Comment by MarkSummerville** [comment]
OK - Think I have found it. Looks like it'd happen whenever it does a full scan and tries to clean up the download directory.

Will have a fix in 2.3.2 which I'll put out soon
