### ISSUE TITLE
Fix bugs in Custom Search UI

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#289]
From #262 

* Make it easier to turn off the functionality by looking at the boolean flag to enable/disable rather than the url being null/not-null

**Comment by MarkSummerville** [comment]
@Andy-ABTec - Just realised the tags are case sensitive. May be the issue you were seeing. Will make them insensitive now.

**Comment by Andy-ABTec** [comment]
Cool - When you get a minute a quick example (something I can past in) for starters would be great, I'll figure out the rest from there...

**Comment by MarkSummerville** [comment]
https://www.google.com/search?q={showname}%20TV%20Show

**Comment by MarkSummerville** [comment]
It's the same format as the search engine strings

**Comment by Andy-ABTec** [comment]
OK I'll try that...

**Comment by Andy-ABTec** [comment]
CLANG! The penny drops...
I understand whats going on now - its a custom search on a per show basis, I hadn't twigged, 
Would be really cool if it had a Tags button like Search Engines that popped up a list populated with the show you started the edit on. but hey, at least I can make it work now!
