### ISSUE TITLE
Preferences overhaul / per-show options

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#29]
```
Maybe re-do preferences and per-show options so that you can set
system-wide defaults in the main preferences, then optionally set overrides
for each show.

Quite a few of the options would probably benefit from this.  e.g. language
preferences, ignoring of specials season.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:34

**Comment by MarkSummerville** [comment]
Maybe something to consider for v3 / v4 as we do an overhaul. I like the idea though

**Comment by JoeBiellik** [comment]
Yeah, I'd like to see it done this way, we have a lot of overhead when storing the same options for every show.
