### ISSUE TITLE
Progress window disk capacity display

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#291]
Tiny little thing in no way affecting functionality, but as you guys seem to be heavily into fixing bugs at the moment...  😃 

Take a look at the "Disk" in the Progress window

![image](https://user-images.githubusercontent.com/5175695/34981414-574164ac-fa9f-11e7-8413-befa795d4aa3.png)

Windows has a slightly different view

![image](https://user-images.githubusercontent.com/5175695/34981494-898cfc5a-fa9f-11e7-8c3a-6760dcf1fb52.png)

Get the same problem with UNC as well as Drive letter mappings (UNC is my preference).

Guessing this may be a hangover from the days when terabytes of storage were not commonplace in the home?

**Comment by Andy-ABTec** [comment]
Seems odd - how often are you checking it?

**Comment by MarkSummerville** [comment]
It's checked every 50ms. I think I'll split it so that the directory full indicator is checked less frequently

**Comment by Andy-ABTec** [comment]
Probably a good plan...
You could go as far as every time a new file copy starts or maybe once a second, This is disk we.re talking about, I don't think you're going to see a lot of change in 50ms

**Comment by Andy-ABTec** [comment]
Close - but not quite a cigar!

![image](https://user-images.githubusercontent.com/5175695/35932190-fa92f878-0c2e-11e8-9897-4a2a8ee79672.png)

**Comment by MarkSummerville** [comment]
Added a fix that improves it, I'm not 100% happy (as it would show 999.9 GB), but it's better than the current. Cheers

**Comment by Andy-ABTec** [comment]
In which case here's a solution you might like to try. I've been using for years (it's in JavaScript but I'm sure can can translate)...
It skews the cross over point so you get 0.99 GB rather than 990 MB and will always churn out 3 digits
```
    <script>
        var si = [" ","k","M","G","T","P"]                        // kilo, Mega, Giga etc...
        var bscale = 5;
        var disk = 3456324324789                                  // Free space on disk in bytes


        while ( Math.pow ( 2, bscale * 10 ) >= (disk / 0.9 )) {   // 2 to the power of (bscale*10)
            bscale -- ;                                           // range through the eng. units
        }
        var sdisk = (disk/(Math.pow(2,(bscale*10)))).toString();  // 2 to the power of (bscale*10)

        if (sdisk.charAt(3) == ".") {                            // lop off the decimal if it's the
            sdisk=sdisk.substring(0,3);                          // last character
        } else {
            sdisk=sdisk.substring(0,4);                          // else keep it
        }
        sdisk=sdisk+" "+si[bscale]+"B Free";                     // and add the SI unit

        alert ( sdisk );
    </script>
```

**Comment by MarkSummerville** [comment]
Looks good, I was holding off until v3 when @JoeBiellik has plans to introduce [this library](https://github.com/Humanizr/Humanizer#bytesize) which has all sorts of stuff to make our lives easier.
