### ISSUE TITLE
Docs update for V2.3.2

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#292]
Tweaked version of the website for V2.3.2 now available...

https://andy-abtec.github.io/tvrename/

Let me know what you think...

**Comment by Andy-ABTec** [comment]
Added an update for Add/Edit Search

**Comment by MarkSummerville** [comment]
HI @Andy-ABTec - sorry for the delay in getting back to you

Thank you so much  for your tireless work on the new website - it contains so much useful information now. I have some comments, but more observations really. Feel free to take them or leave them. The website if your domain, so please ignore if they don't fit with your vision or opinion!
 * Homepage should be a little 'punchier' - add a screenshot and maybe move some of the Conventions and stuff deeper in the site. It is our main advert for the system.
 * Much of the homepage is links that is now served by the yellow menu, so removing that can free up some space for the jazzyness
 * Maybe add a links or details page that links to all the pages on the site. It could replace the technical details in the main menu and the tech details would be linked from this new page
 * I'm not sure whether the advanced tabs on 'Add/Edit Show' should be in the userguide or under 'preferences' - most of the preferences are also available globally? I can't decide which I think is more logical.
 * 'Repairing corrupt data' should this move to 'Tools'?
 * Link somethere to the roadmap page: https://github.com/TV-Rename/tvrename/milestones?direction=asc&sort=due_date&state=open as it's quite a nice representation of what we're working on and when
 * Make the Github link a little neater - maybe just have the icon?
 * Specific for the 2.3.2 release
     * 'about' still talks about 2.3.1
     * The “Season search terms:” text box provides TV REname with a list of semicolon separated words the TV Rename will recognise as part of a season identifier when searching.
     * The “Season search terms:” text box provides TV Rename with a list of semicolon separated words that TV Rename will recognise as part of a season identifier when searching using folder monitor.
     * Maybe mention that the specials/seasons/season keywords are aimed at international users

Please don't see these as criticisms - just feedback from afar! 

Thanks again for your tireless work on the site - it looks great!

**Comment by Andy-ABTec** [comment]
Hi @MarkSummerville, Thanks for the feedback, and no worries about the delay, I know you've been busy...

I'm just about to push the 2.3.2 fixes to my repo so you can take a look and pull as you wish...
I think this is the safest way to play things for now, my local Windows / Notepad++ / Chrome / WHL / Ruby / Jekyll / Git workflow can get a little messy and updates everytime I save something, so I'll push up to Andy-ABTec when changes work as a "stand alone" block and you can take it from there.

Largely agree about the other stuff, but considering the original remit and what I had to start with (and fight against - thanks Jekyll!) I don't think things are looking too bad either!

My main restriction at the moment is the  menu system and trying to keep the important stuff accessible without having to hunt or drill down too far.

The menu entries grew out of what was there already, the guides and TV Rename's menus, though thinking about it, I can probably mege support and the trackers into one page with links and sub pages as necessary which would free up a couple of buttons for other stuff.

As I've said previously - the bulk of the work is done, moving stuff around is "just" cut-and-paste!

**Comment by Andy-ABTec** [comment]
@MarkSummerville, you might like to check out:

https://andy-abtec.github.io/tvrename/support

It's not live yet, but attached to the menu support link it does away with both the bug and feature trackers freeing up menu space for other stuff.

Additionally I'm looking ant merging index.md and about.md into index.md and "jazzing up" the page with some screen shots freeing up another menu slot in the process.

I'll also look at making the github link at the bottom of the page smaller, though I think we need to keep it, there won't be many many left if I implement the above.

So far so good?

**Comment by Andy-ABTec** [comment]
Said I'd be away for a while... Its been a slog, but check it out...

https://andy-abtec.github.io/tvrename/

Let me know what you think...

**Comment by Andy-ABTec** [comment]
Think this is about as good as its going to get for now,,,
