### ISSUE TITLE
.sub / .srt confusion...

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#294]
Sorry, this has been nagging me all day (so I just went and checked)...

In options preferences you talk about .sub files in a number of places, I think you mean .srt files...

.sub/.idx or VobSub is a graphic format used for subtitles and is AFAIAA the default subtitle format for DVD's, 

.srt is the text file in the SubRip format created from OCRing the graphics in the .sub file and combining it with the timings from the .idx file using something like dvdsubedit.

**Comment by JoeBiellik** [comment]
I think people still use a mix of both formats, srt is more common but sub/idx is still used, for example [Kodi even supports](http://kodi.wiki/view/subtitles#Compressed_subtitles) packed sub/idx files. SSA subtitles are common for non-English hardsubbed media but there are many more formats too.

Can we just change the phrasing from ``.sub`` to ``subtitles``?

**Comment by Andy-ABTec** [comment]
Don't think so...

In Options>Preferences Files & Folders there is an option to rename .sub files to .txt files.

Don't think that will work very well unless TV Rename does OCR on the quiet :smiley:.

Probably just needs the text tweaking on the form.

**Comment by Andy-ABTec** [comment]
Plus if you're going to copy the .sub file you need to take the .idx file with it otherwise the timings are unknown.

**Comment by JoeBiellik** [comment]
Yes, you are right its a strange option and behaviour, do we know why it was initially added? I think it just renames the .sub file rather than moving anything, so as long as software is looking for subtitles in a .txt file and the .idx file is there, it would work.

**Comment by MarkSummerville** [comment]
This is the only background I can find: http://old.tvrename.com/bbold/4/t-62.html

**Comment by MarkSummerville** [comment]
Also here: http://old.tvrename.com/bbold/3/t-136.html

**Comment by Andy-ABTec** [comment]
Done some digging...
It appears there was a .sub text format for the MicroDVD player back in 2000, really strange structure: -

> {0}{25}Hello world!

Where the numbers are frame count, though I must admit I've never seen it before today, I'm much more familiar with the generally accepted .srt:

>168
> 00:20:41,150 --> 00:20:45,109
> How did he do that?
> Made him an offer he couldn't refuse.

It seems to be much more common to see .sub in the context of SUB/IDX, the raw dvd format, which is what got me started down this rabbit hole in the first place!

Its a shame that google groups doesn't support surveys, otherwise I could ask what people use...

**Comment by Andy-ABTec** [comment]
Think I'll put this on the back burner for now, I'll ask in the group though I don't think |I'll get much response, maybe it's something to be revisited for V3?

**Comment by Andy-ABTec** [comment]
The survey is up and running in the forum, going to close this for now and visit later down the line, maybe V4...
