### ISSUE TITLE
Update Available misbehaving

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#299]
Sorry guys,
Getting this: -

![image](https://user-images.githubusercontent.com/5175695/35138310-dbd446ce-fce5-11e7-8139-5c22ff5a44d5.png)

Every time I start TV Rename.

"Cancel" gets rid of it but there is obviously something not quite right...
I'm already running 2.3.2 (did it the first time round) and have "saved" as well.
Occurs both in Beta and Production.

**Comment by MarkSummerville** [comment]
Damn - I'll have to take a look when I get home

**Comment by MarkSummerville** [comment]
Need a new line at https://github.com/TV-Rename/tvrename/blob/4436b782fce9069310162dc271a6446a31f39f6c/TVRename%23/TVRename/TVDoc.cs#L3198

`if (String.IsNullOrWhiteSpace( this.Prerelease) && String.IsNullOrWhiteSpace(otherUpdateVersion .Prerelease)) return 0;`

**Comment by MarkSummerville** [comment]
Have pulled the release and I'll reissue in a couple of hours when I can get that code change in and tested.

Sorry all

**Comment by Andy-ABTec** [comment]
No worries, just glad it was caught early on...

**Comment by Andy-ABTec** [comment]
No worries, just glad it was caught early on...

**Comment by JoeBiellik** [comment]
Very minor but you can see from the screenshot above that it shows an extra ``-`` after the version number if there isn't a prerelease string.

**Comment by MarkSummerville** [comment]
Yeah - fixed the `-` too.

**Comment by JoeBiellik** [comment]
Quick thing, the latest release filename is wrong on GH. Maybe because AppVeyor had built that tag before? Can we rename the file to avoid confusion?

**Comment by MarkSummerville** [comment]
Yeah - was just doing that. Done. Also have made some changes the compiler was complaining about deprecated methods.
