### ISSUE TITLE
Full cache of thetvdb shows+ids

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#3]
```
To speed up initial folder monitor scans, come with pre-loaded cache of
TheTVDB show names and IDs.

Database is available.  Is this a good idea, or does it lead to problems
with it getting out of date?
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 11:57

**Comment by MarkSummerville** [comment]
Not sure this is a good idea due to the size of the data. It seems like a massive change to fix a non-existent problem!
