### ISSUE TITLE
Mede8er Support

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#307]
As part of v3 I've been implementing updated media center files and am working on the Mede8er format.

[The Mede8er site](http://www.mede8er.com/) is pretty hard to navigate and I can't find anything concrete on its metadata requirements, just snippets. Does anyone have one of these devices?

I've found a few of their [guides specifically talk about using TV Rename](http://www.mede8er.org/Firmware_Final/TVrename/9May2013/TVrename%20Tutorial%2009%20May%202013.pdf) and they have a [forum section for it](http://www.mede8erforum.com/index.php/board,149.0.html). It's recently updated and looks like people are still using this project with the Mede8er devices.

I've seen a lot of conflicting information on image size requirements and if the "view.xml" files are even needed in the latest firmware, so if no one here has a device to test on I might reach out to them for exact clarification.

**Comment by JoeBiellik** [comment]
Thanks, I'll post here when we are ready to test.

**Comment by fotofrank** [comment]
I've got a Mede8er which is one of the first models: MED500x
It's possibilities are limited compared to the newer models and it's by far "idiot proof" when it comes to the use of images and their sizes.

I'll be more then happy to be of assistance.

**Comment by MarkSummerville** [comment]
@localhost61  Looking at the current version, it looks to be correct:

Looking at the code, it asks for an upper case View.xml one to be produced:
https://github.com/TV-Rename/tvrename/blob/52f45519c4c6091240476c331b32c071c9d28b93/TVRename/DownloadIdentifers/DownloadMede8erMetaData.cs#L57

Further, the XML looks to be the same format you are requesting:

https://github.com/TV-Rename/tvrename/blob/2120324935c8aec480ad7d55aaea54494700e37c/TVRename/ItemsAndActions/ActionMede8erViewXML.cs#L46-L57

**Comment by localhost61** [comment]
@MarkSummerville
I made a test again and you are perfectly right. It acts as stated on a fully populated TVshow were I removed all those View.xml files.

Then I apologize, the fault may be mine. Now I've batch-removed , all the (lower-case ) view.xml occurrences found on disc in order to be sure.

But I'm surprised, I don't remember to have seen previously a TVShow in ViewMode = Preview . I'll have to dig.

It may be a matter of taste, but:
- for base folder I would prefer ViewMode = Movie. In this mode the Episode thumbnails size is minimal and don't hide too much the fanart.jpg background. 
- for season folder I would prefer ViewMode = Music

Great tip this Github's feature of pointing lines of code with an URL.

**Comment by eentje** [comment]
personally i use the following view modes.

for the main folder with all the series: movie
for the serie folder itself : movie
for the season:  movie

for the same reason as localhost. i want to see as much of the fanart as posible. 

 note: i use thumbgen still to make folder, fanart series and season folder jpgs

**Comment by MarkSummerville** [comment]
@localhost61, @eentje If you can agree on changes to the modes with Zaarwan then I can easily make changes to the format

**Comment by MarkSummerville** [comment]
@eentje any reason you use thumbgen to make the the images. Is TV rename deficient in some way?

**Comment by MarkSummerville** [comment]
Just did a change - take a look and see if you can see any issues

**Comment by localhost61** [comment]
It seems OK for me, but I don't have a working VS 2015 for compiling. Waiting for your release.

**Comment by MarkSummerville** [comment]
Should all be in latest 2.5 RC - let me know how you get on
