### ISSUE TITLE
New Website Launch (not yet!)

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#308]
As you can probably tell, things are getting close.

Having thought about it I think the best time to go live with this is when V3 is launched.

The current site pretty much covers everything at the moment and I'm guessing the bigger new stuff is not going to appear outside beta before V3 so doing it this way means the new site can be tweaked for V3 without the need to update the existing stuff in the old site (unless it's error correction!)

Thoughts?

**Comment by MarkSummerville** [comment]
I think that's a good idea - we can keep working on the new one and update with the new UIs etc. Then release en-masse.  My only only would be the hassle of keeping them both up to date ( I suppose we can do minimal updates to the v2 Leap-day one)

**Comment by Andy-ABTec** [comment]
That was my thought, if your adding new features to version 2.x what are you holding back for 3?

**Comment by scott-mikus** [comment]
I assume when you say V3 you are talking 3.x not 2.3.x and if that is the case the website while still mostly current does need tweaking.

Such as the new full vs quick and recent search features which are not present in the user guide on the current website deployment.

I am totally up for doing anything required to update the website. Vetting, editing, keeping up with deployment of new stable releases and keep both the user, quick and technical guides.

While I agree waiting for a V3 release would be the best time for a full overhaul, I do feel interim updates are required with all of the recent code updates. But that’s just me. 😁

**Comment by MarkSummerville** [comment]
Hi Scott - Yes we are talking about v3. The proposal is to switch from the current style: http://www.tvrename.com/ to a more minimalist one with better support and better navigation options: https://tv-rename.github.io/Website/ (still much work to be done, but Andy is making good progress here:  http://test.ab-tec.co.uk/)

Thanks for the offer of help - great to have you involved

**Comment by Andy-ABTec** [comment]
HI @scott-mikus 
Thanks for the comments...
> Such as the new full vs quick and recent search features which are not present in the user guide on the current website deployment.
Take a look at http://www.tvrename.com/userguide#scan, I think you'll find mention of them.

I'll admit the site could be better, but if you saw what I was given to start with and the restrictions imposed by hosting as an old GitHub theme it's not that bad

**Comment by MarkSummerville** [comment]
Anything to cover off here? Just trying to close down whatever issues I can
