### ISSUE TITLE
Prevent JS Errors if inbuilt WebBrowser cannot support JQuery

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#309]
Resolve this: https://groups.google.com/forum/#!topic/tvrename/pQKzkj2Nx6c

Make website degrade gracefully if JQuery is not supported and show a blank screen. May be able to inspect registry and find IE version and then ignore loading the screen if old versions are encountered

**Comment by JoeBiellik** [comment]
There shouldn't be any need to show a blank screen for old IE, the JS script tags can be wrapped in IE conditional comments so no JS runs. The site with no JS should work fine just without some niceties.

**Comment by JoeBiellik** [comment]
If setting that hides the error and the site still works, then I would just do that - easier than trying to modify the template.

**Comment by MarkSummerville** [comment]
Actually looks like it's an issue with any version of IE

![image](https://user-images.githubusercontent.com/14905881/35554986-9d55d0ba-05d8-11e8-8984-9a9fd021941d.png)

I think `$('img').load(sectionHeight);` should be changed. To `$('img').on("load",sectionHeight);` ?

**Comment by Andy-ABTec** [comment]
Not sure why this is happening... 
_Leap day's main.js contains_
```
$(function() {
  $("section h1, section h2").each(function(){
    $("nav ul").append("<li class='tag-" + this.nodeName.toLowerCase() + "'><a href='#" + $(this).text().toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g,'') + "'>" + $(this).text() + "</a></li>");
    $(this).attr("id",$(this).text().toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g,''));
    $("nav ul li:first-child a").parent().addClass("active");
  });

  $("nav ul li").on("click", "a", function(event) {
    var position = $($(this).attr("href")).offset().top - 190;
    $("html, body").animate({scrollTop: position}, 400);
    $("nav ul li a").parent().removeClass("active");
    $(this).parent().addClass("active");
    event.preventDefault();
  });

  sectionHeight();

  $('img').on('load', sectionHeight);
});
```
And `$('img').on('load'` looks ok to me unless it's the quotes - on click further up the page uses double quotes?

**Comment by MarkSummerville** [comment]
Hmm - that's not what's being served by http://www.tvrename.com/assets/js/main.js so not a caching issue

**Comment by Andy-ABTec** [comment]
Ok, it looks like http://www.tvrename.com/assets/js/main.js isn't being passed through from https://pages-themes.github.io/leap-day/assets/js/main.js

 I'll drop a corrected version on our website as an override later

**Comment by MarkSummerville** [comment]
Seems like this had unintended side effects. Explore and Watch no longer worked. Reverting.
