### ISSUE TITLE
Thoughts for V3...

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#311]
Can't remember if I've bought any of this up before but with Feb 28th not far away now...

Having been "close to the coalface" for the last several weeks testing stuff while writing the docs some oddities with the menu system content leap out - these are only suggestions!

**Help Menu**
* "Statistics" is a tool, should be in "Tools" menu?
* "Bug Report" needs its output zipping or the whole thing dropping, the last one I produced was over 12300 lines of text!
* Buy me a drink? - has anyone actually done this?
* "new Version" or "New Version"?

**Beta Menu**
* Not seeing any performance issues with "Actor Grid" ( 70 Shows, 2500 episodes, 25Mb internet)  maybe it should go back to "Tools" where it belongs or is my collection not big enough to show the problem?

**Tools Menu**
* Don't think "Folder Monitor" is a "Tool" it feels more like an option, should live next to "Search Folders" as "Monitor Folders" in Options>Preferences?

Just my two-penneth...

**Comment by JoeBiellik** [comment]
Not sure where the deadline came from but it seems very unrealistic to be honest.

In my v3 branch, I have changed the bug report code to send the user to create a new GH issue but we do need to work on sending less data.

The actor grid takes 5+ mins for me with over 500 shows, blocks the UI and isn't multithreaded. It needs to be completely rewritten or removed in v3 IMO.

I'm working on a much more integrated "Bulk Add Shows" to replace the "Folder Monitor".

**Comment by Andy-ABTec** [comment]
Hi Joe,
The milestone came from here:
https://github.com/TV-Rename/tvrename/milestone/2

No panic, everything's good, I just want to put pen to paper so to speak - staring at /using stuff so much lately silly things like screen and menu layouts start to annoy! 

I'm actually in the process of installing Visual Studio 2017 Community at the moment so I can hopefully get a better look at what's in the pipeline...

**Comment by JoeBiellik** [comment]
Yeah, I'm aware it's on the milestone, just not sure how it was decided!

While my v3 branch is getting close to having all the basic features it's going to take more time to port over all existing functionality. After that, there needs to be a lot of discussion about which of my changes are worth keeping and moving them over to a proper v3. Ideally, we would then write unit tests and start releasing betas - with this many major changes I would expect a number of regression bugs so we want to allow plenty of time for testing.

**Comment by Andy-ABTec** [comment]
**_I have absolutely no idea how it was arrived at either..._**

I totally second your testing-regression workflow anything I can do to help just holler! - Takes me back to the days when I had to work for a living - Sorry! :sunglasses:

**Comment by JoeBiellik** [comment]
You can take a look at what I just pushed to the v3 branch if you want - rudimentary scanning should work. I'll start working on the ability to override episode numbers, split, merge etc. Testing that when its done would be appreciated.

**Comment by Andy-ABTec** [comment]
Thanks, I'll have a play once I've finish setting up Visual Studio etc, but for now I'm looking at a web navigation issue...

**Comment by Andy-ABTec** [comment]
OK - So far so good, I just scanned my media library... 8)

**Comment by JoeBiellik** [comment]
I'd be fairly careful with running it against your real library, I can't completely sure it won't overwrite something by mistake.

**Comment by Andy-ABTec** [comment]
Its OK, I'll test it anyway and let you know if I get any problems.

 I have 1 x Live and 2 X Backup NAS (Ebay is my friend) and I've turned off the overnight syncing - the Rsync over VPN out to Spain was playing up anyway and I need to figure out which of my nephews broke the spanish end + an offline backup (don't you just love 2TB USB drives)...

Thanks for the warning though... 😎

**Comment by MarkSummerville** [comment]
Dates are plucked out of thin air by me. Non intended to put pressure on people - just an indicative idea of what I'm thinking. Plumbed for a 1 march date as it seemed @JoeBiellik rate of progress would have it refactored pretty quickly. I have pushed them back. The last thing I want is for this to feel like a real job with deadlines/targets etc!

**Comment by Andy-ABTec** [comment]
In which case I must stop doing 8 hours a day...

**Comment by JoeBiellik** [comment]
@Andy-ABTec I think most of your original points are fixed in v3 now.

Stats is moved to tools.
Bug reporter needs more work and is now only shown if the program crashes. Do we need it in the menu?
"Folder Monitor" is now "Bulk Add Shows" under the file menu.
Actor Grid and update check aren't implemented yet.

**Comment by Andy-ABTec** [comment]
Thanks Joe. Just out of interest what's the problem with the actor grid? For me the attached loads virtually instantaneously (about 0.5s) 

![actor grid](https://user-images.githubusercontent.com/5175695/35995941-dbb10790-0d0c-11e8-901e-ee57fbedaaed.png)

Does it pre-load or build on the fly?

**Comment by Andy-ABTec** [comment]
Just tried the Bulk Add Shows in V3 - it flys!

**Comment by JoeBiellik** [comment]
I've not looked at the actor grid code in depth but it's just very slow when you have a lot of shows. Ticking "Include Guest Stars" seems to make it hang forever too.
I'm sure it could be sped up but I just question its value - with a lot of shows its almost impossible to browse around it and make matches as you have to scroll so much. Maybe if it had some kind of filtering and more export options it would be more useful to me - how do you use it?

**Comment by JoeBiellik** [comment]
Its still loading the grid on my 700 show library:
![image](https://user-images.githubusercontent.com/43646/35998065-75abcc8a-0d13-11e8-8db3-bff586abe8ad.png)
Thats 5GB of RAM usage and maxing a 4.8GHz core...

**Comment by Andy-ABTec** [comment]
Most use I get from it  is "What else in my library was that actor in", tracking actors in crossover episodes which DC Comics seem particularly fond of and "who was that bloke in such and such". Not a lot of use I know, but great for proving my smart-arse brother-in-law wrong!

**Comment by JoeBiellik** [comment]
Thanks for this info - I've started porting the grid to v3 to see if the bad performance is down to the grid control or how we are using it.

**Comment by Andy-ABTec** [comment]
Ont of interest does it pull stuff on the fly?

**Comment by JoeBiellik** [comment]
If you mean does the actor grid download anything - no.

**Comment by Andy-ABTec** [comment]
Well, that blows that theory out the water...

**Comment by MarkSummerville** [comment]
It may be because the control uses a class called DFC (Directory Files Cache) that caches calls to the filesystem? If you have run a full scan first then the subsequent actors grid *should* be quicker. It's not functionality I use though, so I don't tend to look at it.

I've has some good quick wins improving 'Show Summary' and "Bulk Add Shows' with resharper's performance monitoring

**Comment by MarkSummerville** [comment]
Takes about 4 secs on my system - resharper says that is mainly down to UI calls and is processor bound

**Comment by MarkSummerville** [comment]
![image](https://user-images.githubusercontent.com/14905881/36070862-fa9356fc-0f3e-11e8-9877-80d2dbd01bed.png)


Resharper results when you include guest stars

**Comment by Andy-ABTec** [comment]
Just out of interest how many shows/episodes?

**Comment by MarkSummerville** [comment]
358/16,740

**Comment by JoeBiellik** [comment]
![image](https://user-images.githubusercontent.com/43646/36074886-55d8b22e-0f3e-11e8-8952-0306a531e98d.png)

I'm looking at 11 mins for guest stars to render, RAM usage is about 3GB when not debugging but is still very excessive.

**Comment by Andy-ABTec** [comment]
ok, so I have only 73 shows / 2600 episodes on my poor old intel core 2 duo 2 x 2.2G and my build of the table including guests is around 1-2s, the only other thing I can think of that mayy affect the timing is that my disk is an SSD.

**Comment by JoeBiellik** [comment]
Using [Resharper's dotTrace profiler](https://www.jetbrains.com/profiler/).

I'm running off a very fast NVMe SSD but AFAIK the actor grid is only working with objects is memory, disk IO shouldn't be a factor.

Pretty sure the performance issues are coming from SourceGrid, it seems like adding one extra row/col doubles the processing time or something is being called recursively for each cell.

**Comment by Andy-ABTec** [comment]
Think this is all pretty much irrelevant now...
