### ISSUE TITLE
Rebrand 'Folder Monitor' to be 'Series Finder'?

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#315]
All,

I find 'Folder Monitor' to be a misnomer, there is no 'monitoring' going on as far as I know. To me folder monitor should refer to monitoring the download folder for new additions rather than a periodic search of a library for new shows.

thoughts?

**Comment by Andy-ABTec** [comment]
Why not set it up the same way as "Search Folders" in Options>Preferences and call it "Library Folders" after all that's what they are...

**Comment by JoeBiellik** [comment]
I personally think the ``Folder Monitor`` should be renamed ``Bulk Add Shows`` as its just a multiple version of the ``Add Show`` dialog. ``Library Folders`` makes me think its already part of my library and ``Series Finder`` brings a new keyword in which complicates it.

**Comment by Andy-ABTec** [comment]
Happy to go with @JoeBiellik's suggestion, It "does what is says on the tin" and that way it becomes an occasional use tool

**Comment by MarkSummerville** [comment]
Updated external view. Internal code refactor will have to wait
