### ISSUE TITLE
V3 branch oddity?

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#317]
Hi @JoeBiellik,

Not sure if this is a bug, but when I opened "Options>Preferences>µTorrent/NZB" for the first time I noted that TV Rename had found the µTorrent "resume.dat" file but not the application which had a blank path.

The Browse works as it should and I can add the path, but it just seemed odd that with µTorrent in its default location TV rename could "find" one file but not the other?

**Comment by JoeBiellik** [comment]
I've not added any form of torrent support to v3 so I'm not sure what you are looking at. To clarify if you have the v3 branch, you want to be working with the "TVRename.Windows" project not "TVRename#".

**Comment by Andy-ABTec** [comment]
Right, I'll get there in the end - now looking at V3 Beta1

![image](https://user-images.githubusercontent.com/5175695/35813788-68c65fdc-0a8c-11e8-9a9d-65c10796f4f9.png)

**Comment by Andy-ABTec** [comment]
Guys, dont know whats going on here - still finding my feet... I "fetched" a copy of V3 as @JoeBiellik sug
suggested...

I can build TVRename# without a problem but it doesn't appear to be Joe's code.

If I build TVRename.Windows I get an exception: -

![image](https://user-images.githubusercontent.com/5175695/35826425-9ec5f34e-0ab0-11e8-8530-53df370b0c74.png)

Get the following in the code:

![image](https://user-images.githubusercontent.com/5175695/35826533-ea0a8e5a-0ab0-11e8-9937-34b1d451999b.png)

What have I broken?

**Comment by JoeBiellik** [comment]
Try deleting the JSON settings files in appdata, does that fix it?

**Comment by Andy-ABTec** [comment]
Yes it does - thanks...

Don't know if it helps, but if I add a tv show and save exit and restart I get the same problem again.If I clear down, start the app, add the same show and exit without saving I don't get the problem. 

Would it help if I zip up app data both with and without the issue so you can compare?

**Comment by JoeBiellik** [comment]
No, I'm not concerned with that yet, lots is currently broken as I'm focusing on key functionality at the moment.

**Comment by Andy-ABTec** [comment]
No worries, holler if you want me to try anything for you...

**Comment by JoeBiellik** [comment]
Closing as you have it running.
