### ISSUE TITLE
2.33 RC1 Auto Upgrade WORKS!

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#321]
Just to let you know, with "Beta" turned on I got prompted to upgrade...

**Comment by MarkSummerville** [comment]
Great news - works here too.

**Comment by MarkSummerville** [comment]
Hi @Andy-ABTec Can you have a play with the 'Bulk Add Shows' function please? I've made it faster (much faster in my case), but want to check that it works for others as well. Cheers
