### ISSUE TITLE
New options on the Search Folders Tab

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#322]
Please can someone confirm the difference between:

**Scheduled Scan** and **Monitor Folders** - there's no mention of it in the release notes...

Obviously Scheduled scan runs against the clock every x hours, but what triggers Monitor Folders to detect a change?

(just staying on top of the docs)

Ta!

**Comment by Andy-ABTec** [comment]
Thinking about it doesn't Monitor Folders make Scheduled Scan redundant - theoretically Monitor Folders would pick up and process every time a new file is found, Scheduled Scan wouldn't get a look in?

**Comment by JoeBiellik** [comment]
@MarkSummerville would know the details but I think you are correct. The OS alerts TV Rename as soon as a file in a monitored search folder changes.

**Comment by MarkSummerville** [comment]
There are some scenarios that the OS alert does not fire. Sometime on networked drives and there were sole old reports about mono not firing them, so the timer scans are a backup for those.

Further there are cases that even with the current approach the system doesn't capture it all:
 * File is dropped
 * TVR scans and does actions
 * While actions are being processed another file is dropped
 * TVR fires up, but doesn't run another scan as it is already mid action.
Again in this case the current system fails

In my mind it is about how the user wants to do it - they get to choose. (at startup, periodic, on file drop)

Sorry my mistake I didn't add them to the release notes. Will update now.

**Comment by MarkSummerville** [comment]
Further -FYI, I wanted these in to bolster the 'automatic' part of the new website

**Comment by Andy-ABTec** [comment]
Cool - just wanted clarification, so it's a Windows file drop that's used to trigger when Monitor Folders is ticked...

**Comment by MarkSummerville** [comment]
If 'Monitor Folders' is checked, any modification addition or removal of a file on the filesystem will trigger the scan (of specified type) to run and the actions to be completed.

Not sure I understand your question, but taking it literally, but 'Monitor Folders for changes' is ticked by clicking on it
