### ISSUE TITLE
Version 2.3.2 does not recognize my folders

### ISSUE THREAD

**Issue by RedX2501** [TV-Rename/tvrename#329]
I just upgraded from 2.2.1 to 2.3.2.  Win 10.

2.2.1 created and recognized all my TV show folders without any problems. Now with 2.3.2 it asks to create all the Season folders or ignore them. Clicking "Create" re-opens the dialog for the same show/season.

I have mapped a network drive to my Z: folder where all my shows are.

The relevant log entry:

```
2018-02-10 23:01:52|INFO| System.IO.DirectoryNotFoundException: (3) Das System kann den angegebenen Pfad nicht finden: [\\?\Z:\13 Reasons Why]
   bei Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   bei Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   bei TVRename.TVDoc.CheckAllFoldersExist(List`1 showlist) System.IO.DirectoryNotFoundException: (3) Das System kann den angegebenen Pfad nicht finden: [\\?\Z:\13 Reasons Why]
   bei Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   bei Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   bei TVRename.TVDoc.CheckAllFoldersExist(List`1 showlist)
```

but as you can see from the screenshot the folder exists:

![tvrenameproblem](https://user-images.githubusercontent.com/929932/36067172-1f8eb1e0-0eb8-11e8-8a8c-f99c6184645b.png)

**Comment by MarkSummerville** [comment]
Hi

Does it find it when you use a fuly specified UNC filename? i.e. //server/Serien/13 Reasons Why?

Thanks

**Comment by RedX2501** [comment]
Adding it as `\\server\Serien\13 Reasons Why` does work.

But I don't feel like that is a clean solution.

**Comment by RedX2501** [comment]
Ok, I have no idea what was going on but it started working.

I'll reopen if anything changes.

**Comment by MarkSummerville** [comment]
OK - thanks. I don't think that using the UNC path is a fix either. I just wanted to check as that hay help us work out what the problem is. 

Let me know if you are finding problems again

**Comment by RedX2501** [comment]
After much delay I did try it again now with version 3.2.5 and I still have the problem.

What is odd is that when I click on the browse button to select the folders I don't see my network mapped drives in PC overview. They exist and I can access them via the explorer.
Before I upgraded this morning I tried with a 2.2.4 version and it worked.

**Comment by RedX2501** [comment]
Here you can see the dialog for the Library folders. It's the same contents as for the Browse button in the scan dialog for missing folder.

![image](https://user-images.githubusercontent.com/929932/84587451-be691b80-ae1f-11ea-9f06-db0d98ce4570.png)

**Comment by SirSparkles** [comment]
We see this issue fairly often. It is permission related.

If you run TVR from the installer then it does not have permission to see the network drives.

Close and reopen. Then it will be running in your account (which does have permission to see these drives)

**Comment by SirSparkles** [comment]
Hi @RedX2501 did a restart fix the issue?

**Comment by SirSparkles** [comment]
Assuming that it fixed the issue. Please feel free to reopen if it is still a problem

**Comment by RedX2501** [comment]
I got to test it today. It really seems to fix the problem.

This leads to the next question. Is the installer running TvRename in elevated mode? That is not nice.
