### ISSUE TITLE
Show Aliases 

### ISSUE THREAD

**Issue by MatLomax** [TV-Rename/tvrename#339]
# Expected Behaviour

When scanning a show, e.g. 'House of Cards (US)', with Show Aliases, the episode files in the scan folder should be identified and renamed.

# Current Behaviour

TVRename does not identify source files matching the show aliases and marks them as missing episodes.

Configured scan folder contains the following files:
![aliases-1](https://user-images.githubusercontent.com/1562860/36379236-b5fe075c-1575-11e8-8eed-6748ac6e6a7e.png)

Show has been configured with the following Show Aliases (multiple to cover all bases I could think of):
![aliases-2](https://user-images.githubusercontent.com/1562860/36379242-bd2268ac-1575-11e8-827b-455ad3613e8b.png)

Scan results still show episodes as missing:
![aliases-3](https://user-images.githubusercontent.com/1562860/36379243-bf0e9618-1575-11e8-919d-a3f953d45176.png)

If I manually rename all the source files to replace '2013' with 'US' to match the show name, then it works as expected.

Either this is a bug with Show Aliases, or I am seriously misunderstanding the point of having aliases.

**Comment by MatLomax** [comment]
Digging through the code a bit, it looks like the `Helpers.SimplifyName` function may be responsible, as it looks for `\b` Regex word boundaries, which are not present in the example above.

**Comment by MarkSummerville** [comment]
Can you send the filename processors screen? I suspect you have a processor
that is matching 2013 to be s20e13. Try opening the file name processors
screen and pointing it at the y:/unsorted folder. That should tell us what
it is looking at.

Cheers

**Comment by MatLomax** [comment]
I'm using all the default filename processors (there's one more below the scrolled position, but it's unrelated):

![aliases-4](https://user-images.githubusercontent.com/1562860/36380128-11b887b8-1579-11e8-98fc-797672447518.png)

**Comment by MatLomax** [comment]
Digging around in the code a bit, the [`Helpers.SimplifyAndCheckFilename`](https://github.com/TV-Rename/tvrename/blob/a3b98932b60efd61434cff84c7b53082f31cf159/TVRename%23/Utility/Helpers.cs#L342) function looks like it could be responsible, as it's using `\b` Regex word boundaries, which would not be present in the example above.

**Comment by MatLomax** [comment]
I put a breakpoint on [this line](https://github.com/TV-Rename/tvrename/blob/8b987dc55b915b57bbc1fa246b66d92d58c6d272/TVRename%23/Finders/FileFinder.cs#L255) and `seasF` and `epF` are indeed set to 2 and 13 respectively.

**Comment by MatLomax** [comment]
Unticking the second ticked processor ('Show - 323 - Foo') in the last screenshot fixed it.

**Comment by MarkSummerville** [comment]
Hey - just looking at this now: What about adding `House Of Cards` as an alias?

**Comment by MarkSummerville** [comment]
Ah - good.

**Comment by MatLomax** [comment]
Unless you count unexpected default behaviour as a bug, you can close this.

**Comment by MarkSummerville** [comment]
I’ll turn offf that processor by default. Thanks
