### ISSUE TITLE
Double Episode Name Merging

### ISSUE THREAD

**Issue by MatLomax** [TV-Rename/tvrename#340]
This is very much an edge case, but I'm hoping there's an easy fix.

# Expected Behaviour

Merging the double episode named:
`Mr. Robot - S02E01-E02 - eps2.0_unm4sk-pt1.tc + eps2.0_unm4sk-pt2.tc`
should result in:
`Mr. Robot - S02E01-E02 - eps2.0_unm4sk.tc`

# Current Behaviour

It tries to rename it to:
`Mr. Robot - S02E01-E02 - eps2.0_unm4sk-pt.tc` 
(extra `-pt` at the end)

**Comment by JoeBiellik** [comment]
I'm not sure if we want to be trying to automatically handle cases where the "part" isn't at the end of the filename, I think this is an example of one to leave alone and let the user handle the naming.

**Comment by MatLomax** [comment]
It is a weird edge case, so it's fair enough that it won't be accounted for in the code.

I just added a custom name to the merge rule and it renames it as expected, so I'm closing this issue.

**Comment by JoeBiellik** [comment]
I think this is still an issue as the default behaviour which just strips the number seems unsafe. @MarkSummerville I think we want to only be handling a number if it ends in (2) or (Part 2) or - Part 2 etc, what do you think?

**Comment by MarkSummerville** [comment]
It finds the common root and assesses that, so two episodes that are called (for example) `The Joe Biellik Story (Part One)` and `The Joe Biellik Story (Part Two)` are combined to '`The Joe Biellik Story`. It seems to work OK for most use cases I've thrown at it. We then check that the `root` is long enough to be useful >3 characters and >40% of the size of the source filenames. I also check that the source episode names are the same length.

Completely agree we could:
* regex for certain common suffixes styles
* remove them first
* then have a simpler assessment logic (similar to the current outlined above)

I'm inclined to see how it goes and only modify if we get further issues raised

**Comment by JoeBiellik** [comment]
Okay, sounds good, that should cover 99% of them.
