### ISSUE TITLE
Episode Files Not Found

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#341]
# Failure Information

Default episode regex misses [24: Legacy](https://www.thetvdb.com/?tab=series&id=311787&lid=7) video files.

## Steps to Reproduce

Wipe all settings, add 24: Legacy with default options, scan and the episodes will show as missing even if you have correctly named files on disk.

## Context

I've not spent any time investigating but it seems none of the filename processors can deal with
``24- Legacy - S01E01 - 12:00 Noon - 1:00 P.M..avi``
I remember [I saw some code](https://github.com/TV-Rename/tvrename/blob/a3b98932b60efd61434cff84c7b53082f31cf159/TVRename%23/TVRename/TVDoc.cs#L2781) that I think is meant to deal with this kind of naming which might need extending.

**Comment by MarkSummerville** [comment]
HI @MatLomax I was thinking just that when I was going through the code looking at your other issue. For me it makes more sense to have the topmost RegEx to be the highest priority.

Alternatively it should search through all and then look at which series/episode combinations it can match. If ANY of those combinations match then use the file. How does that sound?

I think there has been some hesitation about changing this area of code as it has not really been changed for years

**Comment by MarkSummerville** [comment]
@JoeBiellik the quick solution to your issue is to disable the processor called `like '13 - Showname - 2 - Episode Title.avi'` this way the main RegEx at the top will match and it'll process it OK

**Comment by MarkSummerville** [comment]
From looking at the code, it appears that if multiple processors match the filename. It is designed to use the one that has the left-most match.

I think that we can improve it by either;

a) having a formal priority order to the RegExs is a better way to go, To do this we need to;
 * Provide move up and down buttons on the UI
 * Make sure we store the priority and respect it in the save/load processes as well as the Processing Order

b) using all processors and seeing whether any of the series/episode ids are needed. This way `24- Legacy - S01E01 - 12-00 Noon - 1-00 P.M.` would return  `S01E24`,  `S00E24` and   `S01E01`.  Then the calling code can decide if any of those options is useful

Anyone got any views?

**Comment by JoeBiellik** [comment]
My vote is A, it's how I originally thought it worked. B has the potential to give false positives and seems more complex to implement.

**Comment by fotofrank** [comment]
A new option to Re-order the RegEx would be MOST welcome!

**Comment by fotofrank** [comment]
`^(?:\d+)- (?:[a-z]+) - S(?<s>[0-9]{1,})E(?<e>[0-9]{1,}) - .*\.(?:[a-zA-Z0-9]{2,4})$`
works for
`24- Legacy - S01E01 - 12:00 Noon - 1:00 P.M..avi`
