### ISSUE TITLE
CheckForUpdates fails

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#345]
GitHub [updated](https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/) security libraries that can be used and we must have fallen foul:

```
2018-02-24 20:59:54|ERROR| Failed to contact GitHub to identify new releases System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TVRename.TVDoc.CheckForUpdates() 
```

**Comment by JoeBiellik** [comment]
Should just be [``ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12``](https://stackoverflow.com/questions/30491716/how-to-specify-ssl-protocol-to-use-for-webclient-class) I think.

**Comment by MarkSummerville** [comment]
Yeah - that's the change I made. Irony was that VS couldn't connect to commit the change.  I had to upgrade to target 4.6 framework too

**Comment by JoeBiellik** [comment]
Worth noting that with the change to .NET 4.6, Win XP support is dropped - IMHO this is a breaking change and should bump the version to 2.4.

**Comment by MarkSummerville** [comment]
Fair enough - will do

**Comment by JoeBiellik** [comment]
Is 4.6 needed? From what I've seen online, 4.5 added ``SecurityProtocolType.Tls12`` and would still support XP.

**Comment by MarkSummerville** [comment]
No - in that case I'll flip to 4.5.

I read from [here](https://blogs.msdn.microsoft.com/dotnet/p/dotnet45xp/)
that 4.5 does not support XP

**Comment by JoeBiellik** [comment]
Sorry you are correct, XP only supports 4.0 - leave it at 4.6.
