### ISSUE TITLE
Remove 255 filename checks in code

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#347]
Feel like we can remove the following checks in the code:
https://github.com/TV-Rename/tvrename/blob/b587b529875afab3ae5ca1dcce52540d15a17827/TVRename%23/Forms/CustomNameDesigner.cs#L91

https://github.com/TV-Rename/tvrename/blob/b587b529875afab3ae5ca1dcce52540d15a17827/TVRename%23/TVRename/TVDoc.cs#L3029

As AlphaFS will handle longer paths/filenames now

@mhurwood thoughts?

**Comment by JoeBiellik** [comment]
I think its safe to remove the checks, I actually have a single episode file that is over 255 chars which I have to ignore and name manually.
