### ISSUE TITLE
Tidy up TimeZone Code

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#348]
Now that we target .NET v4 Framework then we should follow this advice and use `System.Core.TimeZoneInfo`:
https://github.com/TV-Rename/tvrename/blob/deb30f806c62c9109ce17535e356470f30610b59/TVRename%23/Utility/Timezone.cs#L15

**Comment by MarkSummerville** [comment]
@JoeBiellik do you think this this a v3 thing?

**Comment by JoeBiellik** [comment]
v3 stores all dates as UTC and uses the native types, but it's your call if you want to do this in v2 - depends on how much time you want to spend on v2.
