### ISSUE TITLE
Ignore Mac Temp Files on Share

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#356]
http://old.tvrename.com/bbold/3/t-2960.html

Hello all,

I know this situation is not as likely as some, yet hardly unique and easily repeatable, so I decided to post it as a 'bug', although TV Rename is acting as programmed, I'm certain it's unintended.

Here's the scoop and how to test/fix it.

1. Get yourself a network share, NAS or otherwise.
2. Download the files and/or access them with a Mac.
3. Since the NAS/Share isn't mac format, it will create a second file with metadata for any file it sees, IE, say for instance you have:
Chuck-S01E01.avi
It will create a metadata file called
-.Chuck-S01E01.avi
This will be a hidden file and ~4kb.
... The 'problem' here is that TV Rename sees this file first, so therefore will think that's the real file and rename/move it accordingly. There is no way that I can see to turn off the 'feature' on a mac (you can turn off the creation of other annoying 'features' like the .DS_STORE and SEARCHES folders, but not this.

The fix seems easy enough to do, either ignore files starting with the double-double (-.), or even better to be safe to other unintended consequences ignore those files when the filesize is <10kb... That said, I don't have any development tools hanging around anymore to try this with. Now, granted, this situation is not mainstream, but I will say that TvShows2 for Mac is GREAT for easily tagging and downloading your shows with Transmission, but nothing beats TV Rename for proper filing and categorizing them! If someone feels like this would be a good 5 minute enhancement, I'd be eternally grateful!

Thanks,

Diamond187

**Comment by JoeBiellik** [comment]
I may be mistaken but I don't believe modern versions of MacOS do this anymore.

**Comment by MarkSummerville** [comment]
Line 250 of FileFinder should add
```
     if (dce.LowerName.StartsWith("-.") && ((dce.Length / (1024)) < 10))
                    {
                        logger.Info($"Ignoring {dce.TheFile.FullName} as it looks like a Mac Temp File");
                        continue;
                    };
```
