### ISSUE TITLE
Use meta-info from video files as elements in rename-to filename

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#36]
```
Use things like frame size, frame rate, codec, bitrate, file size.  Either
put those into the filename, or deduce things like "HD" quality tags from them.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:42

**Comment by MarkSummerville** [comment]
Tracked as a feature request in http://ideas.theideawall.com/TVRename/Forum/TopicDetails/f7777200-ffd2-442c-b269-73831d3b5c3b?fb=0

Closing for now - can be reopened if we decide to work on it
