### ISSUE TITLE
DVD Order - strange behaviour

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#360]
Just doing some testing and stumbled on this...
Have all 7 Seasons of Burn Notice and the Sam Axe Special on DVD all nicely ripped and sitting in my library.. a normal aired order is fine and shows no issues, but if I turn on DVD order I get:

![image](https://user-images.githubusercontent.com/5175695/37450044-68fdd09c-2824-11e8-9c43-6c8f106280e6.png)

Its something that changed between RC 1 and RC2 (RC 1 was fine). Comparing thetvdb data I cant spot any issues...

Nothing in the log except an Info line saying Burn Notice was modified.

As ever, happy to poke about and retest etc...

**Comment by Andy-ABTec** [comment]
Just spotted this which might help...
In My shows with DVD Order unticked I see: -

![image](https://user-images.githubusercontent.com/5175695/37450916-c53db39c-2827-11e8-997a-2f7d3b05c744.png)

But with DVD Order ticked I see: -

![image](https://user-images.githubusercontent.com/5175695/37451006-1293d766-2828-11e8-8ab8-5fd857d727e0.png)

Haven't tried any other series yet but will go and do so now...

**Comment by Andy-ABTec** [comment]
"Wild at Heart" is doing similar...
DVD Unticked: 

![image](https://user-images.githubusercontent.com/5175695/37451140-8c271232-2828-11e8-8bf6-27f6b1f7ddeb.png)

DVD Ticked:

![image](https://user-images.githubusercontent.com/5175695/37451179-b09242a4-2828-11e8-9e3d-e665123804fc.png)

**Comment by MarkSummerville** [comment]
Doesn't look like it's behaving in any way that I wouldn't expect. (I understand that may look screwey though) Aired Season 5 for Burn Notice does not have a DVD order specified, so TVR considers them all specials/'not available on DVD'

See 
 * https://www.thetvdb.com/?tab=episode&seriesid=80270&seasonid=463361&id=4074811&lid=7
 * https://www.thetvdb.com/index.php?lid=7&seasonid=463361&seriesid=80270&tab=season&order=dvd

**Comment by MarkSummerville** [comment]
Same for Wild at Heart: https://www.thetvdb.com/index.php?id=81390&lid=7&tab=seasonall&order=dvd

**Comment by Andy-ABTec** [comment]
So its theTVDB then... Shows in question are locked so I dont hold out alot of hope getting them fixed but I'll try

Otherwise I shan't be using DVD order...

**Comment by Andy-ABTec** [comment]
Wild at Heart is unlocked on thetvdb, adding DVD episodes fixes the problem...

**Comment by MarkSummerville** [comment]
Yeah. It’s not something i’ll use much. It’s useful for series that has
episodes listed on dvd in a different order to the aired order. Eg Futurama

**Comment by MarkSummerville** [comment]
Ps thanks for taking the time to test and report back.

**Comment by Andy-ABTec** [comment]
No worries...
