### ISSUE TITLE
ical (.ics) server/export

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#37]
```
Built in ical server that other calendar apps can connect to.  and/or
export ical file, like we currently do with RSS for upcoming shows.


```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:43

**Comment by MarkSummerville** [comment]
Tracking this as a feature request: http://ideas.theideawall.com/TVRename/Forum/TopicDetails/1d87dc6e-09fa-4bb4-9d56-9442a07409cd?fb=0

Closing until we are ready to work on it

**Comment by MarkSummerville** [comment]
This was done
