### ISSUE TITLE
Auto Folder Creation Fails when Show has no directory entered

### ISSUE THREAD

**Issue by dosskat** [TV-Rename/tvrename#381]
# Expected Behaviour
I'm trying to scan for episodes of a newly added show.

# Current Behaviour
I get an error window with:
"unhandled exception has occurred in your application. If you click continue the application will ignore this error and attempt to continue, if you click quit, the application will close immediately.
Path is a zero-length string or contains only white space.
Parameter name: path"

I can continue, but the same error happens every time I try to click scan on any show that hasn't already been added to my library before the error started showing up. I don't actually get to the scan window as usually expected.

The error started showing up upon adding the show in the log file, just in case it's based on that specifically. I hadn't changed anything in particular immediately before this started happening, though I did add a new regex rule for parsing file names.

I have reinstalled, both with and without clearing user data, to no effect.

# Failure Information
I've included the text box from the error message, and a copy of the most recent log file (though I can't see anything out of the ordinary in the log itself)

## Steps to Reproduce
See above :)

Operating System: Windows 10 running on custom desktop, nothing particularly out of the ordinary!

[errorlog.txt](https://github.com/TV-Rename/tvrename/files/1968753/errorlog.txt)
[TVRename.log](https://github.com/TV-Rename/tvrename/files/1968754/TVRename.log)
[appdata-tvrename.zip](https://github.com/TV-Rename/tvrename/files/1968763/appdata-tvrename.zip)

I hope this is an apropriate place to ask for help with the issue, and thanks for all your work on this awesome app. Anything else I could provide to help with this error, just ask.

-chris

**Comment by MarkSummerville** [comment]
Looks like a problem when there is no folder specified for a series. In this case series with IDS 293119 and 269319 and 132941 are causing the problem

**Comment by MarkSummerville** [comment]
Fix is available in https://github.com/TV-Rename/tvrename/releases/tag/2.4.2-rc3 for testing

**Comment by dosskat** [comment]
Wow, you're quick! Thank you for all your hard work on the project and good luck with the 3.0 release
