### ISSUE TITLE
Please add option to use S# as season folders.

### ISSUE THREAD

**Issue by Rudu-be** [TV-Rename/tvrename#390]
Hello, I've been using TVrename for years now and i have always changed the code and build my own so that i can use "my" naming scheme. But since version 2.3... i have not gotten it to work and now with the 2.4... versions so much has changed i cannot find it in the code.

Can you please add the option to use just S# for season names, S and the number of the season, no space.

![image](https://user-images.githubusercontent.com/10807076/39671299-a357d750-5115-11e8-8d79-4d006c977e4c.png)

**Comment by MarkSummerville** [comment]
You should not need to do a code change. :-)

Do a search and replace for
`<SeasonFolderName>Season </SeasonFolderName>`
to 
`<SeasonFolderName>S</SeasonFolderName>`
in TVReameSettings.xml

For reference it is line 598 of ShowsAndEpisodes.cs

**Comment by Rudu-be** [comment]
I used to change it to a regex that looked for S## "SNumberNumber", if i change it to S it will accept series, and any "seriesname" with an S in it.

**Comment by MarkSummerville** [comment]
OK - I get that Bulk Add won't work quite right with this setup. Let me make a few tweaks.
