### ISSUE TITLE
Adjust new subtitle format to include 2/3 length country codes

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#391]
https://github.com/MarkSummerville/tvrename/blob/628a12c49f3bd3bfb251839c154f7ac42c81c730/TVRename%23/Utility/Helpers.cs#L250

Get the match and remove the right number of characters too

**Comment by MarkSummerville** [comment]
Regex will be `(?<ext>\.\w{2,3}\.(srt|sub|sbv))`

**Comment by MarkSummerville** [comment]
Update line 312 of TVDoc too to use named groups too

**Comment by Andy-ABTec** [comment]
Anything I need to be aware of for the website? (beta.tvrename.com)?

**Comment by MarkSummerville** [comment]
Good point!

Bits from this release that are worth documenting IMHO;
**Enhancements:**
 * ~~#353 Add new Export features (Rename XML, Copy/Move XML and Missing XML)~~
 * #355 Improved renaming when one file matches multiple shows or multiple files match one show

**Bug Fixes:**
 * #379 Improve Folder Deleting to include when ignore words are present
 * Command line handling improved
  - hide and unattended have been split to be more useful
 * #391 Fix to retain language specific subtitles
   - Update File & Folders Tab under Preferences
 * #390 Able to configure custom season words more accurately

**Comment by MarkSummerville** [comment]
Tracked on #395, closing this one
