### ISSUE TITLE
"Automating TV Rename" new website

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#393]
@MarkSummerville, just noticed that http://test.ab-tec.co.uk/manual/user#automating-tv-rename is still using "Lorem ipsun".

I'm not really up with the automation side of TV Rename, care to write something to go in there before the site goes live?

**Comment by MarkSummerville** [comment]
I updated the link to point to the appropriate place in the new content: http://test.ab-tec.co.uk/manual/features/#automating

Can just get rid of the Lorem Ipsun page now. I would do, but I'm not sure where it lives

**Comment by Andy-ABTec** [comment]
Its gone, along with its other "shortcut"
