### ISSUE TITLE
How to write a Regex for TV Rename

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#396]
In features...

Is there a reason the bullet points listing the regex sites are no longer links? - I'm sure I set them up as links...

**Comment by MarkSummerville** [comment]
I have not touched them. I agree they should be links.

This will show you the history of the file:
https://github.com/Andy-ABTec/minimal-mistakes/commits/gh-pages/_manual/features/finding.md

They seem to be links in the latest version. Maybe the  theme is removing them?

**Comment by Andy-ABTec** [comment]
Done - seriously, I must be getting old, I could have sworn I did it this way in the first place...
