### ISSUE TITLE
New Website release

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#397]
HI @sstteevvee 

I have another favour to ask in the DNS world (hopefully the last for a while:
 Could we point www.tvrename.com to https://tv-rename.github.io/website
and add legacy.tvrename.com to point to https://tv-rename.github.io/tvrename please?

Once this is done the new site: https://tv-rename.github.io/website/manual/quickstart/ should be available

I think we'll need to do a few tweaks our end to get the site up 100% after the DNS change

Thanks again

**Comment by Andy-ABTec** [comment]
@MarkSummerville I don't think the DNS needs to change in terms of _**www.tvrename.com**_, all you're doing is pointing at a different repo  owned by tv-rename.

I'm not 100% sure but I think you just need to release it from the current website and assign it to the new one

However we will need **legacy.tvrename.com** to keep the old site active after the move.

**Comment by MarkSummerville** [comment]
You are welcome to try, you have the appropriate access as far as I can tell. Having had a play last night I’m fairly sure a dns change is needed. I’m no expert though...

**Comment by Andy-ABTec** [comment]
Sorry, can't do it, don't have access to the settings menu for either repo... 8-(

**Comment by Andy-ABTec** [comment]
Looking at my dns provider I have 2 cname entries

| test | CNAME | andy-abtec.github.io
| old  | CNAME | andy-abtec.github.io

both of which point to andy-abtec.github.io

It's in the settings section of each repo that you set which custom name to use...

So in my case: -

old.abtec.co.uk points to the leap-day repo and
test.ab-tec.co.uk pointed to the minimal-mistakes repo before I changed it to beta.tvrename.com

**Comment by MarkSummerville** [comment]
OK - have made you an admin so you can try. I have tried to switch it over, but it's broken at the moment!

**Comment by MarkSummerville** [comment]
Actually maybe it has worked - just takes a while for it to propagate all the way out

**Comment by Andy-ABTec** [comment]
Certainly works for me... 🥇

**Comment by Andy-ABTec** [comment]
Works for me, I can also see the settings now, all looks fine...

Just waiting on @sstteevvee to create "legacy.tvrename.com" pointed at tv-rename.github.io for the old site, tweak the appropriate setting and you're done!

**Comment by MarkSummerville** [comment]
I don't think we need legacy.tvrename.com.

Only you and I would be looking at it to pull any content that (for some reason) has not been transferred to the new site. The site is available for review at https://tv-rename.github.io/tvrename
