### ISSUE TITLE
rar/zip support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#40]
```
Look in, and get files out of RAR and ZIP files.

Question of what to do after that.  e.g. delete single file archives, what
to do with multi-file, or single-file plus a NFO file.


```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:49

**Comment by MarkSummerville** [comment]
Tracked as New Feature http://ideas.theideawall.com/TVRename/Forum/TopicDetails/e205e333-7b02-4820-99ca-41396c0d84d5?fb=0 

Closing this for now

**Comment by MarkSummerville** [comment]
https://github.com/adamhathcock/sharpcompress

Looks like a good library to help.
