### ISSUE TITLE
Explorer right-click integration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#41]
```
* If it is a folder in the media library, could offer a "Scan"
* If it is any other folder, check against missing items.


```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:50

**Comment by MarkSummerville** [comment]
Closing as tracked here - can be reopened if we decide to work on it

http://ideas.theideawall.com/TVRename/Forum/TopicDetails/82c27b71-9c76-46a2-8fbf-72b42ae0bf01?fb=0
