### ISSUE TITLE
Multipart Regex (Episodes show up as missing in Scan section)

### ISSUE THREAD

**Issue by Filechaser** [TV-Rename/tvrename#412]
# Expected Behaviour
Files that include multiple Episodes (Multipart Regex-Rule) not showing up as missing episodes.

# Current Behaviour
Despite the Regex-Rule being correct and matching, the second episode of the Multiepisodefile is listed as missing episode.

Regex Tested with external Regex Tester

Example:
File: Yourshow  S01E01E02 Episodenames.mp4 
Yourshow S01E02 will be shown as missing in the Scan section.

# Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Happens all the time for every show added.
I am using TV-Rename just to check for missing episodes.  
Episodes are not downloaded by TV-Rename

## Context

Windows 10 newest Update
TV-Rename: 2.4.2 and 2.4.3 RC2
Files on Network location smb.
Access via UNC Path with DNS \\Servername\Folder\File

**Comment by MarkSummerville** [comment]
Have you added a season rule to merge the episodes?

This can be done in 3 ways:
1. Manually: Right click on Season in the 'My Shows' view
2. Automatically: Turn it on in the preferences (Scan options > "Automatically create merge rules..."). NB - this only happens as episodes are merged from the download folders into the library folders.
3. Reactively: Turn on Beta Menus then go to the Beta menu and select 'Duplicate Finder'. Right click on a possible match and then click Add Rule

Does that help?

**Comment by MarkSummerville** [comment]
We could add a function that identifies shows already in the library which requires merging. Ie a version of (2) above that works on the library folders.

it would mean changes around:
https://github.com/TV-Rename/tvrename/blob/0259f7ab4b3446120a983484c23e2b5d88bcec66/TVRename%23/TVRename/TVDoc.cs#L1248

**Comment by MarkSummerville** [comment]
Added a new feature for this

**Comment by Filechaser** [comment]
Does this mean, you already added it?
PS Manually adding merging rules would take years. 
The duplicate finder crashes at the moment.

How can I use your edition with the changes made? I am unfortunately only familiar with python scripts

**Comment by MarkSummerville** [comment]
Is there an error message when duplicate finder crashes? What’s happening in the log file at the time?

Yes I added the new feature. It will be in the next beta version released. 

Cheers

**Comment by MarkSummerville** [comment]
Just released a new version that has the new feature and has a fix *hopefully* for the dup finder issue you saw above

https://github.com/TV-Rename/tvrename/releases/tag/2.4.3-rc3
