### ISSUE TITLE
use own api key / use other server address

### ISSUE THREAD

**Issue by Filechaser** [TV-Rename/tvrename#416]
Glotz.info has a tvdb api that sends back information about series with swiss-german airdates and other location specific information.

Is it a lot of work to make an input field to change the tvdb api address and the api key?
I would really love it. At the moment API key and the address seem to be hardcoded, right?

Is there a donation button somewhere. 
I would like to thank you for fixing the last issue I had.

Thanks you 

Kind regards 

Filechaser

the Api Info: (Are there any differences that would stop it from working?)

<URL>/api/<apikey>/
|
|---- series/
|     |---- <seriesid>/
|           |---- <language>.xml  (same as tvdb with additional fields like  tvrage_id etc)
|           |---- banners.xml  (all banners of a series)
|           |---- actors.xml  (All actors of a series)
|           |
|           |---- all/
|           |     |---- <language>.xml  (same as tvdb with additional fields like  tvrage_id etc)
|           |     |---- <language>.zip  (Zipped version of Full Series Record, banners.xml and actors.xml)
|           |
|           |---- default/  (sorts using the default ordering method)
|           |     |---- <season#>/<episode#>/
|           |           |---- <language>.xml  (same as tvdb with additional fields like  tvrage_id etc)
|           |
|           |---- dvd/  (sorts using the dvd ordering method)
|           |     |---- <season#>/<episode#>/
|           |           |---- <language>.xml  (same as tvdb with additional fields like  tvrage_id etc)
|           |
|           |---- absolute/  (sorts using the absolute ordering method)
|           |     |---- <absolute#>/
|           |       |---- <language>.xml  (same as tvdb with additional fields like  tvrage_id etc)
|
|---- episodes
|     |---- <episodeid>/  (will return en.xml by default)
|           |---- <language>.xml  (same as tvdb with additional fields like  tvrage_id etc)

**Comment by MarkSummerville** [comment]
Hi,

Those details are the old API. New one is detailed at: https://api.thetvdb.com/swagger

As I understand it then there is there is only one one airdate that is provided per episode (from theTVDB.com) , so it doesn't matter which language you are looking at you'll always get the same date. If you can find an example then I can take a look and see how to get the localised airdates. If they have different airdates then I can only assume they are using a different source. Happy to be proven wrong though.

If you are suggesting that glotz.info/api is a source that we could use, then yes it could be a possibility, but it'd need a lot more work than just changing the API key and URL. We have spoken a few times about producing a range of sources. eg http://ideas.theideawall.com/TVRename/Forum/TopicDetails/384ca153-6518-4ed3-ba06-bb743ee4e440


There is a 'Buy me a drink' button in the App which goes back to the original developer (who created the whole thing and still pays for our website etc)

Thanks

**Comment by Filechaser** [comment]
As I wrote the server address which hosts a German edition of the tvdb is www.glotz.info

**Comment by Filechaser** [comment]
I just checked the documentation of glotz.info
They support the V2 Edition too.
So it should be possible to just change the apiserver address and the api key right?

Information on api:;

API V2 Optionen
JSON Format

https://www.glotz.info/v2/server/time

{
	"timestamp":1399726043,
	"timezone":"CEST"
}
Series Names
Gibt alternative Namen für Serien zurück

https://www.glotz.info/v2/names/tvdbid

tvdbid ist optional und gibt nur alternative namen der angegebenen ID zurück

{
	"248835":[
		"Once Upon a Time (2011)",
		"Once Upon a Time",
		"Once Upon A Time",
		"Once Upon A Time (2011)",
		"Once Upon A Time - Es war einmal...",
		"Once Upon A Time - Es war einmal",
		"Once Upon A Time Es war einmal"
	]
}
User Shows
Gibt eine Auflistung aller verfolgten Shows aus

https://www.glotz.info/v2/user/shows/1ZYV0PKTHS4YVRMI

tvdbid ist optional

Show List
Gibt eine Liste aller verfügbaren Shows aus

https://www.glotz.info/v2/shows/list

Kalender
Gibt alle Episoden aus die (ab heute) in den nächsten 7 Tagen ausgestrahlt werden. 
Startdatum und anzahl der Tage optional

https://www.glotz.info/v2/calendar/1ZYV0PKTHS4YVRMI/YYYYMMDD/TAGE

Optional: YYYYMMDD ein datum (zb. 20140430)
TAGE die anzahl der zu zeigenden tage (zb 1)

User Kalender
Gibt alle Episoden aus die (ab heute) in den nächsten 7 Tagen ausgestrahlt werden und zu einer verfolgten Serie gehören. 
Startdatum und anzahl der Tage optional

https://www.glotz.info/v2/user/calendar/1ZYV0PKTHS4YVRMI/YYYYMMDD/TAGE

Optional: YYYYMMDD ein datum (zb. 20140430)
TAGE die anzahl der zu zeigenden tage (zb 1)

Show Summary
Infos zu einer bestimmten Serie

https://www.glotz.info/v2/show/summary/1ZYV0PKTHS4YVRMI/NAME/extended

NAME kann sowohl der slug (bsp: the-blacklist) als auch die tvdb_id (bsp: 266189) sein

Optional: extendet gibt zusätzlich alle episoden so wie eine Liste der Schauspieler/Rollen aus

Show Updates
Auflistung aller Serien die nach einem gewissen Zeitpunkt geupdated wurden

https://www.glotz.info/v2/shows/updated/1ZYV0PKTHS4YVRMI/TIMESTAMP

timestamp muss ein unix timestamp der Zeitzohne CEST sein (siehe /server/time)

**Comment by MarkSummerville** [comment]
If they are genuinely exactly compatible with TVDB API v2 then it may be a simple job to try, but this would mean you have a version that is always linked to only glotz.info. All shows would be linked to that source. The feature  request would allow the user to choose between the sources for each show.

If you want to trial linking to the source then I'd suggest downloading the code and running in visual studio community (free) and change these three lines of code: 
https://github.com/TV-Rename/tvrename/blob/b232eb525f3fa595dfd710acd90703702f4bbd1f/TVRename%23/TheTVDB/TheTVDB.cs#L141
https://github.com/TV-Rename/tvrename/blob/b232eb525f3fa595dfd710acd90703702f4bbd1f/TVRename%23/TheTVDB/TheTVDB.cs#L142
https://github.com/TV-Rename/tvrename/blob/b232eb525f3fa595dfd710acd90703702f4bbd1f/TVRename%23/TheTVDB/TheTVDB.cs#L441

Let me know how you get on. I'll make sure we integrate it fully when we do:
http://ideas.theideawall.com/TVRename/Forum/TopicDetails/1c0aeb70-98ae-4937-9de3-8243ca61fcf2
or
http://ideas.theideawall.com/TVRename/Forum/TopicDetails/384ca153-6518-4ed3-ba06-bb743ee4e440

**Comment by MarkSummerville** [comment]
The old API is the xml format. The new one is the json format.

There must be some incompatibility/difference between the APIs. The API and calling code are fairly closely coupled, so it wouldn't take much to disrupt it.  What error message are you seeing? If you can persevere then you'll probably get it working in some way.

If we are going to work on a central feature then we'd need to make the provider configurable per show. Then we'd have different code for TVDB and glotz.info

**Comment by MarkSummerville** [comment]
If the glotz website is using the same API as the TVDB (which is defined here https://api.thetvdb.com/swagger) then:
https://www.glotz.info/api/login
should return the same as 
https://api.thetvdb.com/api/login

Looks like TV rename can't even logon

**Comment by MarkSummerville** [comment]
Closing as this is a new feature. Two idea wall links above are the Feature Requests that need to be completed for it
