### ISSUE TITLE
TheTVDB auth token fails to refresh (Timer is not running or faililng)

### ISSUE THREAD

**Issue by assafw** [TV-Rename/tvrename#421]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [X] I checked the [documentation](http://www.tvrename.com/userguide) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [X] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [X] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))
 - [X] It is not a general question( these should be asked on the [support forum](https://groups.google.com/forum/#!forum/tvrename))

# Expected Behaviour

Please describe the behaviour you are expecting - TVRename is open for more than 24 hours, on a laptop that goes to sleep/hibernate, When trying to scan for missing episodes - everything will work :)

# Current Behaviour

TVRename shows a 401 UNAUTHORIZED message box when trying to access the TV DB under those conditions

# Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open TV Rename, fetch episode updates (via scan or quick scan). 
2. put the computer to sleep for over 24 hours
3. wake the computer up, try to scan again, popup with failure comes up

Include whether it happens all the time or just sporadically. Also are there certain shows that it applies to?  What other investigation can/have you done?

all the time. the code is not written to support that. when using a 'Timer' to invoke, it will not trigger if the time has passed, or will fail/throw since it cannot refresh.

## Context
I have a proposed fix for this issue (or some direction for such a fix) - in a separate branch (locally) - please let me know **if** (and how) you'd like to receive it

**Comment by assafw** [comment]
Pull request submitted...

**Comment by MarkSummerville** [comment]
thanks @assafw - Really good to have someone help and contribute to a fix.

**Comment by assafw** [comment]
Happy to help @MarkSummerville :)

**Comment by MarkSummerville** [comment]
thanks - released to Beta: https://github.com/TV-Rename/tvrename/releases/tag/2.4.3-rc4
