### ISSUE TITLE
[Mede8er] "Viewed" status lost after rename process.

### ISSUE THREAD

**Issue by localhost61** [TV-Rename/tvrename#443]
The Mede8er firmware has an option to attach a "Viewed" status of a show. It creates a file with the full show's filename,  including extension, and add an other .t extension.

So, that watching the episode:
 "myTVshow - S01E01 - Title.avi"
will generate an ancillary file called:
 "myTVshow - S01E01 - Title.avi.t"
and this file will contain the full path as seen by the Mede8er, that is 
 "/tmp/ramfs/volumes/C:/TVSeries/myTVshow/Season 1/myTVshow - S01E01 - Title.avi" (but this contents is not checked and can be modified without loss of the feature).

The issue with those .t files is that I found no way to make TVRename process them and keep their filename synced with the show filename.

- If I add ";.t" at the `<OtherExtensions>` string :
 then "myTVshow - S01E01 - Title.avi.t" will be renamed "myTVshow - S01E01 - Title.t" and loose its movie extension so that all those files will be attached to nothing, I will lose the "Viewed" status history of all my shows in the Mede8er GUI.

- If I add ";.avi.t;.mkv.t;.rm.t;.mov.t" at the `<OtherExtensions>` string, I'll get a syntax error (file extensions are not supposed to hold a dot).

_[Edit] Escape angled brackets with "Code" quotes_

**Comment by MarkSummerville** [comment]
Looks like the validation is OK
https://github.com/TV-Rename/tvrename/blob/b91dd33f5a18d9f25b1f40a2d3e76e89e47ea311/TVRename/Settings/Settings.cs#L1012

If you add ";.mov.t" etc, Where do you get a syntax error?

Thanks

**Comment by MarkSummerville** [comment]
Also - which extension are you adding them to?
![image](https://user-images.githubusercontent.com/14905881/42143603-95ed077a-7de8-11e8-8a78-eab5aec660cd.png)

**Comment by localhost61** [comment]
@MarkSummerville I'm confused. I edited again the "Other extensions" string to make screenshots, removed and added one by one the double extensions I wanted to be processed and, that time, didn't get any syntax error.

But despite this,  it seems not to work.

I can check in TVRename.xml that the <OtherExtensions> tag is:
 <OtherExtensions>.srt;.nfo;.txt;.tbn;.jpg;.xml;.avi.t;.mkv.t;.mp4.t;.rm.t;.mov.t</OtherExtensions>
 
For testing, I choose a folder on the mede8er HDisc with only one season, and cleanup all TVDB/TVRename modifications.
- Remove all the .jpg, .xml and only keep the .avi, .mkv and their attached .t markers.
- Edit all filenames and keep only the minimal.
- Cleanup parent folder too.
- On TV, check that mede8er GUI shows all Viewed markers properly.
- Then remove the TV show from the TVrename database. Are you sure ? Yes !
- Save and Close TVrename
- Open TVrename again and add the TV show that was  previously removed, using the TVshow ID (hit search twice, as the first attempt always report "0 found"). Fill the base folder field. Set ignore seasons 0. And save.
- Refresh the TV show and check that all the episodes are retrieved from TVDB 
- Open the contextual menu with a right-click on the new TVshow item that appears in the tree and hit "Scan..."

-> In the scan tab that appears, TVrename will properly schedule the renaming of all the video files and the creation of the .jpg and .xml  downloaded from TVDB for the show, the season and all the episodes.
-> But the renaming of the .t files doesn't show and won't be achieved after a hit on "Do checked".

**Comment by MarkSummerville** [comment]
Hi,

Your testing aligns to mine. I think that that validation of the field is OK. I also agree that it doesn't work. I have a code fix ready to go that'll fix it up too.

Should be checked in the next few days and then released to beta in a few weeks

Cheers

**Comment by MarkSummerville** [comment]
Beta version is out now: https://github.com/TV-Rename/tvrename/releases/tag/2.4.3-rc4

**Comment by localhost61** [comment]
@MarkSummerville
Issue solved and orphean markers were renamed too and are now recognized as such.
Thanks a lot !
