### ISSUE TITLE
Find something that does not use old folder naming format in BulkAddShows

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#471]
It should be anywhere like here 

https://github.com/TV-Rename/tvrename/blob/master/TVRename/TVRename/BullkAddManager.cs#L87-L95

and select the 'Library default' name ... Not the custom one for BulkAddShows

**Comment by Chlorel** [comment]
Issue can be closed, the fix is up and run exactly like it have to do :)

**Comment by MarkSummerville** [comment]
I think there is still a case to improve this function. I had in mind that if your format was "01 Season 2017" for example then we could pattern match

**Comment by MarkSummerville** [comment]
Same as #492, closing this one
