### ISSUE TITLE
Something wrong with qBitTorrent

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#475]
Installed WebUI on my incomming computer ( that use's  qBitTorrent for the incomming show's ) ... 
I opened the whole intranet ip class ( 192.168.0.0/24 ) to be sure my computer is in whitelist ( my computer : 192.168.0.15 ) 
I use qBitTorrent 4.1.2 ( the last one )
I documented in Options / Torrent the computer name and port : F-CHARGE 8080 
I checked too in Options / Scan options the qBitTorrent thing ...

I access to the WebUI from my computer without login & pass
I tryed manualy :+1:  /query/preferences

**Comment by Chlorel** [comment]
/query/torrents?filter=all
and selected on hash i got in result for the /query/propertiesFiles/$hashcode
i got every time answer from qBitTorrent ...

But In TVRename ( log file ) 
|WARN| Could not connect to http://F-CHARGE:8080/query/, Please check qBitTorrent Settings and ensure qBitTorrent is running with no password required for local connections 
and in TVrename it self nothing change when i scan ... ( and i Know they are files for the scanned show in qBitTorrent queue )

**Comment by MarkSummerville** [comment]
In my setup TV Rename and qBit are running on the same PC, so the ‘don’t use password for local connections’ is enough to allow access. 

In your setup are they on different computers? If so, then we probably need to send a username and password. I wanted to avoid having the password in cleartext in the tvrename settings file though

**Comment by MarkSummerville** [comment]
If you can then maybe step through the code to see exactly where the issue comes from

**Comment by Chlorel** [comment]
The issue is just on the first line after the try (line 36)
I restarted step by step more time the only thing i seen is in JSONHelper line 37 they where some null in request after creating ...


But if it was a user/password thing ... should i not be unable to play with UI API from any web broser arround ??  I started WebUI in Firefox ( to see the progress of my torrents ) and i played with API in chrome .... never given a username or password ....

**Comment by Chlorel** [comment]
One step later ...
request have a private member 'ChallengedUri' that is null after create process

**Comment by Chlorel** [comment]
Bigging a bit deeper ...
Installed TVRename to my Incomming computer ... 
Bulk added some show's ( that are in download now )
Tryed the scan ... and nothing ...

Replaced the computer name with 'localhost' ... and nice ... it run !
On my computer replaced the computer name too ... and oh nice it run's too !

Now the only hint i can stick ... is the µTorrent icon instead th qBitTorrent one :)
