### ISSUE TITLE
After "Force Refresh All" from menu Downloader stay in idle 

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#476]
For some unknow reason i got the "We have run 10 weeks of updates ...." message ...
So i tryed the force refresh all ...
After what nothing happen's ...
To finaly start the download process .. i had to try a scan ... and before scan downloader do the refresh

( the vers is at the all last stand i pull every new commit you do on master to test on my side )

**Comment by MarkSummerville** [comment]
What was the full text of the ‘10 weeks’ message? Wondering whether that is a bug or something to do with your dev setup. 

I have seen issues where the ‘force refresh all’ clears out the old data and doesn’t download new stuff. I’ve never been able to reproduce it reliably though. 

As you say, workaround is to start a scan. Which forces the redownload to happen

**Comment by Chlorel** [comment]
We have run 10 weeks of updates and we are not up to date.  The system will need to check again once this set of updates have been processed. " ++ " New Last Updated time is " ++ " If the dates keep getting more recent then let the system keep getting 10 week blocks of updates, otherwise consider a 'Force Refresh All'

Not in mood to reproduce the message on this ShowBase ... but next time, will do a screencap ...

I between, i found one easy way to do my multi basis Show collection ... Let me know if want to get my idea
