### ISSUE TITLE
Scan function does not mark episods as missing

### ISSUE THREAD

**Issue by Stolle98** [TV-Rename/tvrename#479]
Hey, i've got an issue:
when i scan my shows it doesn't show me which episodes are missing. Only the specials are listed as missing although I know there are many episodes that are not included in my library yet. No seasons are set to be irgnored.

![1](https://user-images.githubusercontent.com/42513715/44308608-2a5fd180-a3b9-11e8-9686-5e62fa84d671.PNG)
TV-Rename marks this episods as missing, what is right.

![2](https://user-images.githubusercontent.com/42513715/44308609-2a5fd180-a3b9-11e8-98e8-85604aa31ed6.PNG)
But here you can see what i have got in season 3 for example. As you can see many episods are missing.

![3](https://user-images.githubusercontent.com/42513715/44308610-2a5fd180-a3b9-11e8-83a0-a85ef84ee0b0.PNG)
This is the Season List

I hope you can help me with this problem or tell me what is wrong.
with best regards Tim

**Comment by Chlorel** [comment]
Have you tryed a 'Force refresh', just on this show ?

**Comment by Stolle98** [comment]
Yes I already tried "Force refresh" on this show. Nothing changed.

**Comment by MarkSummerville** [comment]
@Stolle98 Any updates? This functionality seems to work for others

**Comment by MarkSummerville** [comment]
Hey - Closing until there is more information to reopen
