### ISSUE TITLE
Do not rename files with extension in uppercase

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#487]
By scanning some show's, i noticed that some files do not be renamed ... and all addon files (xml / jpg) are named like the original episode file name ... That happen's only when the extension is in uppercase

**Comment by MarkSummerville** [comment]
Can you give me some examples please?

**Comment by Chlorel** [comment]
Sure easy ... Just change any extension to upper case ... like i done it for the last TBBT episode see scan result and folder 

![capture-a](https://user-images.githubusercontent.com/8551213/44583062-0bd84c80-a7a4-11e8-8a33-bd054840a214.PNG)
![capture-b](https://user-images.githubusercontent.com/8551213/44583063-0bd84c80-a7a4-11e8-8907-3d0958008dfb.PNG)

**Comment by Chlorel** [comment]
After changing extension to lowercase the process run's normaly

![capture-c](https://user-images.githubusercontent.com/8551213/44583245-a2a50900-a7a4-11e8-9ffe-f87ae01c927a.PNG)

**Comment by MarkSummerville** [comment]
Can you try the latest in master please?

Should fix it, but I've not tried myself

**Comment by Chlorel** [comment]
Updated my master to last stand ... Updated my actual branche to last stand with my add's .. compiled checked out .. look's like it will run now
