### ISSUE TITLE
Some naming troubles to come ?

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#493]
![capture](https://user-images.githubusercontent.com/8551213/44856985-1183d580-ac6f-11e8-99b2-cd6170fd8b93.PNG)

After last update ( i know french people does not have same chars in there file names )

**Comment by MarkSummerville** [comment]
Hmm - I can't think that anything has changed in this area between releases

**Comment by Chlorel** [comment]
I have no idea where it is localised in code, it checked it out with official release before posting the issue

**Comment by Chlorel** [comment]
Look's like once more it's a TvDB bug ... Some time the " ' " is writen " ' " ... and some other time the same char is writen &#39; checked it out on two show on TvDB : Billions (ID:279536) Season 2 it's writen " ' " and in Season 3 as &#39; ... Same with Gotham (ID:274431) in Season 2 & 3 as &#39;  ... Is there any function or method to replace url specific char's to ansi ?

**Comment by Chlorel** [comment]
Well after digging a bit deeper, it look's like a : System.Web.HttpUtility.HtmlDecode()  on the episode name get all these special encoded char's to ansi char's again ... Just find the right place now (just on the place where the episode info's are downloaded)
