### ISSUE TITLE
Subtitle finding/downloading support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#5]
```
Automatically find and download subtitles for shows.

http://tvrename.com/bb/viewtopic.php?f=4&t=453

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:00

**Comment by MarkSummerville** [comment]
Link is http://old.tvrename.com/bbold/4/t-453.html

Raised as http://ideas.theideawall.com/TVRename/Forum/TopicDetails/1556bd80-10e1-4436-ad27-cc8a28d6c642?fb=0

so closing here until someone wants to work on it or people raise the priority
