### ISSUE TITLE
Source contains multiple versions 

### ISSUE THREAD

**Issue by BacchusFLT** [TV-Rename/tvrename#507]
I ran into the issue of the source having multiple version of the samt episode in the scan folder. Some where MKV, some MP4 and some AVI. TV Renamer didn't import any thing or didn't tell me anything. It took me quite while to figure out that I had to delete one of the alternatives. The bare minimum would be indicating that this is the reason it wasn't imported would be nice, but way better would be to be proactive and give the option to upgrade versions (higher resolution) and delete the inferior versions.

**Comment by MarkSummerville** [comment]
Can you explain a little more about this issue please?

TV Rename should:
 * Search through all episodes of shows it tracks and identify any missing episodes.
 * For missing episodes it looks in a series of places to try and find a copy.
 * If it finds a copy it suggests to move/rename.

It should happily deal with shows in different format - even for the same series. You should not have to have deleted one of the alternates. What exactly 'failed to import'?


NB - There is some work underway about an 'upgrade' function, that identifies when a better quality version comes along and upgrades it. That is a new feature tracked on the ideas wall.

**Comment by MarkSummerville** [comment]
Hi,

Check the log file: https://www.tvrename.com/manual/technical/#log-files

Generally if there are multiple files that may match they are not moved and the user is notified in the logs.

In the future we will look at them both and choose the one with the best quality to copy across.

Older versions copied one at random

Hope that helps

**Comment by BacchusFLT** [comment]
Reverting to logfiles is naturally not a very user friendly option, but you
are obviously aware and it might be part of future improvements. Looking
forward to that ...

I guess adding a section to the scan result, where you show both and tag
one for deletion and one for rename + move is the suggested way forward.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den tors 25 okt. 2018 kl 12:51 skrev MarkSummerville <
notifications@github.com>:

**Comment by BacchusFLT** [comment]
[image: Thumbs_up_1.jpg]

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den fre 26 okt. 2018 kl 02:26 skrev MarkSummerville <
notifications@github.com>:
