### ISSUE TITLE
Force Close on Scan

### ISSUE THREAD

**Issue by Hans007a** [TV-Rename/tvrename#513]
After version 2.6 RC4 all next versions force close after starts to scan tv shows without any logs.
My tv shows are on a NAS drive and I installed the last .net v4.7.2

Regards

Hans

**Comment by Hans007a** [comment]
I fond the log (but why not in the program folder, it would be easier to find it) and here the needed part:

2018-11-08 22:33:20|FATAL| UNHANDLED ERROR System.IO.FileNotFoundException: Die Datei oder Assembly "System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
Dateiname: "System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
   bei TVRename.TVDoc.ScanWorker(Object o)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

Regards

Hans

**Comment by MarkSummerville** [comment]
The latest version released last night should fix this issue.

**Comment by Hans007a** [comment]
the log is from 2.6 release version

**Comment by MarkSummerville** [comment]
Hmmm. Have you rebooted since installing? May need a reboot after .net v 4.7.2 is installed

**Comment by MarkSummerville** [comment]
Hi @Hans007a 
Did that work? I saw some similar issues early on with RC4, but they should have cleared up.

Let us know

**Comment by MarkSummerville** [comment]
From the forums, it seems that a reboot is needed after 4.7.2

Feel free to reopen if it doesn’t fix your problem
