### ISSUE TITLE
Installer check and warn if TVRename already running

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#53]
```
When installing a new version, or uninstalling, check to see that TVRename
isn't running.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 1:06

**Comment by JoeBiellik** [comment]
[This can be done](http://nsis.sourceforge.net/Check_whether_your_application_is_running) but I question the necessity.

**Comment by MarkSummerville** [comment]
I agree. You get a message like the following that is pretty clear:
![image](https://user-images.githubusercontent.com/14905881/35951300-c92ac586-0cb5-11e8-85ac-c7e75ba9a9cc.png)
