### ISSUE TITLE
UI componen s stacked..

### ISSUE THREAD

**Issue by BacchusFLT** [TV-Rename/tvrename#555]
2.6.5, the Scan tab always shows this (the "All" checkmark sits on top of the rightmost button. Not sure what is says as I can't read it) 

![image](https://user-images.githubusercontent.com/28536010/51282195-bf0c4100-19e4-11e9-81a1-360fcba5a2fa.png)

**Comment by MarkSummerville** [comment]
Can you make the application wider? The checkboxes move right as the app becomes wider, whilst the buttons stay on the left

**Comment by BacchusFLT** [comment]
This is the standard size it opens on my HTPC/torrent computer. I will
check tomorrow if I can resize, but in general the size I use now hasn't
changed as far as I recall...

**Comment by MarkSummerville** [comment]
in 2.9.0
