### ISSUE TITLE
Unclear why some shows Fail to add

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#577]
Failed to Add Le tueur du lac with   TVDBId=300198 to library
Failed to Add Archer (2009) with   TVDBId=110381 to library
Failed to Add The Grand Tour (2016) with   TVDBId=314087 to library

**Comment by MarkSummerville** [comment]
Have not seen this since 2.6.6

https://papertrailapp.com/groups/12610562/events?q=with%20TVDBId%3D
