### ISSUE TITLE
Mapped drives "disconnected" after reboot

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#58]
```
Drives don't reconnect until explorer visits them.  TVRename sees them as
missing.

* http://tvrename.com/bb/viewtopic.php?p=854#p854
* http://forums.microsoft.com/MSDN/ShowPost.aspx?PostID=2279366&SiteID=1
* WSHNetwork?
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 1:13

**Comment by JoeBiellik** [comment]
I don't think this is something that should be handled inside TV Rename.

**Comment by Andy-ABTec** [comment]
Seconded - maybe highlight that the drive can't be found and skip it in the scans but go no further...

**Comment by JoeBiellik** [comment]
@Andy-ABTec I think it's outside the scope for TV Rename to handle network mappings any differently from normal locations. A mapped network location isn't always a drive - it can also be a directory or symlink as well.

There are [plenty](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/60339d17-6901-4c83-a07d-60fd40a9470c/windows-7-could-not-reconnect-all-network-drives-at-boot-up?forum=peertopeer/) of [ways](https://sourceforge.net/projects/mapdrive/) to [address](https://winaero.com/blog/windows-10-reconnect-network-drives/) this issue with Windows at the system level.

**Comment by MarkSummerville** [comment]
This [feature request](http://ideas.theideawall.com/TVRename/Forum/TopicDetails/ca1525c1-4011-4e7d-a613-b1a882e658fa) is a pretty good way of handling some of the issues here.

Other than that, then maybe add the links above to the 'Tips & Tricks' section of the website? @Andy-ABTec

**Comment by Andy-ABTec** [comment]
OK, Ill have a read...

**Comment by Andy-ABTec** [comment]
Having read through the links that Joe provided I wouldn't be prepared to put my name to any of them.

Personally I have 3 old NAS 1100 devices (sparc based from Netgear  - that's how old!) and I never had a problem connecting to any of them on restart from XP, 7 or 10 using UNC paths and mapped drives unless a box had failed or crashed.

As Joe said, we're not in the windows repair business, surely the simplest solution is to pop a box up saying I cant find such-and such and move on. If this was an unplugged USB drive we wouldn't even be having this conversation...

**Comment by Andy-ABTec** [comment]
Actually what would happen in TV Rename if it was an unplugged USB disk in the search path?

**Comment by JoeBiellik** [comment]
I have PCs that boot to the desktop before DHCP has had time to hand out an IP and setting the "Always wait for the network at computer startup and logon" group policy fixes it at the cost of a slightly slower login.

The problem with showing a popup explicitly for non-connected network drives is we can't easily identify them. Currently, we show a single form if any directory is missing (show or season), network, USB or otherwise, prompting the user to create the folder, skip or locate it which I think is sufficient until we implement the feature request Mark linked.

**Comment by Andy-ABTec** [comment]
"Always wait for the network at computer startup and logon" group policy fixes it at the cost of a slightly slower login. I'm more that happy to go with, I'll sling something together...

 A lot of the stuff I read involved batch files running as startup and the like - yugh!

**Comment by Andy-ABTec** [comment]
Seems with the latest Win 10 builds its only available if the Local Group Policy Editor is installed - not prepared to open that particular can of worms on someone else's machine especially as we dont know what state it's in. 

Cant find a Registry key either...

**Comment by JoeBiellik** [comment]
[Details at the bottom](https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsLogon::SyncForegroundPolicy), but I don't think we want to be recommending registry changes to users.

**Comment by Andy-ABTec** [comment]
Been there, tried that key doesn't appear to exits in my build of windows 10... 8-(

Totally agree, we want to be recommending registry or gp changes to users.

**Comment by JoeBiellik** [comment]
Setting the group policy created that registry key and path for me in Windows 10 Pro 1709.

**Comment by Andy-ABTec** [comment]
Ahh, there's the difference, I'm running Windows HOME 1709 - no Group Policy editor, had to install it...

We DEFINITELY don't want to be recommending registry or gp changes to users - its a problem with their machine/network, NOT TV Rename.

**Comment by JoeBiellik** [comment]
Closing this as out of scope.
