### ISSUE TITLE
BulkAddShow ... hang when try to AUTOID a bunch of series 

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#596]
Hi,

Installed the last released TVRename ... And to test it right, decided to get to a brand new install ( deleted everthing in roaming TVRename\TVRename\2.1

After twicking arround, i got the setup like it was before ... I know i have a big amount of series on my V: drive ... So setted Library folder to V:\_INCOMMING ( where every goes in after download completed )
added also every 'base' folder where shows are stored once renamed ...

![pref3](https://user-images.githubusercontent.com/8551213/51922723-e6eaa400-23e9-11e9-9517-7acb6411aef2.PNG)

like show here ...

So i try a bulk add show ...
First step check ... all is right ... TVR find all m_ show folders at there places ...

![bulkadd check](https://user-images.githubusercontent.com/8551213/51922958-53fe3980-23ea-11e9-99a6-789406f48134.PNG)

Second Step ... trying to Auto ID all the shows ... 
One click ... and wait ... wait ... wait ... ( 2 chocolates and 3 buck beer later waiting ... to see TVR is hanging ) and hang seriously ( needed taskman to exit from process )

[TVRename.log](https://github.com/TV-Rename/tvrename/files/2808600/TVRename.log)

here log file to ...
any idea ??

**Comment by MarkSummerville** [comment]
Founda fix for 2.7.2

**Comment by Chlorel** [comment]
Lokk's like it run ... but find it very slow ... will check it with my older build and come back with values
