### ISSUE TITLE
Error creating folders on network share

### ISSUE THREAD

**Issue by subxero** [TV-Rename/tvrename#597]
Hi, using lastest version 2.7.1

I'm using a NAS with all data to share between computers, the nas works perfect, there aren't any problems with access or file permissions. Windows explorer and media players works perfect.

The new version dont like share drives, previous was working fine.

The program detects a new episode on download folder and ask for permision to create a destination folder and stucks there, asking and asking the same, you can create manually the expected folder but still trying to create dialog.

I tried changing absolute path to assigned unit "Z:" with the same results.

2019-01-29 22:01:11|INFO| Creating directory as it is missing: \\10.0.0.2\share\vose\Gotham 
2019-01-29 22:01:30|INFO| Could not directory: \\10.0.0.2\share\vose\Gotham 
2019-01-29 22:01:30|INFO| System.IO.IOException: (53) No se ha encontrado la ruta de acceso de la red: [\\10.0.0.2\share]
   en Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   en Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   en TVRename.CheckAllFoldersExist.CreateSeasonFolders(ShowItem si, Int32 snum, List`1 folders) System.IO.IOException: (53) No se ha encontrado la ruta de acceso de la red: [\\10.0.0.2\share]
   en Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   en Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   en TVRename.CheckAllFoldersExist.CreateSeasonFolders(ShowItem si, Int32 snum, List`1 folders)
2019-01-29 22:04:53|INFO| Creating directory as it is missing: \\10.0.0.2\share\vose\Gotham 
2019-01-29 22:05:13|INFO| Could not directory: \\10.0.0.2\share\vose\Gotham 
2019-01-29 22:05:13|INFO| System.IO.IOException: (53) No se ha encontrado la ruta de acceso de la red: [\\10.0.0.2\share]
   en Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   en Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   en TVRename.CheckAllFoldersExist.CreateSeasonFolders(ShowItem si, Int32 snum, List`1 folders) System.IO.IOException: (53) No se ha encontrado la ruta de acceso de la red: [\\10.0.0.2\share]
   en Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   en Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   en TVRename.CheckAllFoldersExist.CreateSeasonFolders(ShowItem si, Int32 snum, List`1 folders)

You can ignore it but then dont found and episode to rename

* Operating System: W10 64bit 1809
* Are you using the windows version or command line version? windows

**Comment by fgnn** [comment]
I also am experiencing this issue. I upgraded from version 2.3.? to version 2.7.1 and it no longer detects the mapped network drive from my NAS.

OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

**Comment by MarkSummerville** [comment]
Hi @fgnn - what is the error message you are seeing? What are you seeing in the logs?

**Comment by MarkSummerville** [comment]
Also there are some tips on the website that may help for windows 10

https://www.tvrename.com/manual/tips-tricks/

Maybe they'll help?

**Comment by subxero** [comment]
Hi, MarkSummerville.
The registre tip doesn't works.
The new version 2.7.2 have the same problem
2019-01-31 22:49:41|INFO| Creating directory as it is missing: \\nas\share\Arrow 
2019-01-31 22:49:43|WARN| Could not create directory: \\nas\share\Arrow Error Message: (53) No se ha encontrado la ruta de acceso de la red: [\\nas\share] 
2019-01-31 22:49:45|INFO| Creating directory as it is missing: \\nas\share\Arrow 
2019-01-31 22:49:45|WARN| Could not create directory: \\nas\share\Arrow Error Message: (53) No se ha encontrado la ruta de acceso de la red: [\\nas\share] 
.....
2019-01-31 22:49:55|INFO| Creating directory as it is missing: \\nas\share\How to Get Away with Murder 
2019-01-31 22:49:55|WARN| Could not create directory: \\nas\share\How to Get Away with Murder Error Message: (53) No se ha encontrado la ruta de acceso de la red: [\\nas\share]

**Comment by GeorgeBell1982** [comment]
Hi @MarkSummerville,

I have the same error where the mapped network drives are not picked up. So I pulled the latest master branch and to my surprise the version is 6.10 and the drives are visible. I would look into this issue for you if you need help, but not getting the latest code is a bit of a problem.

Please let me know if I can help, in the mean time I will be using version 6.10 as that still works correctly with the mapped network drives.

**Comment by Andy-ABTec** [comment]
Curious, I think you'll find that master is the latest version but the version numbers haven't been updated for a while...

**Comment by GeorgeBell1982** [comment]
> Curious, I think you'll find that master is the latest version but the version numbers haven't been updated for a while...

@Andy-ABTec, very curious then as the network mapped drives work on my debug version. I will do a release compile and check tonight

**Comment by MarkSummerville** [comment]
Hey, If you pull master then you'll have the latest. The version number is updated by the automated build processes. I have manually updated to reassure you.

Generally we've seen most of these sorts of problems be resolved by a reboot and to check which user the application is running as. Some people are / are not running the process as administrator.

Also some people were seeing issues when running TVR directly from the installer

**Comment by GeorgeBell1982** [comment]
thx @MarkSummerville , very strange that v2.7.4 now works correctly in picking up the mapped drives, not sure what changed though ("scratches head"). Oh well, thx for the responses, if you ever need some help on issues, give me a pm

**Comment by MarkSummerville** [comment]
Thanks for taking a look. As I said before most people have found that the problem has mysteriously gone away too. I’ve not been able to identify anything consistent about when the problem does/ does not occur yet

We do seem to have an uptick if issues when new versions are released.

**Comment by MarkSummerville** [comment]
@subxero @fgnn Are your problems persisting?

**Comment by subxero** [comment]
I don't known why but last version 2.7.9 works, dont have this issue. 

👍 

BR
