### ISSUE TITLE
Merged epsiode auto-naming

### ISSUE THREAD

**Issue by koryhughes** [TV-Rename/tvrename#601]
# Expected Behaviour

When two episodes are merged, the automatically generated name should be in the format "{First name} + {Second name}".

# Current Behaviour

When the episode names are simply in the format "Episode {number}", and both episode numbers are multiple digits, and share more than one significant digit, then the automatically generated name is truncated to "Episode {common digits}", ie:

Merging two sequential episodes named "Episode 13" and "Episode 14" will result in an automatically generated name of "Episode 1" rather than "Episode 13 + Episode 14".

The issue seems to be related to the [GetBestNameFor](https://github.com/TV-Rename/tvrename/blob/master/TVRename/TVRename/ShowLibrary.cs#L514) method and the [GetCommonStartString](https://github.com/TV-Rename/tvrename/blob/master/TVRename/Utility/Helper/Helpers.cs#L248) method, which essentially do a very naive check for a common starting string. I presume this is to mop up cases like "Episode Name - Part 1" and "Episode Name - Part 2", which would get trimmed down to "Episode Name" in the current code.

# Failure Information

## Steps to Reproduce

1. Add a TV show that uses the episode number at the end of the episode name
2. Add a merge rule, merging two of the episodes together
3. Do not provide a custom name for the merged episodes.

[Here](https://www.thetvdb.com/series/my-strange-hero/seasons/1) is one such show that triggers this bug.

## Context

I've attached XML and Log files from the latest code compiled locally, but I've also been able to see this on the release versions, going back some time now.

* Operating System: Windows Server 2016 & Windows Server 2019
* Are you using the windows version or command line version? Windows version

## XML Files

[TheTVDB.txt](https://github.com/TV-Rename/tvrename/files/2813068/TheTVDB.txt)
[TVRenameSettings.txt](https://github.com/TV-Rename/tvrename/files/2813069/TVRenameSettings.txt)

## Log Files

[TVRename.log](https://github.com/TV-Rename/tvrename/files/2813074/TVRename.log)

**Comment by MarkSummerville** [comment]
Thanks for the clear write up. They can be manually overwritten for the few that it will create wrongly.

A small change in 2.7.2 should fix up the '"Episode 1" rather than "Episode 13 + Episode 14".' issue.

Have you identified any others that it gets wrong?

**Comment by koryhughes** [comment]
Thanks, I've pulled down the latest code and confirmed that this fix works for me.

I've not noticed any other issues with the automatically generated merge names.
