### ISSUE TITLE
User-definable "copy" "move", etc. functions/scripts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#61]
```
Have TVRename run external scripts (or hit webpages) for carrying out a
move/copy operation, rather than doing it ourselves.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 1:17

**Comment by MarkSummerville** [comment]
https://github.com/TV-Rename/tvrename/issues/15
https://github.com/TV-Rename/tvrename/issues/61
http://old.tvrename.com/bbold/4/t-396.html

Raised as http://ideas.theideawall.com/TVRename/Forum/TopicDetails/3ca8665a-2968-4b6c-9220-420fd3c942e4?fb=0, so closing here for now
