### ISSUE TITLE
Path.... still too long

### ISSUE THREAD

**Issue by DigitalDJ** [TV-Rename/tvrename#616]
Regarding issue #614 

The NameFor function in CustomEpisodeName.cs does not take into account the full path of the episode.

The MAX_LENGTH of 250 is supposed to include the full path to the episode, not just the filename.

Previously, the folder of the episode was passed to the function, but now it is not.

**Comment by DigitalDJ** [comment]
Not to mention, a MAX_PATH constant already exists, and the maximum is not 250, but 260.

**Comment by MarkSummerville** [comment]
The path length should not be an issue as we use a library that avoids this restriction. The 250 260 issue is because we don’t know the length of the extension, so assume a max extension of 10 characters

Having said all that there is still a chance that there are a few bugs left

Do you have a specific example of the issue?

**Comment by DigitalDJ** [comment]
Sorry, I should have included an example.

I fired up a debug copy of found that AlphaFS throws a PathTooLongException

I'm not sure where the assumption is that AlphaFS truncates the path.

In DoCopyRename, From and To are as follows:

From: (Length 199 -- what previous versions of TVRename did)
a:\warez\tv shows\Battlestar Galactica (2003)\Season 0\Battlestar Galactica (2003) - S00E33-E39 - Razor Minisode (1) Day 4,571 + Razor Minisode (2) The Hangar + Razor Minisode (3) Operation Rapt.mp4

To: (Length 300 -- current master)
a:\warez\tv shows\Battlestar Galactica (2003)\Season 0\Battlestar Galactica (2003) - S00E33-E39 - Razor Minisode (1) Day 4,571 + Razor Minisode (2) The Hangar + Razor Minisode (3) Operation Raptor Talon + Razor Minisode (4) Free Fall + Razor Minisode (5) The Lab + Razor Minisode (6) Survivors +.mp4

**Comment by MarkSummerville** [comment]
I tested on a few systems and the AlphaFS does allow move and rename of longer filenames, however the XML writing for XML nfo didn't work and even windows explorer didn't allow you to rename the resultant files. SO have re-introduced a 260 character path limit.

Please try the latest and report back if further optimisations are needed

**Comment by DigitalDJ** [comment]
Thanks, this appears to work now. But do note, even if Windows Explorer is updated to allow you to work beyond the 260 path limit, if the target is a network file system with compatibility restrictions in place, AlphaFS will never be able to bypass the server side restrictions.
