### ISSUE TITLE
Run script/command after completing actions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#62]
```
http://tvrename.com/bb/viewtopic.php?f=4&t=239

When done doing all actions on "Scan" tab, run external
program/script/website.  Maybe pass arguments saying what was done, and/or
location of XML log file.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 1:18

**Comment by MarkSummerville** [comment]
Closing as recorded here: http://ideas.theideawall.com/TVRename/Forum/TopicDetails/8a8720c7-3a84-4630-b298-cf992e332dcc

Old discussion here http://old.tvrename.com/bbold/4/t-239.html
