### ISSUE TITLE
[Feature Request] Add list of files to rename directly into the interface

### ISSUE THREAD

**Issue by Ansem93** [TV-Rename/tvrename#628]
Hi everyone.
I wanted to ask if it's possible to have a feature similar to filebot where I put the list of episodes into the interface and I rename them without moving them.
I need to rename older series that I already have and I don't get how to it one at time :(

**Comment by MarkSummerville** [comment]
Sorry but having never used filebot you'll need to explain in more detail what you are after. Maybe ask on the forums or if it is a new feature then use the ideas wall:

https://groups.google.com/forum/#!forum/tvrename
http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0

Only bugs should be raised here
