### ISSUE TITLE
Bug: Scan Downloads Folder for Changes

### ISSUE THREAD

**Issue by AzWasHere** [TV-Rename/tvrename#629]
I torrent files into my Downloads Folder, which I also have set to scan when changes are monitored. So, as long as torrents are active, I cannot use TV Rename because it scans relentlessly, despite cancelling.

I recommend a cool-down period between scans initiated by monitoring changes, or at least when an auto-initiated scan is cancelled. Bonus points for making this adjustable.

Thanks!

**Comment by MarkSummerville** [comment]
Maybe try to set your download tool to move them to another location once complete, then scan that location from TVR? Would that solve it?

**Comment by MarkSummerville** [comment]
eg https://www.techsupportalert.com/utorrent-help-move-downloads-category-folders-bittorrent
or https://imgur.com/a/JSfMZ
etc

**Comment by MarkSummerville** [comment]
@AzWasHere Has this suggestion helped? Let us know as if not then we can put this feature request on the ideas wall to be proritised with the other new features: http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0
