### ISSUE TITLE
Base Folder default value?

### ISSUE THREAD

**Issue by rrrevin** [TV-Rename/tvrename#645]
Running 2.8.9..

Perhaps I can't find it, but is it possible to have a default values for everything under "Folder Tab", found at "Add -> Folders"? Things like "Automatic Folders", "Base Folder", etc.. I find myself changing these ALL the time I add a new show to the same settings.

**Comment by MarkSummerville** [comment]
in 2.9.0

**Comment by rrrevin** [comment]
This works great BTW! Thanks!
