### ISSUE TITLE
BG Download is busy - try again in 10 seconds

### ISSUE THREAD

**Issue by laffer98** [TV-Rename/tvrename#646]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest [version
- [x ] I checked the userguide) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [x ] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [? ] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))
 - [? ] It is not a general question( these should be asked on the [support forum](https://groups.google.com/forum/#!forum/tvrename))

# Expected Behaviour

receive a token

# Current Behaviour
timing out
What is the current behaviour?

# Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
just starting the program
Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

Include whether it happens all the time or just sporadically. Also are there certain shows that it applies to?  What other investigation can/have you done?

## Context
all the time

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
windows 10 version 
[TVRename.log](https://github.com/TV-Rename/tvrename/files/3658179/TVRename.log)
latest updates
* Are you using the windows version or command line version?

## XML Files

Please include your XML files from your user directory here. Rename them to be txt files to load them here directly.
- See http://www.tvrename.com/technical#configuration-files for more information

## Log Files

Upload a log file here that is the log file that was present at the time of the error
 - See http://www.tvrename.com/technical#log-files for more information

## Error messages

Please inlcude the exact wording of any error messages that you have seen on screen or in the logs.

## Screenshots or videos of the issue

Please add any images or videos here. Use snipping tool or tinytake / bandicam For videos

**Comment by laffer98** [comment]
[TVRename.log](https://github.com/TV-Rename/tvrename/files/3658189/TVRename.log)

**Comment by laffer98** [comment]
Exception caught on attempt 1 of 3 to get https://api.thetvdb.com/login - will retry after delay 00:00:02: The operation has timed out

**Comment by laffer98** [comment]
[TVRename.log](https://github.com/TV-Rename/tvrename/files/3658209/TVRename.log)

**Comment by MarkSummerville** [comment]
I can't see anything wrong. Looks like a connectivity issue. 

Multiple 
2019-09-26 09:15:07|INFO| BG Download is busy - try again in 10 seconds 
lines 

Sometimes means that a popup box has appeared and popped under the main window and the user has not noticed it
