### ISSUE TITLE
Series folders are created although not needed. Add Option to deactivate.

### ISSUE THREAD

**Issue by AleXSR700** [TV-Rename/tvrename#647]
Hi everyone,
TV-Rename is really great but I feel like there should be an additional option or a code alteration for the "Add missing folders" option.
Right now it always adds all missing folders even if there are no shows to put into them.

Personally I would say it should only add the season folders if it has episodes it wants to put into them.

But if you deactivate the option it won't create the folder when needed. If you turn it on it will add the folders whether they are needed or not. Clearly this is either a broken code or an incomplete option.

I hope you agree and maybe it's an easy fix.

Thank you for your consideration.

**Comment by SirSparkles** [comment]
The easy parts of this are included in 2.9.9
