### ISSUE TITLE
Time Zone errors

### ISSUE THREAD

**Issue by mhurwood** [TV-Rename/tvrename#649]
I've noticed some errors in the log file for shows with Time Zones that are perfectly valid as far as the drop-down list of time zones is concerned, but which then don't get processed correctly, so there's some sort of mis-match going on I suspect.

The warnings in the log file are:

WARN Could not work out what timezone 'xxxx' has. In the settings it uses 'West Bank Gaza Standard Time', but that is not valid. Please update. Using the default timezone Eastern Standard Time for the show instead.

WARN Could not work out what timezone 'xxxx' has. In the settings it uses 'Jerusalem Standard Time', but that is not valid. Please update. Using the default timezone Eastern Standard Time for the show instead.

Obviously this is not necessarily an exhaustive list of problem time zones, just two that I have come across.  There may be more.

**Comment by SirSparkles** [comment]
Probably need to use https://codeofmatt.com/localized-time-zone-names-in-net/ to remedy
I'll take a look
