### ISSUE TITLE
Adding new shows finds "0 Episodes" and scanning doesn't show episodes for those shows

### ISSUE THREAD

**Issue by randomname42** [TV-Rename/tvrename#650]
All of a sudden today I can still add new shows, but always get 0 Episodes listed. This happened with all five shows I tried to add today.

Running a scan afterwards does not show any episodes for those shows, and there's no option to rename anything.

Add any show on the My Shows page and this happens.

Updating to 2.9.6 did not fix the issue.

**Comment by SAB3RX** [comment]
Same problem here.

**Comment by Chicob13** [comment]
Same issue here, and those shows aren't showing up in when to watch

**Comment by blamesociety** [comment]
Can confirm. I tried adding The Man in the High Castle and The Mandalorian and both show 0 seasons and 0 episodes.

**Comment by mhurwood** [comment]
This is a known problem. The fault is with TheTVDB, not with TVRename. Either they will fix it, or we'll have to work around it somehow.

**Comment by pipicanim** [comment]
Having the same issue the app is completely unusable as of yesterday.

**Comment by SirSparkles** [comment]
Seems to have been resolved for me

**Comment by AlexFielder** [comment]
This "Not downloaded, or not available" error is still an issue for me on version 2.9.7 - every time I start TV-Rename I get the above message on any recently added shows. Any ideas on how to fix (if it can be fixed at the app end)?
