### ISSUE TITLE
BulkAdd does not detect specific season name

### ISSUE THREAD

**Issue by poulpito** [TV-Rename/tvrename#651]
Hi,

I've try several things to help discover tv show using french (...nobody is perfect) season name 'Saison' 
add it in > 
-display Season Name parameter
-Library Folder Search items : Saison ;Saison; Season; (i've add one with blank ... in case) 
- Season folder format : Saison {Season:2}

Here are log : 
when renaming folder into "Season 1"to debug 
00:11:05 INFO Assuming XXXXXX contains a show because pattern 'Season {Season}' is found in subdirectory XXXXX\Season 1
00:11:05 INFO Adding XXXXXX as a new folder

when folder is "Saison 1": 
00:11:37 INFO Adding XXXXXX\saison 1 as a new folder   and appear in flat  in bulk add 

I've try to add saison lowercase  because i'm seing both upper and lower in log  but .... nothing 
I've also try using local folder to debug instead of windows mount  but i've the same behaviour. 

:)

**Comment by SirSparkles** [comment]
Try using 'Force to use Season Words from Settings only' option - that should help

**Comment by poulpito** [comment]
was also part of testing :(  no effect at all  
any chance this part of code was modify lately ?  
i was using tvrename a long time ago and everything was fine out of the box (a year back easy)

**Comment by SirSparkles** [comment]
I have just added a fix that should work in the way you expect (even if the settings override is not used), But you'll have to await the next version

**Comment by poulpito** [comment]
i'll have a look on next tag release :)  will update after upgrade 
hope it will solve !   anyway thanks \o

**Comment by poulpito** [comment]
quick note, compile TVrename myself and solution is working :) 
i'll wait official build   thanks again !
