### ISSUE TITLE
Language Portuguese-Brazil not find

### ISSUE THREAD

**Issue by alissongamer** [TV-Rename/tvrename#653]
Recently TVDB inserted the language option in Portuguese-Brazil, and I realized that in the last update of TV Rename there is already this language option, but when I download the information it does not find the language of Portuguese-Brazil and only low in English.

**Comment by SirSparkles** [comment]
DO you have an example series that has translations in Portuguese-Brazil on TVDB?

**Comment by SirSparkles** [comment]
OK - have raised: https://forums.thetvdb.com/viewtopic.php?f=17&t=60522

which explains why the series information is coming down in Portuguese and not Brazilian Portugese

**Comment by alissongamer** [comment]
> 
> 
> OK - have raised: https://forums.thetvdb.com/viewtopic.php?f=17&t=60522
> 
> which explains why the series information is coming down in Portuguese and not Brazilian Portugese

But will this be resolved?

**Comment by alissongamer** [comment]
No solution yet? Because it still doesn't work
