### ISSUE TITLE
Ignore "sample videos up to MB is size

### ISSUE THREAD

**Issue by Geneocide** [TV-Rename/tvrename#655]
I'm running 2.9.8 but when I change the 50 MB default to 70, it won't save after a restart of the app. It will use the setting immediately after closing the preferences, but when I close and reopen the app it's back to the 50 MB behavior.

Anyway, reproducing is quite simple. Start app. Open Preferences, change 50 MB to 70 MB (I haven't tried many other values). Close app. Restart App. Open Preferences. See that setting is back to 50 MB.

It might also be nice for it to be able to just ignore all files in a folder with certain names, perhaps "Sample" for example, as well as ignoring my file size.

**Comment by SirSparkles** [comment]
Good spot - will be fixed in the next version

To be clear, the function ignores a file if
  - The Checkbox for ignore samples is checked
  - The file contains 'sample' 
  - The file is less than the specified size
