### ISSUE TITLE
Since 3.0.1-rc5 : Right Click -> Edit Show in show list make app hang 

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#658]
All is say'd in title :)
Tracked back to AddEditShow.cs line 204 ... 
Why is language list not filled ?

**Comment by SirSparkles** [comment]
does it happen every time?

**Comment by Chlorel** [comment]
try this : suppress languages.xml ... run the app ... 1rst time all goes nice ... save and exit app, return in it ... then you get the error ... can be because the languages.xml is full filled with blanks like this : 

<?xml version="1.0" encoding="utf-8"?>
<Languages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Language />
  <Language />
  <Language />

**Comment by Chlorel** [comment]
?xml version="1.0" encoding="utf-8"?>
Languages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  Language />
  Language />
  Language />

**Comment by SirSparkles** [comment]
Does this still happen with the latest 3.0.2 RC?

**Comment by SirSparkles** [comment]
Should be fixed in rc7 if not

**Comment by Chlorel** [comment]
it happen's alway's ... the turn arround is to delete languages.xml ... so it run while first lauch after ... when saving stuff closing app ... and return to it later ... error is back :)

**Comment by Chlorel** [comment]
Upgraded to last stand, error gone, languages.xml file right filled now .. Thank's
