### ISSUE TITLE
Upgrading 2.9.9 to 3.0.2 RC 6 results in .net error

### ISSUE THREAD

**Issue by ezek1el** [TV-Rename/tvrename#659]
**Expected Behaviour**

Clicking the "Add" button should open the add new show window

**Current Behaviour**

**Error Message**
![2020-01-10_193336](https://user-images.githubusercontent.com/15878321/72176993-0b177900-33e0-11ea-8f71-96e2d4a16ccf.jpg)

[error_message_details.txt](https://github.com/TV-Rename/tvrename/files/4047342/error_message_details.txt)

**Steps to Reproduce**

1. upgrade from 2.9.9 to 3.0.2 RC 6
2. Click Add or Edit button
3. get error message

**Context**

* Operating System: Windows 8.1
* Are you using the windows version or command line version? Windows version

**XML Files**

[TVRenameSettings.txt](https://github.com/TV-Rename/tvrename/files/4047243/TVRenameSettings.txt)
[TheTVDB.txt](https://github.com/TV-Rename/tvrename/files/4047245/TheTVDB.txt)
[Statistics.txt](https://github.com/TV-Rename/tvrename/files/4047248/Statistics.txt)
[Layout.txt](https://github.com/TV-Rename/tvrename/files/4047249/Layout.txt)
[Languages.txt](https://github.com/TV-Rename/tvrename/files/4047382/Languages.txt)

**Comment by SirSparkles** [comment]
rc7 shoud fix these issues - sorry
