### ISSUE TITLE
Scan Full Create Missing Folder Dialog 

### ISSUE THREAD

**Issue by page2pagepro** [TV-Rename/tvrename#664]
Two issues.

1) Despite TVRenameSettings.xml `<LeadingZeroOnSeason>true</LeadingZeroOnSeason>`, the dialog creates Season 1-9 w/o zero-pad length 2. i.e.: "Season 04".

2) Dialog can become hidden behind parent window. It is findable in Task "Mangler" but would be more useful if either taskbar showed dialog or when parent is selected child window surfaces.

Keep up the hard work on a fantastic tool!

**Comment by SirSparkles** [comment]
For 1) 
What is the configuration for the show? The show's configuration will be used to define the folder structure. You can set the default structure for a show too in settings: (Season's folder format = Season {Season:2})

2. I'll take a look at the way the window is setup to make sure it's in the front

**Comment by SirSparkles** [comment]
@page2pagepro How does 3.1 look? We have modified the way that the dialogs appear

**Comment by SirSparkles** [comment]
Changes have been made - let us know if they have not resolved it and we can open another bug
