### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by LordFader** [TV-Rename/tvrename#673]
![image](https://user-images.githubusercontent.com/4002168/73143570-ade41e80-4093-11ea-87ab-225c00145827.png)

**Comment by eentje** [comment]
same issue for me

**Comment by DesigningKnights** [comment]
Same here too, same trojan detected.

**Comment by SirSparkles** [comment]
Which virus scanner are you guys using? No issue for me

**Comment by DesigningKnights** [comment]
Windows Defender,  says Trojan:Win32/Detplock, just like the image that LordFader posted

**Comment by SirSparkles** [comment]
https://www.virustotal.com/gui/url/33caf549d41186422887f1170a6bd3184474b1525737d0d31297873be7b164a8/detection

gives it a clean rating

will check into windows defender now

**Comment by SirSparkles** [comment]
What version of update are you on? I'm on 1.307.3079.0 downloaded today

**Comment by DesigningKnights** [comment]
i'm on 1.307.3082.0, downloaded a few minutes ago, and same issue.  same trojan detected.

**Comment by SirSparkles** [comment]
Is it detecting it in the installer? or the file produced after installation?

**Comment by SirSparkles** [comment]
![image](https://user-images.githubusercontent.com/14905881/73168410-b8a2c000-4134-11ea-9196-9e071fe13514.png)

MS have rescanned and updated the definitions - let me know if that made any difference to you (with the latest definitions)

**Comment by eentje** [comment]
I updated to Windows Defender Antivirus - KB2267602 (version 1.307.3109.0) and i dont get a threat warming any more. Thx for the fast response SirSparkles and for the great program.

**Comment by SirSparkles** [comment]
Happy to close this one? @LordFader

**Comment by rrrevin** [comment]
3.1.0 installer comes up with 3 positives using VirusTotal.
Results here: https://www.virustotal.com/gui/file/950f8e1fdd64d85319dae468b894936c840da71c44cd89a6d68a60e4cd88ba32/detection

OPSWAT comes back clean :)
https://metadefender.opswat.com/results#!/file/f6a1119d516627345bf8d318502a3b64/hash/overview

**Comment by SirSparkles** [comment]
Closing as seems to be a false positive
