### ISSUE TITLE
More control over My Shows tree display (colours, groups)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#7]
```
* Separate continuing and ended shows
http://tvrename.com/bb/viewtopic.php?f=4&t=505
* Other ways to group shows?
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:02

**Comment by MarkSummerville** [comment]
Really this is:
 * expanding colouring to seasons: complete/ignored/complete so far
 * new option to hide ignored seasons - maybe part of the filter function

**Comment by MarkSummerville** [comment]
Putting the completeness of the season would slow down the UI too much

Will do those changes in the 'Show Summary' View

**Comment by MarkSummerville** [comment]
Covering off "expanding colouring to seasons: complete/ignored/complete so far" in #438. Closing this one
