### ISSUE TITLE
Add The MOvie DB TV Series API

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#712]
https://developers.themoviedb.org/4/list/get-list

**Comment by SirSparkles** [comment]
Also possibly a slim down version on https://www.episodate.com/api

**Comment by 1024mb** [comment]
I second the request for TheMovieDB.

**Comment by SirSparkles** [comment]
Tracked in 
http://ideas.theideawall.com/TVRename/Forum/TopicDetails/469af65a-d650-4062-9f08-527fb7968774
and
http://ideas.theideawall.com/TVRename/Forum/TopicDetails/00db34b0-9bc6-4a14-a958-64d441839e5f?fb=0 

closing here
