### ISSUE TITLE
Add / Remove colums

### ISSUE THREAD

**Issue by paoloalby** [TV-Rename/tvrename#714]
Is there any way to add/remove column in the Scan panel?

Now I have Show, Season, Episode, Folder, Filename and Source columns.
My friend has Date and doesn't have Source column.

We both have the latest version. How can we show/hide colums in Scan window?

**Comment by SirSparkles** [comment]
Just by dragging them to 0 size. They are all always there but may have 0 width.

**Comment by SirSparkles** [comment]
@paoloalby Has that fixed it?
