### ISSUE TITLE
Full Path checkbox in FileName Processor does not seem to work

### ISSUE THREAD

**Issue by AndrewSav** [TV-Rename/tvrename#721]
# Expected Behaviour

I expect Full Path to be processes when "Full Path" checkbox is checked.

# Current Behaviour

Full Path is not processed

# Failure Information

Cannot match anything in the full path, E.g. `season (?<s>[0-9]+)\\episode (?<e>[0-9]{1,3})` does not match. 

Stepping through the code reveals that the code path goes via [this line](https://github.com/TV-Rename/tvrename/blob/19942a877b9a046030e50b487aec883a4685f978/TVRename/Finders/FinderHelper.cs#L41) which, in turn causes the path evaluate to empty string,

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. End up on the FileName Processor with your test folder path containing "Season 03"
2. Check Full Path and try to match on `Season (?<s>[0-9]+)`
3. Observer that it is not matched

>Include whether it happens all the time or just sporadically. 

All the time

>Also are there certain shows that it applies to?  

Have not tested, but I cannot see why it should be applied to only certain shows.

>What other investigation can/have you done?

Stepped through the code in the debugger, and observed that path root is evaluated to empty string in the regex checks.
The issues seems to be only on the FileName Processor form. The scan itself seems to work fine - if you manage to get your regexp right flying blind.

## Context

* Operating System: `Win 10`
* Are you using the windows version or command line version? - `Windows`

## XML Files

Please include your XML files from your user directory here. Rename them to be txt files to load them here directly.
- See http://www.tvrename.com/technical#configuration-files for more information

`http://www.tvrename.com/technical#configuration-files` gives 404.

## Log Files

Upload a log file here that is the log file that was present at the time of the error
 - See http://www.tvrename.com/technical#log-files for more information

`http://www.tvrename.com/technical#log-files` also gives 404
## Error messages

Please inlcude the exact wording of any error messages that you have seen on screen or in the logs.

No error messages.

## Screenshots or videos of the issue

![image](https://user-images.githubusercontent.com/658865/80781758-b33b9280-8bc7-11ea-8236-5d02dc7507d1.png)

![image](https://user-images.githubusercontent.com/658865/80781764-b8004680-8bc7-11ea-86fc-67bc64a2cdcb.png)

**Comment by SirSparkles** [comment]
In fact, the issue was that the full path was *always* being used. If you set the breakpoint on the same line then the itemName variable includes the full path.

Now fixed

**Comment by AndrewSav** [comment]
It's working now, thanks.
