### ISSUE TITLE
Filename Processor rules seem to interact with each other in unintended manner

### ISSUE THREAD

**Issue by AndrewSav** [TV-Rename/tvrename#722]
If we get this one rule:
![image](https://user-images.githubusercontent.com/658865/80783652-90f94300-8bce-11ea-80e5-422c2bc2f24e.png)
It results in this scan (as expected, all matches):
![image](https://user-images.githubusercontent.com/658865/80783682-9fdff580-8bce-11ea-93f3-aa3259b524ae.png)
If we get this one rule:
![image](https://user-images.githubusercontent.com/658865/80783701-ae2e1180-8bce-11ea-9562-16b24f42dc6e.png)
It results in this scan (as expected, no matches):
![image](https://user-images.githubusercontent.com/658865/80783715-bbe39700-8bce-11ea-9856-f31115be5028.png)
When we have these two rules combined though like this:
![image](https://user-images.githubusercontent.com/658865/80783732-c69e2c00-8bce-11ea-850e-33014c50cdd2.png)
Suddenly three files do not match and the rest matches alright:
![image](https://user-images.githubusercontent.com/658865/80783751-d6b60b80-8bce-11ea-848f-a6e1c510635c.png)

The files that did not match are:

"Total Drama World Tour - Episode 19 - Niagara Brawls-8CkDpXeGzWk.mkv" 
"Total Drama World Tour - Episode 20 - Chinese Fake-Out-6dgKTKdBZIM.mkv" 
"Total Drama World Tour - Episode 25 - Planes, Trains and Hot Air Mobiles-6Pep2PEAyg4.mkv"

**Comment by SirSparkles** [comment]
What does it say in the log at his time?

Also - Is there anything in the 'Errors' column to the right on the scan results?

**Comment by SirSparkles** [comment]
Also try pointing the 'Filename Processor' screen to the directory with these 3 files in

**Comment by AndrewSav** [comment]
Errors column is empty. Where do I find the log?
'Filename Processor' screen does not find anything due to [the other issue](https://github.com/TV-Rename/tvrename/issues/721) I filed today. 
E.g

![image](https://user-images.githubusercontent.com/658865/80789027-eccbc800-8bde-11ea-8144-118d95a1a5e0.png)


What else would you like me to check?

**Comment by SirSparkles** [comment]
https://www.tvrename.com/manual/technical/#log-files

**Comment by SirSparkles** [comment]
Taking 
Total Drama World Tour - Episode 19 - Niagara Brawls-8CkDpXeGzWk.mkv
as an example:
\b(?<e>[0-9]{2,}) ?- ?.* ?- ?(?<s>[0-9]+)
is above the other regexs

so system recognises the ep as S08E09 which is not needed
![image](https://user-images.githubusercontent.com/14905881/80812122-e72fab80-8bf9-11ea-91ef-15dcf56b5293.png)

The other files maybe do not have a digit as their first character in the last part of the filename? So they do not get recognised by that Regex and vall through to the lower one that you have enabled. The lower one matches them correctly.

Try shifting Regex up and down and using the preview window at the bottom

**Comment by AndrewSav** [comment]
Right, with the preview panel [fixed](https://github.com/TV-Rename/tvrename/issues/721#issuecomment-622373717), this is much clearer now.

Still I'm wondering, would it be worth changing behaviour so that if it matches a non-existent episode _and_ existing episode, existing takes preferences? May be as an option?

I can see that otherwise, these not-matching matches can be a surprise. I'll leave this up to you, if you disagree, feel free to close the issue.

**Comment by SirSparkles** [comment]
I worry that changing it will lead to other other edge cases that produce unexpected results. We had it working in a similar way before and there was a preference to change it to the current more conservative approach (with a strict hierarchy of RegEx)

Maybe add it to the Ideas Wall [here](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0) to see if others would like that change too
