### ISSUE TITLE
Scan dialog box steals focus

### ISSUE THREAD

**Issue by mejico** [TV-Rename/tvrename#726]
Windows 7 x64.  Whenever the app runs a scan the popup window steals focus.   I now know this also happens in Win 10 x64.  The dialogue box is titled 'Download Progress'.

**Comment by SirSparkles** [comment]
Will be adjusted next version - thanks for bringing up

https://github.com/TV-Rename/tvrename/commit/4661572674aa6cd3d85f73d01e790e54c690c4f9

**Comment by mejico** [comment]
No worries.  Thanks for the help.
