### ISSUE TITLE
Can no longer "select" an item anywhere on the line..

### ISSUE THREAD

**Issue by rrrevin** [TV-Rename/tvrename#728]
Just upgraded to 3.2.0. I can no longer select/deselect an item (enable/disable the checkmark square at the start of the line) by double clicking anywhere on the line. With this version, I can only select/deselect by clicking the square. Is this new?

**Comment by SirSparkles** [comment]
Probably. We changed out the grid control to allow grouping and filtering. This was an unintended side effect

**Comment by rrrevin** [comment]
Any chance it can be put back in without undoing the new features?

**Comment by SirSparkles** [comment]
Yeah - can be reenabled. Was it double click only?

**Comment by SirSparkles** [comment]
Fixed in 3.2.1
