### ISSUE TITLE
V3.2.1 - Bulk add shows causes program to hang

### ISSUE THREAD

**Issue by KeiraenW** [TV-Rename/tvrename#729]
# Expected Behaviour

After pressing Tools-->Bulk Add show, and then Check, I should get a progress bar and the newly found shows will be listed

# Current Behaviour

After pressing Tools-->Bulk Add show, and then Check, the program hangs and I have to kill it with the task manager

# Failure Information

No log details for the crash

## Steps to Reproduce

1. Go to Tools-->Bulk Add show, and then Check

Currently affecting 100% of the tries on this version

## Context

Tried several things
changed locations for bulk add scan to 1, then to another 1, still both crash
Changed reinstalling and restarting, changed to open the program as admin, still crashes
regular scanning does work.

* Operating System: Win 10 64
Windows version 3.2.1 (latest)

## XML Files

Please include your XML files from your user directory here. Rename them to be txt files to load them here directly.
- See http://www.tvrename.com/technical#configuration-files for more information
This link is broken

## Log Files

Upload a log file here that is the log file that was present at the time of the error
 - See http://www.tvrename.com/technical#log-files for more information
This link is broken

## Error messages

No messages in the logs, no errors on screen

**Comment by SirSparkles** [comment]
Thanks - will be fixed in 3.2.2
