### ISSUE TITLE
TV Rename is now using Filename Replacements on Season folders

### ISSUE THREAD

**Issue by DaveRaps** [TV-Rename/tvrename#731]
Functionality in software has changed, it now uses Filename Replacements to change the name of the Season folders.

For example, I have Season folders set to be named like Season 00, but because I use a Filename replacement to replace Spaces with Period, it now renamed all my Season folders to Season.00 and moved files there.

Filename Replacements options should not be active on Season folders.

**Comment by SirSparkles** [comment]
Which version did this change during?

**Comment by DaveRaps** [comment]
I wasn’t completely up to date, so it happened for me upon updating to the latest version 3.2.3.
