### ISSUE TITLE
Make Finders respect 'no rename' checks

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#733]

**Comment by nfearnley** [comment]
I believe this may have broken existing functionality. My shows no longer rename anything, only move the files between folders.

**Comment by SirSparkles** [comment]
For a show that is in your library (and it is not renaming), can you please check whether the show has 'Do Renaming' checked (Edit Show -> Advanced -> Do Renaming) and whether the overall configuration is set to rename? (options -> Preferences -> Scan Settings -> Rename Check)

**Comment by SirSparkles** [comment]
@nfearnley I have done a few tests and it seems to be working as expected for me.

**Comment by SirSparkles** [comment]
Seems that others had this problem too: https://groups.google.com/forum/m/#!topic/tvrename/VxMBx69tr4Y

But all resolved once settings were adjusted 

Feel free to reopen if these settings do not fix the problem.
