### ISSUE TITLE
Virus report on installer of 3.2.9

### ISSUE THREAD

**Issue by DesigningKnights** [TV-Rename/tvrename#745]
![Annotation 2020-06-25 091732](https://user-images.githubusercontent.com/8666549/85759014-ad44c800-b6c5-11ea-9c4b-52d13fbf16b3.jpg)

**Comment by SirSparkles** [comment]
Unfortunately there seems to be something about the code that reports false-positives:

See:
https://groups.google.com/forum/#!searchin/tvrename/virus%7Csort:date/tvrename/63zGRyABZTE/rHh7wbxtFAAJ
or
https://groups.google.com/forum/#!searchin/tvrename/virus%7Csort:date/tvrename/SzvSJkiPqDg/DjOzNYlmDQAJ

for prior false alarms:

https://www.virustotal.com/gui/url-analysis/u-ee171053f4b6fa6bbbd5205181e88127a0b33a704ec1c161c3e8b9bfb7eea839-1593142417/detection
or
https://www.virustotal.com/gui/file/0a8306aa8ed19b9a4b1559abb13c435ebbe3b07eab90e74f8455500d05984cd6/detection

Which app are you using to get a warning?

**Comment by SirSparkles** [comment]
Also see
https://metadefender.opswat.com/results/file/bzIwMDYyNm8tN1kwbkduazdMdmV2VzN3ZmxT/regular/multiscan?lang=en

**Comment by DesigningKnights** [comment]
It was Windows 10 Defender. I just ignored the warning and let it install.

**Comment by SirSparkles** [comment]
I have requested a review via https://www.microsoft.com/en-us/wdsi/filesubmission
WIll report back the findings when they come through

**Comment by SirSparkles** [comment]
![image](https://user-images.githubusercontent.com/14905881/85913456-a655bb00-b867-11ea-9b9e-121ec561af19.png)

**Comment by SirSparkles** [comment]
![image](https://user-images.githubusercontent.com/14905881/85916676-afee1b80-b885-11ea-93fa-f6dc4393103e.png)

**Comment by SirSparkles** [comment]
Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.
