### ISSUE TITLE
No more access to mapped network drives or network computers ?

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#769]
Since i upgraded to 4 alpha 3 i dont have access to my mapped network drive, and no access to shared computers too ( to try to access there shared drives ) some hints to solve this ? 

Note since upgraded .. i dont have any access to my show collection too ... the collection is on 2 network mapped drives

**Comment by SirSparkles** [comment]
Close and reopen.  Will be an issue with permissions on the account vs the account the installer has run with
