### ISSUE TITLE
No window!

### ISSUE THREAD

**Issue by soarn** [TV-Rename/tvrename#770]
- [x] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [x] I checked the [documentation](https://www.tvrename.com/manual/user/) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [x] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [x] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))
 - [x] It is not a general question( these should be asked on the [support forum](https://groups.google.com/forum/#!forum/tvrename))

# Bug Details

**Describe the bug**

The window will just not show after the initial launcher (no splash screen).

**Expected Behaviour**

The application launches successfully and I am able to interact with the user interface.

**Current Behavior**

The program will sit in my taskbar and no amounts of clicking on it will produce an on-screen, observable window.

**To Reproduce**

1. Be on Windows 10
2. Launch TV Rename
3. Suffer.

**Context**

I'm working on reorganizing my Movies and TV show, so I went to open up TV-Rename and it said there was an update, I updated (latest stable) and the program will now no longer function.

* Operating System: Windows 10 Home Version 20H2
* Are you using the windows version or command line version: Windows Version

**Additional context**

The only Windows installation changes that I have made since the last time I used TV Rename was disabling Driver Security Enforcement (This is now mandatory for me due to my drivers getting 'effed up and leaving me with no working peripherals on boot with Driver Security Enforcement.)

I have uninstalled the stable and am now on the latest pre-release in an attempt to fix this, so far is seems no version works, not even the previous version that I was on (most likely the second to last stable release.)  I have uninstalled both saving and deleting data and preformed multiple restarts however nothing has aided me and TV Rename continues to not display a window.

## XML Files

[Languages.txt](https://github.com/TV-Rename/tvrename/files/5846768/Languages.txt)
[Layout.txt](https://github.com/TV-Rename/tvrename/files/5846769/Layout.txt)
[State.txt](https://github.com/TV-Rename/tvrename/files/5846770/State.txt)
[Statistics.txt](https://github.com/TV-Rename/tvrename/files/5846771/Statistics.txt)
[TheTVDB.txt](https://github.com/TV-Rename/tvrename/files/5846772/TheTVDB.txt)
[TMDB.txt](https://github.com/TV-Rename/tvrename/files/5846773/TMDB.txt)
[TVmaze.txt](https://github.com/TV-Rename/tvrename/files/5846774/TVmaze.txt)

## Log Files

Included is my current log as well as all archived versions.
[TVRename.log](https://github.com/TV-Rename/tvrename/files/5846829/TVRename.log)

[TVRename.00.log](https://github.com/TV-Rename/tvrename/files/5846831/TVRename.00.log)
[TVRename.01.log](https://github.com/TV-Rename/tvrename/files/5846832/TVRename.01.log)
[TVRename.02.log](https://github.com/TV-Rename/tvrename/files/5846833/TVRename.02.log)
[TVRename.03.log](https://github.com/TV-Rename/tvrename/files/5846834/TVRename.03.log)
[TVRename.04.log](https://github.com/TV-Rename/tvrename/files/5846835/TVRename.04.log)
[TVRename.05.log](https://github.com/TV-Rename/tvrename/files/5846836/TVRename.05.log)
[TVRename.06.log](https://github.com/TV-Rename/tvrename/files/5846837/TVRename.06.log)

## Error messages

No errors have been thrown.  

## Screenshots or videos of the issue

![6i9mgq](https://user-images.githubusercontent.com/11000195/105279654-44db9d80-5b65-11eb-8753-8613265ac318.gif)

(Sorry, didn't mean to record discord in the process.)

**Comment by SirSparkles** [comment]
Try copying  the TVDB, TVMaze and TMDB files out and let TVR Reproduce them. Make sure the old instance is killed off. 

Do you have a Settings.xml file? TVRenameSettings.xml - can't see one added above

Then:
1. close all TVR instances (fored if needed)
2. Rename 2.1 directory to 2.1.old (where the settings are). It will recreate all that it needs  in a new 2.1 folder. 
3. Then Close it. Make sure it is completely shutdown and then recopy your saved TVRenameSettings.xml file over the top of the one its just created. (ie from 2.1.old to 2.1)

Then let me know if there is anything intersting in the log file

**Comment by soarn** [comment]
I've tried doing all this previously, letting it regenerate the files, and all that.  But still not change.

> Do you have a Settings.xml file? TVRenameSettings.xml - can't see one added above

As for settings, one does not get generated, it might be because I never get to a user interface or anything.  If possible, could you attach the default settings xml and I'll add it in there and see if it fixes it?

**Comment by soarn** [comment]
I know this is project is all done by a single dev, and I thank you for that, but I'm happy to help with any bug testing or anything with this issue.  I also ran TV Rename in a [Sandboxie](https://github.com/sandboxie-plus/sandboxie) Sandbox and still encountered the same issue.

**Comment by soarn** [comment]
I installed 3.2.0 to a separate directory to try to see if an older version would work, it did not.  However it did give me the popup asking if I wanted to update to the latest version, but other than that I encountered the same problem of not having any display window whatsoever.  Later today I can restart my PC with Driver Security Enforcement enabled and use VNC to open up TV Rename and see if the window appears or not.

**Comment by soarn** [comment]
![image](https://user-images.githubusercontent.com/11000195/105521342-fd562e00-5c98-11eb-84e9-36b6024575ef.png)
Okay this might be promising... (I got 3.2.0 to run in Sandboxie)

**Comment by soarn** [comment]
Alright man, I got no idea what voodoo magic you did to me, but it's working even when non-sandboxed.  I'll keep checking and see if it breaks again.

In other news, your latest Alpha release didn't include an executable, no idea if that was intentional or not.
