### ISSUE TITLE
Discrepancy between thetvdb.com and TV Rename episode numbers/names

### ISSUE THREAD

**Issue by Ruthalas** [TV-Rename/tvrename#771]
# Bug Details

**Describe the bug**
Some shows show a different episode count and names than their thetvdb.com pages.
Ex: [Oreimo](https://www.thetvdb.com/series/oreimo) season 1 shows 16 episodes on thetvdb.com, but only 12 episodes in the TV Rename interface.
Ex: [The New Adventures of Winnie the Pooh](https://www.thetvdb.com/series/the-new-adventures-of-winnie-the-pooh) season 1 has the same number of episodes, but the episode order/naming is different between thetvdb and TV Rename.

**Expected Behaviour**
Episodes should match the web page on thetvdb for that show/season.

**Current Behaviour**
Episodes are different in the show page in TV Rename and the thetvdb.com page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Name episodes of one of the shows listed above according to thetvdb.com
3. Run Full Scan
4. See discrepancies between the naming

Happens consistently with these two shows.
I confirmed that 'DVD Order' is Unchecked.

* Operating System:
Windows 10, GUI version

## Screenshots or videos of the issue

![image](https://user-images.githubusercontent.com/27835519/108619520-542c6000-741d-11eb-8bde-ce76bf9adf34.png)

**Comment by SirSparkles** [comment]
Does a 'force refresh' on the show fix the issue? Sometimes the TVDB API does not alert us of a change to a show and we need to manually refresh.

**Comment by Ruthalas** [comment]
That resolved both issues. Thank you very much!
