### ISSUE TITLE
Refresh button not working

### ISSUE THREAD

**Issue by LarryGT** [TV-Rename/tvrename#777]
I am testing version 4.1.7.
The Refresh button ist not working. When i click the button nothing happens. I looked at the logfile and there is nothing.
I also clicked on the menu Force Refresh All. After this i clicked on the Refresh button, but nothing happens.
I noticed this also on the previous alpha version.

**Comment by SirSparkles** [comment]
Both seem OK on my system. Neither intend to leave any logging.

Refresh just updates the User Interface 

Have you tried 'background download now'?

**Comment by LarryGT** [comment]
Background download now starts the download.
Why was this changed. In TVRename Versions 3.x clicking on the Refresh button starts the download.
