### ISSUE TITLE
Trying to set Ignore Specials for each of my TV Shows (except one show = "Mars") resulted in this final Saving error...

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#787]
On alpha 23, trying to set Ignore Specials for each of my TV Shows (except one show = "Mars") resulted in this final Saving error...

Plz see screenshot here: https://imgur.com/BEQwxJR

Probably means more to you than me, lol

Plz can u fix when able? thx

**Comment by SAH7777** [comment]
PS: At the same time as trying the above, I think (if I remember correctly) that I also unticked "Rename Check" for the Scan Settings -> so the problem could be because of that instead, just FYI

**Comment by SirSparkles** [comment]
I’ll get it fixed, but try making sure that the tvdb and tmdb regions and languages are set (under data sources)
