### ISSUE TITLE
Major dpi scaling bugs in alpha 25

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#789]
Hi,

I can see partially what you're doing right now in the latest alphas, making TV Rename better handle different Win 10 DPI scaling settings -> which will make TV Rename's text look nice and crisp on high DPI screens etc.

And The final result will be great!! thx :)

but right now, in alpha 25 (which i just installed) it's Wahhhh messed up for me, plz see screenshot here: https://imgur.com/pcFnhf7

i'm at Win 10 dpi scaling = 225% (I'm sitting back from a large 4K screen)

I'll have to rollback to alpha 24 or 23 for now

Plz can you fix for 225% when you're able?, thx!

**Comment by SirSparkles** [comment]
Yeah - I tried to do a quick fix to get it to work, but clearly made it worse. I'll revert the change I made in v25 and address it properly in a future release

**Comment by SirSparkles** [comment]
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

**Comment by SirSparkles** [comment]
These settings may help in the meantime https://groups.google.com/g/tvrename/c/LV47f_md73I

**Comment by SAH7777** [comment]
> These settings may help in the meantime https://groups.google.com/g/tvrename/c/LV47f_md73I

thx but ur commenting out of "Cef.EnableHighDPISupport();" already fixed (restored TV Rename to original slightly blurry text state) for me, thx

**Comment by SirSparkles** [comment]
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8#configuring-your-windows-forms-app-for-high-dpi-support

**Comment by SirSparkles** [comment]
Can I close this? I think the latest versions solve this problem overall. If there are still issues, can they be raised as separate issues please? #914 are the known issues right now
