### ISSUE TITLE
several bugs in alpha 27

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#792]
plz see annotated screenshot here: https://imgur.com/8k3Bhwd

ps: i'm on win 10 with dpi scaling at 225% (for a htpc)

**Comment by SirSparkles** [comment]
'&' issue should be resolved in Alpha 31

DPI changes are some way off, sorry

**Comment by SirSparkles** [comment]
Closing this as DPI issues tracked in #789

**Comment by SAH7777** [comment]
> DPI changes are some way off, sorry

no worries, and looking 4ward to more crispy text when u have time to implement, thx!
