### ISSUE TITLE
Delay moving of files from download folder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#8]
```
Don't move 'new' files from download folder, until they've been there for a
set amount of time. http://tvrename.com/bb/viewtopic.php?f=4&t=497

This would be an option, defaulting to off (i.e. move immediately).

Useful for people who expect new shows to be in a particular place, or want
to allow time for them to be seeded.

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:04

**Comment by MarkSummerville** [comment]
Link is now http://old.tvrename.com/bbold/4/t-497.html

Also raised on http://ideas.theideawall.com/TVRename/Forum/TopicDetails/754ac8bc-172b-43d4-8a54-8b8fca9b81d8?fb=0

Closing until we may work on it
