### ISSUE TITLE
u doing ok? ep details window/pane is still mucked for me

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#804]
dude, u doing ok, still active and well and willing/wanna keep working on tv rename for us end-users?

just haven't had any alpha updates in a while, and in a33 the ep details window/pane is still mucked for me due to win 10 dpi scaling = on (i'm at 225% in win 10 settings)

plz see here (especially re alignment of the panes): https://imgur.com/CbxyNpR

thx!

**Comment by SirSparkles** [comment]
a34 better?

**Comment by SAH7777** [comment]
hey, good 2 hear from u.

na, unfortunately a34 looks the same (see previous screenshot link, thx), but it's only the Information tab for TV Shows that's messed-up

The Images, Summary & Trailer tabs all look fine

**Comment by SirSparkles** [comment]
DPI scaling bugs are tracked in #789. Is there any other issue being tracked here? If not then can it be closed?

**Comment by SAH7777** [comment]
i think they are kinda different cases

the one here is about the look of the TV Show **Information** window/pane/tab/mini-web-page-in-a-frame-thing

the other issue #789 is kinda about the scaling/look of the text all over the place

i think, thx

**Comment by SAH7777** [comment]
plz compare the screenshot links in both posts/issues, thx!

**Comment by SirSparkles** [comment]
Can you try https://github.com/TV-Rename/tvrename/releases/tag/4.6.3 please?

Main view will be broken, but go into Beta mode and try Beta -> Web Test and Beta -> Download installer

**Comment by SAH7777** [comment]
> Can you try https://github.com/TV-Rename/tvrename/releases/tag/4.6.3 please?
> 
> Main view will be broken, but go into Beta mode and try Beta -> Web Test and Beta -> Download installer

I tried it but it's worse, here is a screenshot... you will see things are misshapen and I can't even see my tree of TV Shows anymore:

https://imgur.com/e8DoQ2w
https://imgur.com/k8GHxwj

**Comment by SAH7777** [comment]
Also here: https://imgur.com/nT6ZevR

**Comment by SirSparkles** [comment]
@SAH7777 WHen you click on Beta ->WebTest you should get a window popup with 2 info panes on it. They use different components, so am interested to see whether they fix the offset problem. Can you take a look with 4.6.6 please? If they don't appear, can you take a look in the logs to see whether an issue is occuring please?

**Comment by SAH7777** [comment]
Ok i can test with 4.6.6 later on today but might take me a few hours (up to 10h) because I've gotta do some other things first and also my internet download speed is on the go-slow

Re logs, you mean this thing (https://www.tvrename.com/_manual/technical/log-files/), right?

**Comment by SirSparkles** [comment]
yah - they are the logs. Generally tell you what's going on inside.

I use https://www.baremetalsoft.com/baretail/ to keep on eye on them in real time

**Comment by SAH7777** [comment]
I found some time to test.

**You fixed it!** (mostly).

To recap, I'm on a standard high-DPI display, this one in fact: https://www.scorptec.com.au/product/monitors/25plus-inch/85135-438p1

It's running at 4K res (3840x2160) with my Win 10 DPI-scaling-%-setting = 225% (not simply 200%).

Here is my TV Rename 4.6.6 testing video, wherein I've turned OFF all "High DPI scaling override" settings for the TV Rename .exe, AND **I wiggle my mouse cursor over any remaining problems** I think I see: https://gofile.io/d/26lJBo

PS: Because I am NOT a Pirate, and buy all my TV Shows per Season (or as Complete Show Box Sets on sale)... the TV Rename TV Show Summary grid feature is really good and useful for me. I just wish it wasn't buried under Menus and had its own big access button/area like Scan and Schedule do.

Thanks again

**Comment by SAH7777** [comment]
I should also add that I use **TMDB** as the "Source" for all my shows in TV Rename

So that could by why the episode still-frame images aren't showing up?

**Comment by SAH7777** [comment]
I restarted 4.6.6 and episode still-frame images are now yes showing up ok... strange, but good to see them working now, thx!

**Comment by SirSparkles** [comment]
OK - great. Thanks very much for taking the time to produce the video. I will close this and open up and refer to #914 for the residual issues. Feel free to add others as specific issues are noted
