### ISSUE TITLE
TV Show Summary right-click season > Ignore Season... isn't auto-saved/remembered

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#806]
1. Use TV Show Summary right-click season > Ignore Season
2. Close TV Rename (with Autosave setting on in settings)
3. Ignored Season **isn't remembered**

Please can you fix when you can?
Thanks muchly!

**Comment by SirSparkles** [comment]
Which version - seems OK for me in latest betas?

Is season marked as ignored before you close TV Rename? (edit show and look at ignored seasons)

**Comment by SAH7777** [comment]
hi,

i tried on alpha 34

yes the seasons (was Specials seasons) became gray colored in TV Show Summary window AND Edit Show showed Ignored Seasons: 0

but when close TV Rename (with auto-save option on)... and when relaunch... the Specials seasons weren't ignored (updated setting not remembered)

**Comment by SAH7777** [comment]
maybe u need to re-try/re-test with Specials seasons?

**Comment by SirSparkles** [comment]
Have retried with specials - works fine for me. 

Can you see any issues in the log? Possibly problem saving TVRenameSettings.xml

Try opening up the TVRenameSettings.xml file, search for the show in question and see whether the <IgnoreSeasons> includes 0 for that show (0 indicates 'Specials' season)

**Comment by SAH7777** [comment]
yeah it's a problem in auto saving TV Rename's Settings

The xml wouldn't auto save/update (when TV Rename closed) with the latest "TV Show Summary right-click Special > Ignore Season" change

if u can't reproduce, then don't worry about too much, because from the Main TV Show section (not TV Show Summary) i was able to ignore all Specials and have the changes saved automatically by TV Rename on TV Rename close

thx!

**Comment by SirSparkles** [comment]
Just tested again and works fine for me. Closing for now (happy to reopen if others can reproduce)
