### ISSUE TITLE
Can't check boxes to rename

### ISSUE THREAD

**Issue by mjcorriere** [TV-Rename/tvrename#810]
Fresh install of TV Rename 3.3.1. After doing a full scan it finds all of the TV shows I would like to rename. I have two problems:

1. There is no "check all" option. There are hundreds of files to rename.
2. I can't even individually check any of the items. The box highlights blue when I mouse-over, but clicking does nothing

**Comment by SirSparkles** [comment]
Try 4.4.2.

There is a "check all": In the menu bar, There is a 'Check' option, selecting that submenu allows you to select the types of actions you want to check.

If there is a large number of actions, TV Rename does not check them automatically - just in case there is an error. (for small numbers then the actions are pre-checked)

You will not be able to check 'missing' items. They are just reporting that files are missing and there is nothing TVR can do about those

Try scanning just one TV show - may make the situation clearer. If you are still having problems then take a look in the log and send some screenshots over and we can take a look.

**Comment by mjcorriere** [comment]
Just to confirm, the list was showing me all of the _missing items_. It was particularly confusing because I know I had the files, but they were all slightly misnamed.

Perhaps a suggestion to more clearly indicate that the files are missing? It wasn't immediately obvious to me. 

Thanks!

**Comment by SirSparkles** [comment]
You can always drag the correct file over the missing one  (if that helps)
