### ISSUE TITLE
URI for 4.4.9 update pushed to in-app updater returns 404

### ISSUE THREAD

**Issue by segin** [TV-Rename/tvrename#839]
# Bug Details

**Describe the bug**
Update exe URI is 404

**Expected Behaviour**

TVRename-4.4.9.exe downloads

**What is the current behaviour?**

URI returns 404

**To Reproduce**
Steps to reproduce the behaviour:
1. Wait for Update dialog to appear upon launch 
OR 
1. Choose "Check for updates" from menu
2. Select "Update" or "Update and Exit"
3. Wait for browser to open to the installer executable URI provided by TVRename

**Context**

Windows 10 20H1, 64-bit. TVRename 4.4.8. 

## XML Files

N/A, occurs without regard of configuration

## Log Files

N/A, because the error occurs in the browser.

## Error messages

404 Not Found

## Screenshots or videos of the issue

![image](https://user-images.githubusercontent.com/480709/142135428-3ba513e6-8837-44ad-a9ea-2328ea8ada32.png)

**Comment by SirSparkles** [comment]
Should be fine now
