### ISSUE TITLE
RSS Search Always Happening

### ISSUE THREAD

**Issue by ChrisMTheMan** [TV-Rename/tvrename#840]
RSS search always fires no matter what RSS search setting is used.  I removed all RSS feeds and unchecked all RSS search settings, no help.  I went into the config file and found the RSS Search setting still set to true.  I changed it to false and RSS search still happens.  Log shows no errors related to RSS but does show a persistent "BG download is busy - try again in 10 seconds" message.  The RSS search is very, very slow too.  It takes about 10 seconds to see a show name change in the Scan Progress dialog box.

TVRename v4.4.9
Windows 7 with all service packs installed

**Comment by SirSparkles** [comment]
If you've taken the RSS links out, I don't know how it would still be doing the RSS search,

Have you had the chance to look in the logs to understand what's actually happening at that point? It looks at the JSON search and Jackett during that time too. (Although it says 'Search RSS' on the screen, it should probably say 'Search RSS/JSON and other web sources'

**Comment by SirSparkles** [comment]
@ChrisMTheMan - could you disable it by looking at Jackett / JSON search?

**Comment by ChrisMTheMan** [comment]
Yes, the 'RSS Search' stopped once I disabled Jackett/JSON search.  I agree, that dialog should be labelled 'Web Searches' or something else appropriate.
