### ISSUE TITLE
Information panel truncated

### ISSUE THREAD

**Issue by XCountry** [TV-Rename/tvrename#841]
- [X] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [X ] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall]
# Bug Details

**Describe the bug**
<img width="562" alt="2021-11-20_16-03-09" src="https://user-images.githubusercontent.com/94737139/142719403-1964b047-9da3-4210-b128-6640e79908a1.png">
The images and text in the information panel on the right is truncated and there is no horizontal scroll bar to read the full text of the show.

**Expected Behaviour**
The text and images should be resized to fit the window or there should be a horizontal scroll bar for me to view the right side

**Current Behaviour**
Some text and image is cut off

**To Reproduce**
1. Add a show
2. Scan
3. View the show information on the right panel

**Context**

* Operating System: Win10

**Comment by SirSparkles** [comment]
You running in high DPI mode?

**Comment by SirSparkles** [comment]
See #804

**Comment by XCountry** [comment]
Thanks! I change the properties and it worked!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by SirSparkles** [comment]
@XCountry 4.6.6 should contain an improved fix for this.

If you are able to try to do Beta->Web Test and report back - that would be great

**Comment by SirSparkles** [comment]
I think the latest versions solve this problem overall. If there are still issues, can they be raised as separate issues please? #914 are the known issues right now
