### ISSUE TITLE
Missing files xml not updating after Recent Scan

### ISSUE THREAD

**Issue by anoname1** [TV-Rename/tvrename#842]
# Bug Details

**Describe the bug**
Since a recent update the missing file xml does not get regenerated.

**Expected Behaviour**

The xml file to be updated with the latest Full Scan details.

**Current Behaviour**

After a Recent Scan, A Full Scan does not regenerate the xml file. Deleting the xml file and running a new Full Scan creates a file as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Perform Recent Scan to generate xml file
2. Perform a Full Scan to update the xml file
3. The xml file does not change from the Recent Scan version

Include whether it happens all the time or just sporadically. Also are there certain shows that it applies to?  What other investigation can/have you done?

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Win10
* Are you using the windows version or command line version? Win version

**Additional context**

## XML Files

Please include your XML files from your user directory here. Rename them to be txt files to load them here directly.
- See https://www.tvrename.com/manual/technical/#configuration-files for more information
[TVRenameSettings - Copy (3).txt](https://github.com/TV-Rename/tvrename/files/7574227/TVRenameSettings.-.Copy.3.txt)

**Comment by SirSparkles** [comment]
The missing CSV and XML files are only produced when a full scan is produced. 

A Recent or Quick Scan only scans a subset of shows and hence the missing list would be wrong (and only show a subset of the missing items)

**Comment by anoname1** [comment]
I agree that what you describe is the usual behaviour but since one of the recent updates it is not.

**Comment by anoname1** [comment]
I guess I didn't describe it well, this is a real bug.

**Comment by anoname1** [comment]
After a Recent Scan the xml file gets rewritten with new info, after that a Full Scan no longer works.

**Comment by anoname1** [comment]
![Untitled](https://user-images.githubusercontent.com/83394646/142736808-8eb02220-fc28-48dc-9f0d-2da14fd59d6e.png)

**Comment by SirSparkles** [comment]
Yes, there was a bug that meant that it looked at the scan before the last scan to decide whether to produce the file. There is a code change in to remedy this (see link above). Will be distributed with the next build. Thanks for reporting and persisting

**Comment by anoname1** [comment]
TEMPORARY WORKAROUND

To avoid the bug, only run Full Scans.

**Comment by anoname1** [comment]
Thanks for the fix, works great.
