### ISSUE TITLE
Row selection no longer working nor optimal

### ISSUE THREAD

**Issue by rrrevin** [TV-Rename/tvrename#852]
Running 4.5.1 on W10.

Selecting a row takes upwards of 15 seconds before the "tick" appears. Also, when a row is ticked, I can no longer "unselect" it. Double clicking on the row does noting, neither does clicking on the "tick". Screen shots below.

Details..
Going to Scan/Recent Scan.. I get a list of shows. Then I unselect Check -> Show All. This will allow me to manually select rows.
Screen shot at this point : ![1](https://i.imgur.com/izdFtpI.png)

Now when selecting or double clicking any row, it is no longer immediate as it was in previous versions. It takes upwards of 15 seconds before the "tick" appears. : ![2](https://i.imgur.com/cyBqBgx.png)

And now.. I can no longer unselect a row. Double clicking on a row does nothing, neither does selecting the "tick". Doesn't matter how long I wait.

**Comment by rrrevin** [comment]
So a bit more research on this. Here is how I can replicate this every time.
This is still occurring under version 4.5.3.

1) select Scan
2) select Recent Scan
3) wait for scan to complete
4) unselect Check -> Show All
5) double click the row for your show, but DO NOT MOVE THE MOUSE outside of the selected row
6) **if the row has multiple possible filenames for the same source file**, the row will never be ticked as long as the mouse remains in the selected row. (*)
7) the moment the mouse leaves the selected row, then and only then does the tick appear for the selected row.
8) double clicking or unselecting the tickbox for the selected row does nothing. Moving the mouse in/out of the selected row does nothing.

_(*) Note: if the row has only one filename for the source file, the row selection works as expected. The tick immediately appears or disappears on selection or deselection._

**Comment by SirSparkles** [comment]
Hmmm - let me investigate. Seems to update in a timely fashion for me. I have changed the way it works to try and improve the issues you saw with earlier versions. It's working much better for me.

Behind the scenes the 'items' have been unticked. There must be some problem with the UI not updating - let me see if I can force it to refresh.

**Comment by crcarley** [comment]
I am experiencing same issue as @rrrevin in 4.5.7 on Win 10.

**Comment by SirSparkles** [comment]
OK - just done a fix that should improve it in 4.5.8

**Comment by rrrevin** [comment]
> I am experiencing same issue as @rrrevin in 4.5.7 on Win 10.

@crcarley can you look at #901 ?
