### ISSUE TITLE
Connections to Papertrail?

### ISSUE THREAD

**Issue by rrrevin** [TV-Rename/tvrename#853]
Was tracing the open connections on the app.. what is this connection to Papertrail for???
![Papertrail](https://i.imgur.com/caSY8Gj.png)

**Comment by SirSparkles** [comment]
Papertrail is a logging app that TV Rename will send anonymous crash details to if an unexpected problem occurs. Can be turned off in preferences.

**Comment by SirSparkles** [comment]
Not sure what the AWS connection below is though? Maybe one of the API calls get routed to AWS servers

**Comment by rrrevin** [comment]
Thanks.

**Comment by SirSparkles** [comment]
Which tool are you using to trace connections?

**Comment by rrrevin** [comment]
http://www.nirsoft.net/utils/cports.html

**Comment by SirSparkles** [comment]
The link the the AWS server is initiated by the Cef component we use https://github.com/cefsharp/CefSharp

**Comment by rrrevin** [comment]
Any idea why Cef needs an open and active connection to AWS?

**Comment by SirSparkles** [comment]
@amaitland Is this one you can help with? The Cef component seems to hold a CMD connection to an AWS server

**Comment by amaitland** [comment]
> The Cef component seems to hold a CMD connection to an AWS server

CEF itself doesn't make a connection to AWS. Possibly this is a service worker for one of the websites your using.

**Comment by amaitland** [comment]
> The link the the AWS server is initiated by the Cef component we use

How did you come to this conclusion exactly? CEF makes all network requests through the network service (separate process). Looks like this request originates from the main application exe, so I'd be doubtful this originates from CEF. 

Have you tested with paper trail disabled?

**Comment by SirSparkles** [comment]
Stepping through the code shows the connection is created when we call Cef.initialise. 

Could it be the Cef CrashReporting service

**Comment by amaitland** [comment]
> Stepping through the code shows the connection is created when we call Cef.initialise.

Can you test with https://github.com/cefsharp/CefSharp.MinimalExample and see if you see the same behaviour? 

> Could it be the Cef CrashReporting service?

Should be disabled by. https://bitbucket.org/chromiumembedded/cef/wiki/CrashReporting.md
