### ISSUE TITLE
ThrowIfFrameInvalid

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#862]
| 4.5.2 |ERROR| System.Exception: The underlying frame is no longer valid - please check the IsValid property before calling!     at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()     at CefSharp.Internals.CefFrameWrapper.LoadUrl(String url)     at CefSharp.WinForms.ChromiumWebBrowser.Load(String url)     at TVRename.UI.SetWeb(ChromiumWebBrowser web, Action a) System.Exception: The underlying frame is no longer valid - please check the IsValid property before calling!     at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()     at CefSharp.Internals.CefFrameWrapper.LoadUrl(String url)     at CefSharp.WinForms.ChromiumWebBrowser.Load(String url)     at TVRename.UI.SetWeb(ChromiumWebBrowser web, Action a)

**Comment by amaitland** [comment]
I'll add an extra `MainFrame.IsValid` check to `Load` to avoid this exception.

Do you have any insight into what was going on when this happened? There have been some upstream `CEF` changes regarding frames, so any insight you can give into how to reproduce this would be helpful.

**Comment by SirSparkles** [comment]
@amaitland It's difficult to tell. Any unexpected errors from the community are funnelled anonymously back, so I have very little context unless the user reaches out.

All I can tell is that is happened on  Microsoft Windows NT 6.2.9200.0, 64 Bit OS, 64 Bit Process 4.0.30319.42000

Also it only happens sporadically (and on random computers), but does happen 2-3 times per day across the installed user base
