### ISSUE TITLE
cef thread

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#870]
| 4.5.2 |FATAL| UNHANDLED ERROR - GlobalExceptionHandler System.Exception: Cef.Shutdown must be called on the same thread that Cef.Initialize was called - typically your UI thread. If you called Cef.Initialize on a Thread other than the UI thread then you will need to call Cef.Shutdown on the same thread. Cef.Initialize was called on ManagedThreadId: 1where Cef.Shutdown is being called on ManagedThreadId: 3     at CefSharp.Core.Cef.Shutdown()     at CefSharp.WinForms.ChromiumWebBrowser.OnApplicationExit(Object sender, EventArgs e)     at System.Windows.Forms.Application.RaiseExit()     at System.Windows.Forms.Application.ThreadContext.Dispose(Boolean postQuit)     at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)     at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)     at System.Threading.ThreadHelper.ThreadStart()

**Comment by amaitland** [comment]
> Cef.Initialize was called on ManagedThreadId: 1

This is what I would expect, `Cef.Initialize` called on `Thread 1`, `Cef.Shutdown` also needs to be called on this thread.

> Cef.Shutdown is being called on ManagedThreadId: 3

This is the problem part. The [ChromiumWebBrowser static constructor](https://github.com/cefsharp/CefSharp/blob/cefsharp/96/CefSharp.WinForms/ChromiumWebBrowser.cs#L254) will hook `Application.ApplicationExit`, which will typically execute on the main thread. I don't know enough about your application to suggest what's happening here.

You can set `CefSharpSettings.ShutdownOnExit = false;` before interacting with `ChromiumWebBrowser` then manually calling `Cef.Shutdown` on the main thread, possibly in `Program.Main`.
