### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by XCountry** [TV-Rename/tvrename#879]
- [X] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [X] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))

**Describe the bug**
I get an error when starting TVRename once in a while. I have tried different versions up to the latest and still get the error
"Unexpected end of file while parsing Name has occurred. Line 58319. position 10"
I get a list of settings to restore from but if I select any of the cache, nothing happens. If I only select Application settings and click OK, TVRename starts but I then have to reload the information again.

**Comment by XCountry** [comment]
<img width="680" alt="2021-12-17_8-38-02" src="https://user-images.githubusercontent.com/94737139/146469520-5ba6e68f-351e-4a21-8cb1-afacd913f7ea.png">
This is what I got opening TVRename today. Should I close it before closing my computer?

**Comment by SirSparkles** [comment]
Select the second one in the first, third and 4th ones. Select the 'No Cache' option for the second one (TheTVDB)
