### ISSUE TITLE
Shows cant be found sometimes until restart.

### ISSUE THREAD

**Issue by ItsME6969** [TV-Rename/tvrename#886]
# Bug Details

**Describe the bug**
Sometimes shows can't be found by TVDB name and you have to find the ID and it shows as unknown. This is a show I had, but removed it from the list. I have autoadd on scan on which picked it up again but couldnt find it until I used the TVDB ID. I've seen this bug a lot and for the longest time.

**Expected Behaviour**
Find the show without having to use the ID

**Current Behaviour**
Doesn't find shows sometimes, with the name being exactly as is on TVDB.

What is the current behaviour?

**To Reproduce**
Steps to reproduce the behaviour:
1. Delete a show off the list
2. Auto Add on scan on
3.  Deleted the show and tried to bulk add it doesnt show up. So it does not occur only on auto add on scan but just generally.

![11 - Copy](https://user-images.githubusercontent.com/89707006/149294402-e8f6440a-408b-463e-80c6-6fa63d9292b7.jpg)
![12 - Copy](https://user-images.githubusercontent.com/89707006/149294406-1861a6f4-8d50-4eb4-9447-2e3364aadb00.jpg)

4. Close the App and restart and boom...the show is found now using the name.

![3 - Copy](https://user-images.githubusercontent.com/89707006/149294440-fc8b0eb1-266d-490e-b530-65f1642ec6cf.jpg)
![4 - Copy](https://user-images.githubusercontent.com/89707006/149294444-4b8ce4bb-d9a8-459d-b32e-407faea32fd6.jpg)

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11
* Are you using the windows version or command line version? Windows

**Additional context**
None

**Comment by SirSparkles** [comment]
OK - I made a change in 4.5.6 that should help. I can't make it forget the name anymore, but am not 100% that this has resolved it.

Can you take a look and see whether we need further changes please?

**Comment by ItsME6969** [comment]
Thanks. I'll report back if any issues arise.

**Comment by ItsME6969** [comment]
@SirSparkles The bug still exists and is easy to replicate just as before.
1. Delete a show
2. Try to add it.....It doesn't get found
3. Restart and search again... Now it's found
