### ISSUE TITLE
Display / Cropping issue on 4k screen

### ISSUE THREAD

**Issue by 555five** [TV-Rename/tvrename#899]
Display / Cropping issue on 4k screen

On the TV Shows > Information tab, the image/information is cropped such that I can see only a quarter of the image. 

Please see screen capture - https://i.imgur.com/AyVVG3A.jpg
Or attached picture

This issue has been present since the major overhaul. 
Currently on latest version 4.5.7

This appears to be specific to 4k Display resolution (3840x2160). 
If I change to 1920x1080, there is no cropping. 

Apologies if this is a known issue.  Thanks.

![ScreenCap4k](https://user-images.githubusercontent.com/98145144/150475900-d76c7ff9-b35d-4ff5-bd46-6dd7a796bef3.jpg)

**Comment by SirSparkles** [comment]
Have a look at these: https://github.com/TV-Rename/tvrename/labels/UI-DPI
and 
https://groups.google.com/g/tvrename/search?q=dpi

It's a known issue that's difficult for me to fix as I can't reproduce. Others have had success tweaking the DPI settings though

**Comment by 555five** [comment]
I suspect that the issue might be related to scaling under Windows display settings. On my 4k laptop screen, scaling is set to 225% to make things readable on a 15" screen. 

If I change the scaling to 100% it corrects the problem within TV rename. But everything else is way to small to read. 
I hope this information might allow you at least to reproduce the issue.

Thanks you muchly for your continued work.

**Comment by SirSparkles** [comment]
Can you try https://github.com/TV-Rename/tvrename/releases/tag/4.6.3 please?

Main view will be broken, but go into Beta mode and try Beta -> Web Test and Beta -> Download installer

**Comment by SirSparkles** [comment]
@555five - Actually 4.6.6 is better and should try to improve the experience

Main view will be broken, but go into Beta mode and try:
Beta -> Download installer
and
Beta -> Web Test

**Comment by 555five** [comment]
@SirSparkles - Thanks, 4.6.6 has resolved the view for TV Shows > Information tab, (though lots of other things such as columns are truncated).
How does one enter beta mode?

**Comment by SirSparkles** [comment]
Options -> Preferences -> General -> Mode = Beta

**Comment by SirSparkles** [comment]
Let me know of problems. If the original offset issue is resolved then don't worry about Beta->Web Test

**Comment by SirSparkles** [comment]
Truncated columns should be able to be solved by dragging them to the needed width and TVR should remember the new widths when it reopens

**Comment by 555five** [comment]
Thanks @SirSparkles 
It's looking good now. 

Some notes - 
Main Page > the names of the tabs 'TV Shows' and 'Schedule' are truncated (see screen capture) 

![Scr-01](https://user-images.githubusercontent.com/98145144/173318110-724b7e86-0ac0-4db4-b950-e756a605fea3.jpg)

Tools > Quick Rename remembers spacing. 
But for some reason the TV Shows > Add window truncates and doesn't remember the spacing (see screen capture)

![Scr-02](https://user-images.githubusercontent.com/98145144/173318322-d0e8e322-122d-4f2c-8885-6dc2536aa475.jpg)

**Comment by SirSparkles** [comment]
Thanks - will take a look at these issues

**Comment by SirSparkles** [comment]
Latest should fix add/edit TV show

Have not managed to replicate the 'TV Shows' and 'Schedule'  one yet

**Comment by 555five** [comment]
DPI Scaling on main screen is worse on 4.7. 
The icons are truncated and the clickable area does not match the icons. 
![Scr1](https://user-images.githubusercontent.com/98145144/174514640-4aa93f4d-dd51-46f4-bf67-d3cbdd894239.jpg)

Actually I found the text descriptions for Movies/TV Shows/Search/Schedule more helpful than just the icons. Thanks

**Comment by 555five** [comment]
@SirSparkles - 
Version 4.7.1 looks perfect. Good work!

**Comment by SirSparkles** [comment]
Great - thanks for persevering - let us know of any further issues you notice
