### ISSUE TITLE
Fuzzy name matching when finding episodes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#9]
```
fuzzy match on looking for matching ep 

http://tvrename.com/bb/viewtopic.php?f=5&t=390&p=1502#p1399
```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:05

**Comment by MarkSummerville** [comment]
Link is now http://old.tvrename.com/bbold/5/t-390.html

https://www.autoitscript.com/forum/topic/55617-fuzzy-string-matching/

**Comment by MarkSummerville** [comment]
Now tracked here: http://ideas.theideawall.com/TVRename/Forum/TopicDetails/0a0b5abe-8079-4fd7-baa5-6aa80cfaafe0?fb=0

Closing this until we decide to work on this
