### ISSUE TITLE
just remindin you that the Information window (and maybe other windows) is still totally mucked up and unusable with high-DPI scaling %

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#909]
dude, thanks again for TV Rename but just remindin you that the Information window (and maybe other windows, don't remember) is still totally mucked up and unusable with Win 10 DPI scaling at 225% (maybe also for other high DPI %s)

plz see here: https://imgur.com/nH1xmow

it's been like that for months i think - i'm on latest v

**Comment by SirSparkles** [comment]
Can you try https://github.com/TV-Rename/tvrename/releases/tag/4.6.3 please? 

Main view will be broken, but go into Beta mode and try Beta -> Web Test and Beta -> Download installer

**Comment by SAH7777** [comment]
> Can you try https://github.com/TV-Rename/tvrename/releases/tag/4.6.3 please?
> 
> Main view will be broken, but go into Beta mode and try Beta -> Web Test and Beta -> Download installer

I tried it but it's worse, here is a screenshot... you will see things are misshapen and I can't even see my tree of TV Shows anymore:

https://imgur.com/nT6ZevR
https://imgur.com/e8DoQ2w
https://imgur.com/k8GHxwj

**Comment by SirSparkles** [comment]
What about 'Beta -> Web Test' 

This version is just designed to see if we fix the offset in the info pane issues:
![image](https://user-images.githubusercontent.com/14905881/173165995-8fa04e54-83d7-412c-86f7-cd29040c9003.png)


The left and right use different components - aim is to see whether the offset issue can be fixed

Will have to work on the other DPI issuses separately

**Comment by SAH7777** [comment]
Ok, I'll try it/that out later on today or tomorrow (I'm in Australia, East coast) as I really need to update my TV Rename TV Show paths (as I did a big server directory change recnetly), then save n backup my TV Rename setup... before doing any more Beta testing, thanks

**Comment by SAH7777** [comment]
ok, i found some time, and rushed through my testing, so that you could work on tv rename this weekend if you wanted....

to recap, I'm on Win 10 at 225% dpi scaling

Web Test did nothing, because I can't even see any summary information in 4.6.3 (see screenshots below)

in 4.6.3, things do look crispier, which is nice, but the layout is all misshapen/missing-bits

here are the testing screenshots...

BEFORE (v 4.6.1):
https://imgur.com/ikcvLr3
https://imgur.com/3Oi1oq2

AFTER (v 4.6.3):
https://imgur.com/cyxRXIf
https://imgur.com/WeRhOoh

I'll have to roll-back to 4.6.1 for now

thanks

**Comment by SirSparkles** [comment]
WebTest etc tries to fix the offset for the component on the right

This is the list of stuff I'm working through to fix general label sizes etc:
https://stackoverflow.com/questions/22735174/how-to-write-winforms-code-that-auto-scales-to-system-font-and-dpi-settings/29766847#29766847

**Comment by SAH7777** [comment]
yep, but in case you missed it, the said "component on the right" is now completely missing in the latest beta build (look closely/compare the screenshots above)

**Comment by SAH7777** [comment]
also the TV Show tree is completely missing now

**Comment by SirSparkles** [comment]
Thanks for making the time. Unfortunately it all looks sweet on my system, so any changes are 'hit and hope'.

If you can try https://github.com/TV-Rename/tvrename/releases/tag/4.6.4 then hopefully it pushes it in the right direction. (will be up soon)

Please send a screenshot of the window that displays when you click on 'Beta -> Web test' my hope is that the left hand side fails, but the right hand side works,

**Comment by SAH7777** [comment]
Sorry, I don't know (haven't learnt how) to deal with source code .zip assets.... I'll need to just wait for a pre-compiled .exe installer to overwrite previous installed build before I can test anything

**Comment by SAH7777** [comment]
oh the exe is up now (25 secs ago), I'll give it a try

**Comment by SirSparkles** [comment]
Just takes a while to be created - is up now

**Comment by SAH7777** [comment]
sorry, i used all my monthly internet datacap (700GB) and it's on the go-slow, so still downloading 4.6.4 (takes about 15 mins a build on slow speed)...

**Comment by SAH7777** [comment]
Um, the main stuff is still completely missing on my screen, please see here: https://imgur.com/b2OakJw

Beta > Web Test doesn't change anything

**Comment by SAH7777** [comment]
Here you go, some screenshots with different "High DPI scaling override" exe settings to help you fix the problem...

We can thank KevBlisse from here (https://github.com/TV-Rename/tvrename/issues/910#issuecomment-1153016856) for the tip(s) also

re The exe:
https://imgur.com/pdgWB5K
https://imgur.com/oesgyyy

setting Application (=blank):
https://imgur.com/7MwtbRO
https://imgur.com/BkwmzVL

setting System (=better):
https://imgur.com/eZIP4El
https://imgur.com/Q0DLOUn

setting System (Enhanced) (=half-half-fixed):
https://imgur.com/EZjluSh
https://imgur.com/NbYeSsN

Please study the screenshots carefully, took me a while to make, lol

Setting System means I can actually use 4.6.4, yay!, instead of having to keep rolling-back to 4.6.1 :)

**Comment by SAH7777** [comment]
Also this major Win 10 setting is probably relevant: https://imgur.com/hCtRNj2

**Comment by SirSparkles** [comment]
4.6.6 tries to fix the missing treeview and right hand pane issue. Please let me know what you think
