### ISSUE TITLE
sorting of eps messed up in scan results, plz see screenshot link below

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#910]
thx again for tv rename

i don't know what this view is called but it's the result of a show scan or full scan... plz see here: https://imgur.com/tFPsNRg

u can see a bug where the sorting is messed up... look at how messed up the episode ordering is... i don't have Simpsons S4+... it should be cleanly s4e1, s4e2, s4e3....

plz can u fix it?

it's been like this for the last few versions (a month or so)

**Comment by KevBlisse** [comment]
This is due to the filename template editor settings used, change them by going to options > filename template editor in the menu and set the naming template to the ordering preset you'd like.

**Comment by SAH7777** [comment]
Thanks! I'll try that later, but right now I really need the dev to fix 4.6.4 re respecting our Win 10 DPI-scaling-%-setting, because I'm getting tired of having to keep rolling-back to 4.6.1

**Comment by KevBlisse** [comment]
I've managed to fix that, by right clicking on the TVrename.exe and clicking properties, then compatibility and change high dpi settings, ticking the box in Program DPI  and High DPI scaling override and setting that to Application meant it displayed the tv info correctly for me.

**Comment by SAH7777** [comment]
Lol, my 4.6.4 is fixed when doing High DPI override > System (NOT Application), but thx for that tip!

**Comment by SAH7777** [comment]
> This is due to the filename template editor settings used, change them by going to options > filename template editor in the menu and set the naming template to the ordering preset you'd like.

Thanks, but changing to different filename template editor presets, unfortunately didn't fix the ep sorting issue in my scan results :(

**Comment by KevBlisse** [comment]
> 

What regex's do you have enabled under Filename Processors? I've had problems finding some files when I've not had certain ones enabled.

**Comment by SAH7777** [comment]
I think I had default before, and I restored "default matching expressions" just now, but the ep sorting in scan results issue remains, unfortunately :(

**Comment by KevBlisse** [comment]
Under Prefences > Scan Settings > Missing Check - Do you have ignore episodes previously seen ticked?

**Comment by SAH7777** [comment]
Thanks for trying to help, please see here (the settings and the problem in the same screenshot, particularly compare 4x01 and 4x02 positions): https://imgur.com/ckiGZZv

You might notice that I don't use TV Rename for actually Renaming anything, lol, but just for Missing checks and New Aired checking.

**Comment by KevBlisse** [comment]
Ahhh. What happens when you click the episode or date column titles? does that fix the ordering? 

I missed what your problem was and thought it was something else. Sorry. Joys of online tech support.

**Comment by SAH7777** [comment]
Please see video demo here: https://gofile.io/d/kHySKG

Sort by Date IS better, thx! (but would prefer if Sort by Season was actually fixed).

Also, "Revert View" is also bad, see here: https://imgur.com/pafDtFN

**Comment by KevBlisse** [comment]
Ahhh yes, it is a bug. I think it's due to the lack of a leading zero on episode numbers.

**Comment by SAH7777** [comment]
Yeah that makes sense and would be why e01 is at the top, while e02 is after e19 (bug).

It's annoying and confusing when I'm checking for Missing eps via Scan, lol

**Comment by SAH7777** [comment]
And because of this, I find myself tending to use the TV Show **Summary** grid more and more (not Scan)

**Comment by SAH7777** [comment]
yep, fixed now, thx!
