### ISSUE TITLE
TV Rename crashes on startup after update to latest version

### ISSUE THREAD

**Issue by JoseHidalgo** [TV-Rename/tvrename#911]
Hello from France, and first of all, thanks for this great piece of software. :) Here's my issue :

Yesterday, I have updated TV Rename from 3.3.1 to 4.6.1.
The installer asked me to install NET Framework 4.8, which I accepted.
The installer forced a reboot, but overall everything went well.
After the reboot, I tried launching TV Rename (Windows version). It immediately crashed on startup.
This happens 100% of the time. Which means that I can't use TV Rename anymore.
With version 3.3.1, everything was working perfectly.
Also, I have a big database with dozens of TV shows, so I hope I won't lose it !

Please check the included log file, I think the problem is pretty clear. ;)

FYI I'm still using Windows 7 SP1 x64. I have an old PC that wouldn't support Windows 10/11 anyway.

## XML Files
[TVRenameSettings.txt](https://github.com/TV-Rename/tvrename/files/8549456/TVRenameSettings.txt)
[TheTVDB.txt](https://github.com/TV-Rename/tvrename/files/8549457/TheTVDB.txt)
[Statistics.txt](https://github.com/TV-Rename/tvrename/files/8549458/Statistics.txt)
[Layout.txt](https://github.com/TV-Rename/tvrename/files/8549459/Layout.txt)
[Languages.txt](https://github.com/TV-Rename/tvrename/files/8549460/Languages.txt)

## Log Files
[TVRename.log](https://github.com/TV-Rename/tvrename/files/8549452/TVRename.log)

## Error messages
2022-04-24 04:01:51|FATAL| Application exiting with error System.
TypeInitializationException: An exception has been lifted by the type inizializer for 'TVRename.TMDB.LocalCache'. ---> System.IO.FileNotFoundException: Impossible to find the file or the assembly 'TMDbLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The specified file is missing.

## Screenshots or videos of the issue
The app just crashes immediately on startup, displaying the error dialog, so there's nothing more to show. Thanks in advance for your help !

**Comment by SirSparkles** [comment]
Maybe try another install? Looks like some component was not installed

does C:\Program Files (x86)\TVRename have TMDBLIb.dll ?

**Comment by JoseHidalgo** [comment]
Thanks for your reply.
I can confirm that C:\Program Files (x86)\TVRename does NOT have TMDBLIb.dll.
For unknown reasons that file was skipped during installation.

A reinstall fixed the issue. I was afraid of trying it because I was unsure of the problem and I didn't want my database to be erased. Your reply helped me understand that it was probably an installation issue.

Everything seems to be working now. Thanks a lot for your help!

Problem closed I guess. :)
