### ISSUE TITLE
Bug: AFter doing bulk add show(s) > go to tv show page/listing > right-click a show > scan "show" => see bug = scan returns "full scan" results, not just for the desired right-clicked show

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#933]
Thx again for TV rename!

Bug: AFter doing bulk add show(s) > go to tv show page/listing > right-click a show > scan "show" => see bug = scan returns "full scan" results, not just for the desired right-clicked show

**Comment by SirSparkles** [comment]
There is a deliberate feature in there. If you add a show it is included in the next scan (whatever that scan is for).

I suspect that the scan results are for the show you right-clicked plus any recent ones you added (eg via Bulk Add)

**Comment by SirSparkles** [comment]
(If you do a 'Fast Scan "ShowName"' it bypasses this feature

**Comment by SAH7777** [comment]
ahh, ok, thx!
