### ISSUE TITLE
Microsoft Defender SmartScreen prevents installer to run

### ISSUE THREAD

**Issue by shalak** [TV-Rename/tvrename#941]
# Bug Details

**Describe the bug**
Microsoft Defender SmartScreen prevents installing 4.7.0

**Expected Behaviour**

Installer is not flagged by Microsoft Defender SmartScreen.

**Current Behaviour**

Installer is flagged by Microsoft Defender SmartScreen, cannot proceed with install.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run installer for 4.7.0

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Are you using the windows version or command line version? N/A

## Screenshots or videos of the issue
<img width="908" alt="image" src="https://user-images.githubusercontent.com/1536554/187089128-6f8c2f22-7137-424c-9865-7c6a676ee594.png">

**Comment by SirSparkles** [comment]
If you click on 'Wiecej informacji' you can allow the installer to run.

It takes a while for windows defender to realise the file is safe

**Comment by shalak** [comment]
> It takes a while for windows defender to realise the file is safe

I tried installing 4.6.1 - same situation. How much time do I have to wait? Is it possible to send the binary to Microsoft for analysis so they can whitelist the file signature?

**Comment by SirSparkles** [comment]
https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

**Comment by SirSparkles** [comment]
https://www.microsoft.com/en-us/wdsi/submission/5aa21a59-f49c-4c5e-8e17-4519260c52dc

**Comment by shalak** [comment]
> https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro
> > Option 1: Submit your app for malware analysis to Microsoft

@SirSparkles did you submit it already?

**Comment by SirSparkles** [comment]
yep - should work ok now
