### ISSUE TITLE
Mediabrowser compatability Episode Thumbs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#95]
```
What steps will reproduce the problem?
1. Upon Scan prepares to download TVDb JPG
2. Renames automatically to episode name.tbn
3.

What is the expected output? What do you see instead?
I'd love to have the ability to overide the name change and even the 
possibility to have the downloaded jpg's land in the metadata folder. 

What version of the product are you using? On what operating system?
Version 2.2.0b5 Windows vista

Please provide any additional information below.

Really the only reason I'm even using Media browser is for the "wall" view.
If you could add this functionality then wow. Using Media companion for movies 
because of this.
```

Original issue reported on code.google.com by `glen.whiston@gmail.com` on 26 Oct 2010 at 10:30

**Comment by MarkSummerville** [comment]
See also:

Hi,

First off, thanks for a fantastic application it's been a real help. Like a lot of others, I've toyed with a few other such applications, but for TV this is the most common sense approach to moving/renaming/scraping I've seen. I know you've announced that you're scaling back your development this year, but I thought I would be cheeky and ask you if you had any intentions of increasing the scope of your app to encompass MediaBrowser compatibility?

Like XBMC, they scrape data from TVdb but can also used locally stored metadata. Whereas XBMC uses nfo & tbn in each of the season folders, MediaBrowser uses xml & jpeg stored in a season\metadata folder. As the source data is the same, the are broad similarities between the nfo & xml files, although some of the flag names are different, and it looks like the xml contains more fields. The tbn and jpeg files are identical, the only difference is that it's existence needs to be specified in the xml file under the <filename> flag.

http://old.tvrename.com/bbold/4/t-1566.html

**Comment by JoeBiellik** [comment]
Has MediaBrowser become [Emby](https://github.com/MediaBrowser/Emby)? It seems to [follow the same naming](https://github.com/MediaBrowser/Wiki/wiki/TV%20naming) as Kodi etc, and should be easy enough to edit the metadata file names in v3, but I can't find any specific details in the NFO/XML format it uses.

**Comment by fotofrank** [comment]
On MediaBrowser and Emby: [https://emby.media/introducing-emby.html](url)
I also read somewhere that Emby server has migrated to full compatibility with Kodi.

**Comment by MarkSummerville** [comment]
https://github.com/MediaBrowser/Wiki/wiki/TV%20naming

**Comment by MarkSummerville** [comment]
http://ideas.theideawall.com/TVRename/Forum/TopicDetails/066e4d09-d61a-4221-a7a6-b3c6c7c87535

Closing as I think putting Kodi files will do the job
