### ISSUE TITLE
TMDB as Source is now TOTALLY BROKEN, TV Rename can't communicate with TMDB API

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#950]
Hi, 

TV Rename needs an urgent update regarding using TMDB as Source for Show Metadata. It's totally broken now, just try adding a new show with TMDB as Source, and try Scanning the Show. 

They must have changed the TMDB API in the last few weeks.

Please can you kindly fix it ASAP? 

Thank you and thank you for TV Rename!

**Comment by SirSparkles** [comment]
Try v4.9.0 and make sure you install https://dotnet.microsoft.com/en-us/download/dotnet/7.0 first

**Comment by SAH7777** [comment]
Hi,

I tried the new 4.9.0 big final release already, the problem remains, but no I haven't installed dotnet 7 yet. But which dotnet 7 installer do I download? There are like 5x different installers to choose on that single weblink. I'm assuming I need one of the 'runtime' ones?

Anyway, it's late night here now, so I won't be able to try again till later tomorrow probably.

Thank you.

**Comment by SirSparkles** [comment]
You'll need the SDK one for your system type - probably https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.202-windows-x64-installer

**Comment by SAH7777** [comment]
Hi, 

I installed it and restarted and tried TVRename again, but no change, looks like TVRename can no longer communicate with the TMDB API. I think they changed something on their end. 

Please can you try yourself with some test Shows set to use TMDB as Source? 

Thank you!

**Comment by SAH7777** [comment]
Oh, Wait! It's working now, but there was a biiiiiggggg delay in pulling down the TMDB metadata, but at least it's working! Thank you!
