### ISSUE TITLE
>NET 6.0.16 Installed by TV rename refuses to run?

### ISSUE THREAD

**Issue by xzavain** [TV-Rename/tvrename#952]
I am running the latest version of TV Rename, just removed and installed today. 

I am getting a prompt that I need to install .NET 6.016 x64 bit. I install this, which I confirmed is installed and I still get this prompt and TV rename refuses to run. 

Please see attached images.
[https://ibb.co/DGQY95G](url)
[https://ibb.co/sq0f9fb](url)
[https://ibb.co/5rt4hBp](url)

I also have the latest version of Windows 11 Pro 64 Bit.

Please fix this issue, this is highly annoying and is preventing me from using the software.

**Comment by SirSparkles** [comment]
https://groups.google.com/g/tvrename/c/S3e4mV75o9A

**Comment by SirSparkles** [comment]
Need to install the SDK - it's not clear why though

**Comment by SirSparkles** [comment]
Try running `dotnet --list-runtimes` to see what's installed.

You need;
- Microsoft.AspNetCore.App 6.0.16
- Microsoft.NETCore.App 6.0.16
- Microsoft.WindowsDesktop.App 6.0.16 

Take a look at #954 to see how we diagnosed it for another user.

Advice is now at https://groups.google.com/g/tvrename/c/ArsxJPYe6BY/m/dtFrwJQVBAAJ to assist

Please let us know if this does not work for you and we can re-open the issue

**Comment by Ruthalas** [comment]
For posterity the link to the discussion in the second comment works, but the link in the last comment above is dead.
I have archived the discussion link [here](https://web.archive.org/web/20230701033706/https://groups.google.com/g/tvrename/c/S3e4mV75o9A).

The suggested solution is to install the SDK (software development kit), which contains the three runtimes mentioned above:
- NET Runtime 6.0.15
- [ASP.NET](http://asp.net/) Core Runtime 6.0.15
- NET Desktop Runtime 6.0.15

To do this you can either:
- Visit [this link](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) and download and install the correct version for your OS
- Or use this command in windows command prompt: `winget install Microsoft.DotNet.SDK.6`

I used the second and it resolved the issue for me.
