### ISSUE TITLE
4.9.1 won't launch, .net error even after installing .net

### ISSUE THREAD

**Issue by randomname42** [TV-Rename/tvrename#954]
I'm trying to run TV Rename on Windows 11 for the first time. It refused to run, saying .net needs to be installed.

First I installed .net 6 from the link in the error message that comes up when trying to start TV Rename (and restarted the pc). That did not fix it.

I saw .net 7 SDK recommended from https://github.com/TV-Rename/tvrename/issues/950 so I downloaded dotnet-sdk-7.0.302-win-x64 and installed that. And restarted the pc again.

I still get the same error when trying to run:

---------------------------
TVRename.exe
---------------------------
You must install or update .NET to run this application.

Framework: 'Microsoft.AspNetCore.App', version '6.0.0' (x64)

Would you like to download it now?

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
---------------------------
Yes   No   
---------------------------

Sorry if this sounds like an unfair complaint, but why does it not link to what you actually need when it gives an error like that instead of something that doesn't help? I don't understand.

What are you supposed to install to fix this?

Edit: I looked up how to verify .net is installed right.

dotnet --list-sdks
7.0.302 [C:\Program Files\dotnet\sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

I don't understand what the problem is. It makes no sense that TV Rename won't run.

I have TV Rename installed on a different drive (D). There's no way that could be an issue, is there?

**Comment by randomname42** [comment]
I tried installed dotnet-sdk-6.0.405-win-x86 too and that didn't make TV Rename launch either.

**Comment by randomname42** [comment]
I found and old copy of 2.9.7 I had from a long time ago and it runs and works fine. I guess I'm going to have to use that for now.

**Comment by SirSparkles** [comment]
What does the log say?

TV  Rename does not put that message box up. Microsoft put that message up, so we don't have control over it. Having said that, we don't understand why it needs the SDK and not the normal runtime

**Comment by SirSparkles** [comment]
Also - any extra information in `dotnet --info`?

C++ Redistributable needs to be installed, but I think that the app reports the correct download link in that case (as we control the popup)

**Comment by randomname42** [comment]
> What does the log say?

It never launches so it doesn't make a log. The only logs are for 2.9.7 after I started using that instead (I checked every log to make sure). I'm guessing those wouldn't help.



> Also - any extra information in `dotnet --info`?

.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by SirSparkles** [comment]
Thanks for trying. No smooking gun here though.

I have this though:
`Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]`
but I dont think that should matter - worth trying though

So when you try and launch it, it just pops up the dialog box from microsoft? 

Assuming you have tried a full reboot etc? Running as local admin?

**Comment by randomname42** [comment]
Yep, it instantly pops up that "you must install .net" message, and nothing else happens. Had already tried after full reboot. 

I tried running it as admin now (hadn't thought of trying that) but it still just pops up that .net needs to be installed message.

**Comment by SirSparkles** [comment]
try installing` Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]`

**Comment by randomname42** [comment]
After installing that and rebooting it finally launched!

**Comment by SirSparkles** [comment]
🙌
