### ISSUE TITLE
4.9.6 CLI logging still has issues

### ISSUE THREAD

**Issue by RogerD-AZ** [TV-Rename/tvrename#956]
When starting 4.9.6 via command line logging acts as expected, everything you'd expect to see is logged.

TV Rename 4.9.6 started with args: /quickscan /unattended
as expected, etc, etc.
as expected, etc, etc.

....Now with it already running via the above command line sending the following command....

2023-05-22 21:33:38|INFO| TV Rename 4.9.6 started with args: /quickscan /unattended 

....All that is logged is the below, but program acts/performs as expected. Any further CLI commands results is the same below output.

2023-05-22 21:33:38|INFO| Connected to NTP Server at UTC (based on local clock) 05/23/2023 04:33:38 AM 
2023-05-22 21:33:39|INFO| Finished connecting to NTP Server at UTC (based on local clock) 05/23/2023 04:33:39 AM - Offset = -00:00:02.7012075 
2023-05-22 21:33:39|INFO| Copyright (C) 2023 TV Rename 
2023-05-22 21:33:39|INFO| This program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions 
2023-05-22 21:33:39|WARN| An instance is already running, exiting 

....THE CEF-DEBUG.LOG CONTAINS THE BELOW

[0522/213105.337:ERROR:gl_display.cc(508)] EGL Driver message (Error) eglCreateContext: Requested GLES version (3.0) is greater than max supported (2, 0).
[0522/213105.337:ERROR:gl_context_egl.cc(371)] eglCreateContext failed with error EGL_SUCCESS
[0522/213305.232:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by SirSparkles** [comment]
You'll need to look in the prior log TVRename.00.log which the other instance still logs to

**Comment by RogerD-AZ** [comment]
Only the first log on CLI startup has any additional information, here is a dir from archive folder. All those additional logs are from sending additional commands once TVR has been started via CLI. This was not the case in the 3x versions. I'm the one that helped testing TVR during covid years., Thank you, RogerD

TVRename.00.log	623	05/24/2023 05:41p	-a--
TVRename.01.log	623	05/24/2023 04:41p	-a--
TVRename.02.log	623	05/24/2023 03:40p	-a--
TVRename.03.log	623	05/24/2023 02:40p	-a--
TVRename.04.log	623	05/24/2023 01:39p	-a--
TVRename.05.log	623	05/24/2023 12:39p	-a--
TVRename.06.log	623	05/24/2023 11:38a	-a--
TVRename.07.log	623	05/24/2023 10:38a	-a--
TVRename.08.log	623	05/24/2023 09:37a	-a--
TVRename.09.log	623	05/24/2023 08:37a	-a--
TVRename.10.log	623	05/24/2023 07:36a	-a--
TVRename.11.log	623	05/24/2023 06:36a	-a--
TVRename.12.log	623	05/24/2023 05:35a	-a--
TVRename.13.log	640	05/24/2023 04:35a	-a--
TVRename.14.log	623	05/24/2023 03:35a	-a--
TVRename.15.log	623	05/24/2023 02:34a	-a--
TVRename.16.log	636	05/24/2023 01:27a	-a--
TVRename.17.log	623	05/24/2023 01:26a	-a--
TVRename.18.log	623	05/24/2023 12:45a	-a--
TVRename.19.log	481,013	05/24/2023 06:32p	-a--

**Comment by SirSparkles** [comment]
The latest versions work differently as we not use .Net Core and the old way of communicating from the command line to the running instance has been removed.

 When tried with the latest versions on my PC it continues to log in the TVRename00.log file.  The logging infastructure controls which file each instance logs to. When the command line introduces a new instance of the app it checks to see whether one is aleady running and the running instance shuffles backward in its log. In your case it looks like **TVRename19** has been updated:

For example:

> 2023-05-25 22:00:18|INFO| UI: Updating MyShows 
> 2023-05-25 22:00:19|INFO| UI: Updating MyMovies 
> 2023-05-25 22:08:50|INFO| UI: Updating MyShows 
> 2023-05-25 22:08:50|INFO| UI: Updating MyMovies 
> 2023-05-25 22:14:49|INFO| Received C:\Program, Files, (x86)\TVRename\TVRename.dll, /quickscan, /hide, sending to the application. 
> 2023-05-25 22:14:49|INFO| ******************************* 
> 2023-05-25 22:14:49|INFO| Starting unattended Quick TV Shows and Movies Scan for all shows and all movies... 
> 2023-05-25 22:14:49|INFO| TV Rename is about to be busy doing Scan Quick since 25/05/2023 10:14:49 PM 
> 2023-05-25 22:14:49|INFO| Processing 0 files for shows that need to be scanned 
> 2023-05-25 22:14:49|INFO| Processing 0 directories for shows that need to be scanned 
> 
>

**Comment by RogerD-AZ** [comment]
I now see the backward shuffle, thank you for the explanation.
