### ISSUE TITLE
Scan stuck on "Getting updates list from TVDB"

### ISSUE THREAD

**Issue by TheWortLord** [TV-Rename/tvrename#969]
I love TV Rename and I am am having an issue that started about a month ago. When scanning my library for new files the scan gets stuck on the "Currently Downloading: Getting updates list from TVDB" popup window with a completely empty progress bar. Sometimes the scan will complete successfully if I let the program sit for a long time (at least 5 minutes if not longer). Wondering if there has been some change with the way the program interacts with TVDB. Any info would be greatly appreciated.

- [X] I am running the latest [4.9.9]
- [X] I checked the and found no answer
- [X] I checked to make sure that this issue has not already been [filed]
- [X] It is a bug (i.e. something that is going wrong) and not a new feature 
- [X] It is not a general question( these should be asked on the [support forum]

* Operating System: Windows

**Comment by SirSparkles** [comment]
Take a look at #955, #964, #967

TV Rename asks TVDB for the latest updates each time it runs. Seems that TVDB has had days when it has millions of updates at the same time and TV Rename hangs up while it gets through that backlog. 

Either leave it running for a while or do a 'force refresh all' and it'll catch up and should be OK again.

Please let us know if that doesn't fix it and we can reopen the issue

**Comment by TheWortLord** [comment]
Force refresh all seems to have worked a treat. Thank you and my apologies for not being able to find the previously existing issues.

**Comment by SirSparkles** [comment]
No worries - glad it worked. If you get it again then looking at the log file Help-> Log will sometimes give a reassuring nod to know it's still workign behind the scenes
