### ISSUE TITLE
Ignored episodes showing when running a full scan

### ISSUE THREAD

**Issue by DamnSynth** [TV-Rename/tvrename#971]
# Bug Details

**Describe the bug**
When running a full scan, episodes that I've added to the ignore list will appear

**Expected Behaviour**

The ignored episodes do not show after running a scan

**Current Behaviour**

Items on the ignore list are showing when running a full scan

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'scan'
2. Click on 'full scan'

Include whether it happens all the time or just sporadically. Also are there certain shows that it applies to?  What other investigation can/have you done? 

- Issue happens every time. I've tried re-installing the app and deleting the items on the ignore list and then re-adding them,  but this didn't resolve the issue.

## Screenshots or videos of the issue

<img width="530" alt="Screenshot 2023-06-15 111203" src="https://github.com/TV-Rename/tvrename/assets/64916854/e6520dcd-505d-4e6e-8c09-259843065745">

**Comment by SirSparkles** [comment]
Makes sense.
* Ignore List is designed for single episodes
* This item in the scan results relates to a whole season of episodes

**Work around**: So to make it work for a whole season that's missing you'll need to 'Revert to Missing episodes' and then add each to the ignore list. 

Code fix will remove that menu option for the season and allow you to remove the whole season (by adjusting the settings for that show)
