### ISSUE TITLE
Log Viewer not displaying "live" log with TVDB Accuracy Check

### ISSUE THREAD

**Issue by TommySnyder** [TV-Rename/tvrename#976]
TVRename 5.03
When running TVDB Accuracy Check the TVRename Log Viewer does not show the "live" logging as it used to in 4.99 and before.  If you look at the Full Log you can see that additional logging has been added but the display is static to the time that you look at it.  In other words, it does not show continual "live" logging.  In the end, the TVDB Accuracy Check, itself, is performed successfully.
The TMDB Accuracy Check does not have this problem.  It shows "live" logging in the TVRename Log Viewer.

**Comment by SirSparkles** [comment]
Fixed in next version
