### ISSUE TITLE
TVRename out of sync from TVDB.. (for at least one show.. again?)

### ISSUE THREAD

**Issue by rrrevin** [TV-Rename/tvrename#982]
Running 5.0.6. Masterchef (US) won't update to latest, which includes info for S13E06.

When doing a Forced update in TVRenames, the log shows:
2023-07-19 06:21:47|INFO| Status on screen updated: Code 167751 (Everything) plus banners 
2023-07-19 06:21:47|INFO| Update obtained for MasterChef (US) at 1688517831 based on 2023-07-05 00:43:51 
2023-07-19 06:21:50|INFO| TV Rename free again (busy since 2023-07-19 6:21:26 AM) 

_(Note: that update date look suspect, IMHO)_

It's showing:
![image](https://github.com/TV-Rename/tvrename/assets/49560189/dd327f13-93dc-47cd-88dd-20a21a03284d)

However TVDB website shows:
![image](https://github.com/TV-Rename/tvrename/assets/49560189/df173040-9de2-400b-a240-606eb6bf007c)

Again, problems related to https://github.com/thetvdb/v4-api/issues/297 ?

**Comment by TommySnyder** [comment]
As I, sort of, expected,  adding the episode description didn't stimulate TVDB to work right and send the info to the API.
Since this is not a TVRename problem but a TVDB one, I will add Masterchef (US) to our list of problem series on the TVDB Github Issue #299.  You can probably close this Issue here.

**Comment by TommySnyder** [comment]
As I was about to enter Masterchef (US) into #299 I noticed that someone just entered the episode name and description for Masterchef (US) episodes S13E07 and S13E08 in TVDB.  I'd like to wait a day or two before reporting this in case the new information stimulates it to work right.  Nothing worse than reporting something broke and it being ok on its own.

**Comment by TommySnyder** [comment]
They fixed #299.  Do a Force Refresh All and you should be OK now.  I had setup Masterchef (US) on my computer after you posted the Issue and it is showing it fixed here now.

**Comment by rrrevin** [comment]
Looks like they fixed it. Fingers crossed it stays fixed.
