### ISSUE TITLE
5.0.7  Timezone Setting not used at Startup

### ISSUE THREAD

**Issue by TommySnyder** [TV-Rename/tvrename#984]
Just to add to the mayhem, I don't shut down TV Rename often but when I do and I start it up again, I notice that the two soap operas that I've been writing about have their times wildly off.  I determined that the shows that have their timezones as "GMT+10" and whatever don't start using that setting initially.  I have to go into Edit for each show and simply click on OK and then it uses the adjusted offset time.

**Comment by SirSparkles** [comment]
5.0.8 should help - let us know how you go
