### ISSUE TITLE
Scan stalls with "Obtained 500 responses from lastupdated query" when attempting to use TheTVDB Token

### ISSUE THREAD

**Issue by joachimweyl** [TV-Rename/tvrename#988]
# Bug Details

When attempting to use any of the scan's the app does not move past scanning. No progress bar. if I look in the TVRename.log I see a bunch of errors that include this "Obtained 500 responses from lastupdated query" right after getting the New Token from TheTVDB.

**Expected Behaviour**

scan, progress bar, display rename options list based on files found.

**Current Behaviour**

stops on Download Progress window, no progress bar

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Scan
2. Click on Quick Scann (or any of the other scans)
3. wait for Scan Progress window/popup
4. wait for Download Progress window/popup
5. no error just nothing happens
6. log gets a bunch of "Obtained 500 responses from lastupdated query" after 
7. it also happens if I try to do a background update, basically anything where i try to access TheTVDB

Has happened on and off for a while, and I would just install an older version and it would fix it but I would like the new version so Now I want to see if there is a way to fix it

**Context**

* Operating System: Windows 11
* windows version

## Screenshots or videos of the issue

![image](https://github.com/TV-Rename/tvrename/assets/28782106/d90f8f84-ec34-488b-90db-c5dcdb8c2e1f)

**Comment by joachimweyl** [comment]
I was able to do a scan by going offline but of course that will not provide me with any new information.

**Comment by SirSparkles** [comment]
Try a “force refresh all”. That should get a full download of all the data and get you back in sync

**Comment by TommySnyder** [comment]
It is a common problem if you don't run TV Rename often.  When was the last time you ran TVR before this?
Solution: do a "Force Refresh All" and wait patiently while it completes.
See [https://github.com/TV-Rename/tvrename/issues/964](url)

**Comment by joachimweyl** [comment]
I scan once a week or if I go on vacation once in 2 weeks. I will try the "Force Refresh All" next time thank you.

**Comment by SirSparkles** [comment]
Sometimes TVDB do a batch update of all of their shows. When they do the 'changes' queue of updates is very conjested and TV Rename takes ages to get back in line. You can either be patient and let it run (possibly overnight!) or do a 'froce refresh all'. 

Feel free to reopen if that does not resolve the issue
