### ISSUE TITLE
Not initializing... at all

### ISSUE THREAD

**Issue by airduern** [TV-Rename/tvrename#989]
Hi team, 

I installed TV Rename 5.0.8 on Win 10 Pro x64 last update. 
I downloaded window version installer from https://www.tvrename.com/.
On first launch, I've been asked to install .NET Runtime 6.0.0 and ASP.NET 6.0.0. 
I installed both. 
When I launched TV Rename again, I can see my cursor showing a loading in progress for 5s, then... nothing. No splash screen, no window blink, nothing. I never could open TV Rename even once... Not even an error message... 

Expectations: ...to see a window opening with TV Rename displayed into it. 

I tried starting it in admin, no change. 
I uninstalled, reinstalled 3 times, no change. 
I tried installing previous version until 4.9.4, no change. 

I found neither userfilepath nor log, nor any TV Rename folder in Roaming folder. 

I tried finding a similar bug report among the 39 active reports, but found no similar report. 

I added a video capture in attachement. 'Hope it will help... 
https://github.com/TV-Rename/tvrename/assets/142394227/39d4ccf0-e351-4ff3-8b1e-0ba6f64f41f3

Thank you for your help.

**Comment by TommySnyder** [comment]
Download and install -  [https://download.visualstudio.microsoft.com/download/pr/e3f91c3f-dbcc-44cb-a319-9cb15c9b61b9/6c87d96b2294afed74ccf414e7747b5a/dotnet-sdk-7.0.400-win-x64.exe
](url)

**Comment by TommySnyder** [comment]
Hmmm... I wasn't expecting that.   Usually that does the trick.  Let me think about it some more.

**Comment by TommySnyder** [comment]
Please run  "dotnet --info" (no quotes) from the command line to provide a list of all your active dotnets.  Copy the list here.

Just so you know I'm following what went on in a previously closed issue - [https://github.com/TV-Rename/tvrename/issues/954](url)
That ended in success so I'm hoping that following it's ways will also lead to success.  We need to find out what dotnet you are missing.

**Comment by airduern** [comment]
Thank you Tommy, 
Here we go with .NET installed packages.
![dotnet_info](https://github.com/TV-Rename/tvrename/assets/142394227/32049598-6135-4b2e-ae19-beed42419d58)

**Comment by airduern** [comment]
Wow! I was reading the topic you provided. I installed .NET SDK 6... and it worked!
![tvRename_run](https://github.com/TV-Rename/tvrename/assets/142394227/c49c15ff-ed14-4281-929b-bbb79f9181ad)
