### ISSUE TITLE
Tv Rename Freeze when adding movie

### ISSUE THREAD

**Issue by LucDeGit** [TV-Rename/tvrename#992]
Hello, 

I run the latest version of tv rename 5.0.8.
The issue is that after add a movie (search it and select the emplacement) the window "Download Progress" appear and the app freeze.

The only way to quit the app is via Task Manager.

**Comment by FirstLine1** [comment]
I have the same problem.

**Comment by HairyOtter** [comment]
Same but for me it's happening when adding TV shows.

**Comment by Sphaa80** [comment]
I have the same problem with TV shows. But if I wait 15-20 min on the "Download Progress" window it will eventually finish downloading and work correctly. Still, waiting 20 min for downloading info about one show is a very long time. In this example I tried to add a show with only one season and 10 episodes, and I have no other shows added to TVrename. Can also add that after I've added the show TVRename is using 1,35Gb RAM (dont know if it's normal or not)

**Comment by tanakaeru01** [comment]
Also happening for me as well on 5.0.8, it takes noticeably longer and sometimes freezes when adding a single show and gets frozen on the 'Download Progress' window.

**Comment by omega552003** [comment]
It is working, the progress bar no longer works. I was sorting South Park and it took TV Rename about 5 mins to finish.

**Comment by SirSparkles** [comment]
If you look in the log file:  [here](https://www.tvrename.com/manual/technical/#:~:text=The%20main%20active%20log%20file,the%20application%20used%20as%20normal.) you will see that there are many updates coming through from one of the sources.

**Force refresh all generally fixes these problems.**
